### ISSUE TITLE
jackd2: Jackd will not start if X not running

### ISSUE THREAD

**Issue by adiknoth** [jackaudio/jack2#10]
Forwarded from http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=670112

While previous versions of jackdmp with dbus support merely printed an
error when unable to connect to X, this one will actually fail to start
as discussed here:
http://permalink.gmane.org/gmane.comp.audio.jackit/25430

This makes it impossible to use the current debian package of jackd2 on
any system which doesn't have X installe or is not currently running it
and requires rebuilding the package without the --dbus configure flag.

**Comment by adiknoth** [comment]
Please remind me to comment on this later. The pull request looks interesting, but maybe should be split.

**Comment by 7890** [comment]
Env variable $JACK_NO_AUDIO_RESERVATION targets this issue.
