### ISSUE TITLE
Is it possible to compile for OSS 4 on linux?

### ISSUE THREAD

**Issue by lapsio** [jackaudio/jack2#103]
Is it possible to compile JACK2 on linux running OSS v4?

**Comment by sletz** [comment]
There is a OSS driver that was develop for Solaris (JackOSSDriver.h,cpp files), it may work on Linux assuming you adapt the "waf" build system to compile and deploy it.

**Comment by lilrc** [comment]
Are you still interested in this or should we close this? It should not be too hard to fix I hope.

**Comment by lapsio** [comment]
Well. OSSv4 driver requires continuos source patching for every new major kernel release. Few months ago I got to the point it didn't want to compile under any circumstance under OpenSUSE linux so I gave up after many years of using OSS. But on Arch OSS package is still maintained so I think many people may still find it interesting. Maybe once I'll be reinstalling OS I'll hit this problem once again because I'm not really satisfied with ALSA support for my soundcard comparing to what OSS offered.

**Comment by 7890** [comment]
I will close this issue for the following reasons:
-Inactive for some time
-No immediate plan to support OSS "better" than currently is the case
However pull requests to improve (JackOSSDriver.h,cpp files) are welcome. Thanks for caring about JACK!
