### ISSUE TITLE
intermittent sudden sample rate / pitch problems

### ISSUE THREAD

**Issue by comotion** [jackaudio/jack2#104]
Hello,
we have a Mackie Onyx 1640i / FireWire in our studio which works suprisingly well with jack and ffado. However, we are experiencing intermittent changes in pitch / sample rate which make the mixer both record and output with incorrect pitch and bpm. There are no indications in the jack / ffado logs, even when verbose logs is enabled, that these sample rate events occur. 
This is a showstopper for us, so we welcome the help to debug this issue.

Platform is Ubuntu 14.04 64bit
04:00.0 FireWire (IEEE 1394): Texas Instruments TSB43AB23 IEEE-1394a-2000 Controller (PHY/Link)

**Comment by 7890** [comment]
Hi, if this is still relevant, please consult with the ffado project. The mailinglist is usually very responsive. You can subscribe here: https://sourceforge.net/projects/ffado/lists/ffado-user
