### ISSUE TITLE
Jackd starts to eat cpu after some hours of uptime

### ISSUE THREAD

**Issue by milasudril** [jackaudio/jack2#115]
I have started jackd like this:

```
jackd --sync -P85 -p128 -dalsa -dhw:UA25 -r48000 -p64 -n3 -Xraw
```

on kernel `Linux 3.13.0-49-lowlatency` x86-64

It runs smoothly for a long time, and then it seams like jackd gets stuck in a spin-loop steeling 2 out of 4 cores. Since jack is running as a realtime process, the kernel cannot interrupt it locking the system. Why this?

Running it under `cpulimit` works when jackd is not a dull boy. When jackd has locked up, I can access the computer. Sound is interrupted and the system is not running smooth, but at least I can kill jack making the system responsible again.

I realize that this kind of bug can be tricky to find. I guess it would help if I could force a core dump on the spot when it gets stuck.

**Comment by mseeber** [comment]
Thanks for the report!
Does this also happen with other hardware devices?
Does this happen only with this set of parameters?

**Comment by milasudril** [comment]
I need to check other devices and parameters. Do you suspect that any parameter can make it happen earlier? The system works for 12h before it stops, so it is a quite long time.

**Comment by sletz** [comment]
Any ways to dump the thread state of 'jackd' when the problems occurs?

**Comment by milasudril** [comment]
@sletz Under `cpulimit`, it is possible to control the machine although very choppy. If it would help, I can use `gcore` to produce a dump. I took a snapshot in normal state.

**Comment by milasudril** [comment]
Here [1] is a output from apport when it locked up. I manually gave it a SIGSEGV when CPU usage rose.

[1] https://drive.google.com/file/d/0B5Yu7rHDoEpRU1B3cjI5YnlKRHc/view?usp=sharing

**Comment by milasudril** [comment]
I downloaded the latest git and compiled with debug

Here are some more info:

./pidwatch 3122 0.5 0

    3122 was killed due to CPU overload
    Process lifetime:       44749.09
    CPU workload threshold: 0.5
    Latest CPU workload:    0.84
    Workload average:       0.09479103

So it did run for 44749.09 seconds. Workload average does not include the crash value.

Here is a backtrace from gdb:

    #0  0x00007f6fe08371c1 in do_sigwait (sig=0x7ffed398bd90, set=<optimized out>)
        at ../nptl/sysdeps/unix/sysv/linux/../../../../../sysdeps/unix/sysv/linux/sigwait.c:60
    #1  __GI___sigwait (set=0x7f6fe14126c0, sig=0x7ffed398bd90)
       at ../nptl/sysdeps/unix/sysv/linux/../../../../../sysdeps/unix/sysv/linux/sigwait.c:97
    #2  0x00007f6fe11ba1d0 in jackctl_wait_signals ()
       from /usr/lib/x86_64-linux-gnu/libjackserver.so.0
    #3  0x0000000000402f81 in main (argc=10, argv=0x7ffed398c3c8)
       at ../common/Jackdmp.cpp:623

if it is jackd, `jackctl_wait_signals` . But it looks like it did not load my debug version of  `libjackserver.so`. I guess it can be a kernel thing also...

**Comment by milasudril** [comment]
A new update:

The problem does not occur on

    Linux 3.16.0-34-generic #47-Ubuntu SMP Fri Apr 10 18:03:41 UTC 2015 i686 i686 i686 GNU/Linux

and

    kort 0: ICH6 [Intel ICH6], enhet 0: Intel ICH [Intel ICH6]
    Underordnade enheter: 0/1
    Underordnad enhet nr. 0: subdevice #0

So there is no MIDI interface on that machine. Also it is a single core a Intel(R) Pentium(R) M processor 1.73GHz. Would the next thing to try hooking up the UA25 to this machine?

**Comment by milasudril** [comment]
I have found that is spends approximately the same amount of time in kernel and user

    Process lifetime:       44743.74
    CPU workload threshold: 0.5
    Latest CPU workload:    2.055 (kernel=0.875,user=1.18)
    Workload average:       0.1118369 (kernel=0.05955884,user=0.05227809)

**Comment by milasudril** [comment]
The issue is still present on `Linux R3-S6 3.18.19 #3 SMP PREEMPT Tue Jul 28 16:52:18 CEST 2015 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by asbaklm** [comment]
I have the same issue on a PREEMPT 4.2 Kernel system and possibly (it's been a while since using it) another system with a 3.18 or 3.19 PREEMPT kernel. After some hours of uptime the CPU is hogged by jackd and the process has to be restarted to resolve this. My system uses a USB Midi/Audio interface.

**Comment by milasudril** [comment]
@asbaklm After how long time does your system freeze? And what is your sample rate? As said, on my system it looks like some integer overflow in a timer loop. If you can measure the time it takes on your system, this hypothesis can be tested.

**Comment by asbaklm** [comment]
I don't have the exact time but usually during the course of a working day, meaning around the 8 hour or so mark (give or take). System doesn't freeze but jackd eats up available CPU resources.

**Comment by escitalopram** [comment]
@milasudril Was the stack trace you posted exactly from the hanging thread or just from the first available process id? If the latter, maybe the solution of #150  works for you, too? (It's in the current master branch)

**Comment by milasudril** [comment]
@escitalopram I will check if this solution works. I guess it does. But a better solution would be to not use absolute time anywhere. Then it will still work after 3 million years.

**Comment by milasudril** [comment]
I can confirm that the problem has disappeared after upgrading jack.

**Comment by asbaklm** [comment]
The problem is resolved for me as well, after installing this github version of jack2.
