### ISSUE TITLE
Not linking to ALSA (libasound) on Arch linux

### ISSUE THREAD

**Issue by f4bsch** [jackaudio/jack2#132]
The waf configure command detects ALSA properly, but it does not link properly the ALSA library when building. JACK crashes on startup saying that it could not init the ALSA driver and that there are unreferenced symbols (all ALSA related). Also the alsa_in/out example clients cannot be compiled due to undefined references.

I could get it to work by adding the -lasound linker parameter to the root wscript:

`conf.env.append_unique('LINKFLAGS', '-lasound')`

I don't know what's the proper location to add this or where the bug is. 
Somebody know how to merge this properly?

**Comment by mseeber** [comment]
What are the flags you used to configure the waf build?

Please check if

    ./waf configure --alsa

or:

    ./waf configure --alsa=on

does the job for you.

**Comment by lilrc** [comment]
It should not be necessary to add "-lasound" to LINKFLAGS. All necessary flags should be read from alsa.pc. Can you post the content of your alsa.pc file? It should reside somewhere under /usr/lib/pkgconfig or /usr/libXX/pkgconfig depending on your distributions choice.

Also can you post the output of "./waf configure [ALL YOUR OPTIONS GOES HERE]" and the output of "./waf -v"?

**Comment by f4bsch** [comment]
Im configuring with this:
``CXXFLAGS=$NEON_FLAGS  CFLAGS=$NEON_FLAGS ./waf configure --alsa --portaudio=no --prefix=/usr``
Where `NEON_FLAGS="-funroll-all-loops -ftree-vectorize -mfloat-abi=hard -mfpu=neon"`.

I currenlty dont have access to the embedded system (Raspberry PI 2), so can't check OS version, waf version or the pkgconfig files. I think that issue is caused by the latter, though. Will check this and get back with more details. Thanks so far!

**Comment by 7890** [comment]
If this is still an issue, please re-open.

**Comment by dvzrv** [comment]
This should be fixed since long I think. Just checked again for the jack2 package on Arch Linux (I currently maintain it) and we definitely link against libasound.so.2. As Arch Linux ARM is rebuilding our packages, it should be the same there (unless they do custom modifications for some reasons).
