### ISSUE TITLE
 Segmentation fault in jack library

### ISSUE THREAD

**Issue by corfuvalentin** [jackaudio/jack2#140]
Hi,
I observed one segmentation fault in this library:

    Program terminated with signal 11, Segmentation fault. 
    #0  0xb6be5656 in sem_getvalue@GLIBC_2.0 () from /lib/libpthread.so.0 
    (gdb) bt 
    #0  0xb6be5656 in sem_getvalue@GLIBC_2.0 () from /lib/libpthread.so.0 
    #1  0xb67b9ef0 in Jack::JackPosixSemaphore::ConnectInput(char const*, char const*) () from /usr/lib/libjack.so.0 
    #2  0xb67bc418 in Jack::JackLibClient::ClientNotifyImp(int, char const*, int, int, char const*, int, int) () from /usr/lib/libjack.so.0 
    #3  0xb679c02a in Jack::JackClient::ClientNotify(int, char const*, int, int, char const*, int, int) () 
    from /usr/lib/libjack.so.0 
    #4  0xb67be5d1 in Jack::JackSocketClientChannel::Execute() () from /usr/lib/libjack.so.0 
    #5  0xb67b8fe5 in Jack::JackPosixThread::ThreadHandler(void*) () from /usr/lib/libjack.so.0 
    #6  0xb6bdee19 in start_thread () from /lib/libpthread.so.0 
    #7  0xb6a3cffe in clone () from /lib/libc.so.6 
    (gdb)

I'm also think that the seg fault is due to sem_getvalue() of NULL semaphore.
So I'm suggesting this kind of fix...

    diff --git a/posix/JackPosixSemaphore.cpp b/posix/JackPosixSemaphore.cpp
    index 63e0e8f..7969b7f 100644
    --- a/posix/JackPosixSemaphore.cpp
    +++ b/posix/JackPosixSemaphore.cpp
    @@ -166,11 +166,14 @@ bool JackPosixSemaphore::ConnectInput(const char* name, const char* server_name)
     if ((fSemaphore = sem_open(fName, O_CREAT)) == (sem_t*)SEM_FAILED) {
         jack_error("Connect: can't connect named semaphore name = %s err = %s", fName, strerror(errno));
         return false;
    -    } else {
    +    } else if (fSemaphore){
         int val = 0;
         sem_getvalue(fSemaphore, &val);
         jack_log("JackPosixSemaphore::Connect sem_getvalue %ld", val);
         return true;
    +    } else {
    +        jack_err("ackPosixSemaphore::Connect sem_getvalue: not initialized!");
    +        return false;
       }
    }

What do you think?

(I'm using jack version 1.9.9.5.)

Best Regards,
Valentin Corfu

**Comment by sletz** [comment]
OK. Fixed on git.

St�phane

Le 3 sept. 2015 � 10:34, Valentin Corfu <notifications@github.com> a �crit :

**Comment by corfuvalentin** [comment]
I observed that in commit: 008872fc167deb82e2b16e34ff3dc9e431186bc4, you added other changes in addition of suggested fix. 
It is all related to this seg fault?

Regards,
Valentin Corfu

**Comment by corfuvalentin** [comment]
Ouch! I got it! :) 
That piece of code is commented.

**Comment by lilrc** [comment]
@sletz, can we close this or are you going to do more with this bug?

**Comment by corfuvalentin** [comment]
Yes. Thank you!
