### ISSUE TITLE
How to use the examples to route audio from input mic to output speaker like a loop

### ISSUE THREAD

**Issue by sriranjanr** [jackaudio/jack2#146]
Hello,

I am new to jack audio and alsa. Could someone please tell me how to use an example to route audio from input to output i.e from mic to speaker? I tried to run simple_client but could not run it as it asks to specify a name. I have connected USB sound cards to my linux laptop running ubuntu.

**Comment by mseeber** [comment]
Have a look at the man pages of [jack_connect (1)](http://dev.man-online.org/man1/jack_connect/) and jack_disconnect.

**Comment by nedko** [comment]
There is no reply from the OP since he requested help in September. Thus I'm closing this issue.
