### ISSUE TITLE
Jack For Windows Binaries disabled

### ISSUE THREAD

**Issue by mores** [jackaudio/jack2#147]
I am unable to download:
https://dl.dropboxusercontent.com/u/28869550/Jack_v1.9.10_64_setup.exe

"Error (429)
This account's public links are generating too much traffic and have been temporarily disabled!"

Code::Blocks latest version is 13.12 - Is it recommended to use 10.05 or 13:12 ?

**Comment by mseeber** [comment]
@sletz If dropbox stays unreliable like this, an alternative could be to attach the binaries to the release tags of jack2 on github.

**Comment by LaKing** [comment]
Is there any progress on this?

Dropbox is not made for this. Do you need a host sharing files?

**Comment by mseeber** [comment]
@sletz Would you consider adding the binarys for windows to the tags on GitHub? I think this might be the most easy solution right now.

**Comment by Silmerias** [comment]
Issue temporary fixed in the wait of the owner solution.

http://wahou.net/dl/Jack_v1.9.10_64_setup.exe
http://wahou.net/dl/Jack_v1.9.10_64_setup.exe.md5sum

Virus free, scanned 2017-03-17

**Comment by QLQL** [comment]
Thank you!

**Comment by publicdoename** [comment]
@mseeber I agree 100%.  It seems like kind of a no-brainer. This is the first C/C++ or G/G++ source I have tried to compile on windows and it is driving me nuts. I've successfully compiled code on Linux many times. Unfortunately, I need it for a program that is Win/OSX only. I think I am going to hang my hat and download an .exe I found on the JACK mailing list. I had really hoped today would be the day I learned to compile on windows, but there are two many little tweaks to get it to compile. Tired of feeling like an ouroboros. End rant. Peace, everyone.

**Comment by redtide** [comment]
Old website related issue, the links was fixed.

**Comment by trebmuh** [comment]
@redtide if fixed, can you close then?

**Comment by redtide** [comment]
> @redtide if fixed, can you close then?

Nope, I have only write access on the website repository, I saw this issue related to one there so I drop a message here for who can do it.

**Comment by falkTX** [comment]
I will close this now
