### ISSUE TITLE
  Jackd starts to eat 200% cpu after some hours of uptime

### ISSUE THREAD

**Issue by escitalopram** [jackaudio/jack2#150]
Hi,
I think this problem is not the same as issue #115, because in #115 there was no MIDI and the stack trace would be different.

After some hours of uptime, jackd (jackdmp version 1.9.10 tmpdir /dev/shm protocol 8) would hog exactly 2 of my processor cores, a number which happens to coincide with the number of alsa midi ports on my setup.

Also, when I attach gdb to pause the hanging threads, the sound still works, but I haven't tested MIDI under that circumstances yet.

I installed a debug build and when I attached gdb to one of the hanging threads, it stopped at `alsa_rawmidi.c:865`, which would be a poll call in `midi_thread()`. I'm not intimately familiar what happens there, but it seems to me like that would be a loop that puts ALSA MIDI events into jackd.

I think that to some extent I know what the problem is: It seems to be a kind of misunderstanding of how `poll()` works. I suggest that, because in my `man 3 poll` it says, that `POLLERR` and `POLLNVAL` are 'only valid in the `revents` member' of `pollfd`, as opposed to the `events` member, with which they are used in that function. Furthermore, it seems that the result of the poll call is only checked for `POLLIN` events. I'd guess if some kind of error condition arises, `POLLERR` or something would be raised in `revents` which sends the thread into a CPU hogging endless loop because the error condition is presumably not dealt with, so the `poll()` call immediately returns again every time.

Unfortunately, when attaching gdb, the process randomly crashes during debugging, so I couldn't yet find out about the error condition actually happening to me when the CPU hogging starts.

**Comment by asbaklm** [comment]
I suspect I am affected by the same issue, jackd hogs the cpu after a few hours uptime. This problem has been around for a long time. Restarting jackd temporarily works around the issue but doesn't ultimately resolve it.

**Comment by escitalopram** [comment]
I could confirm that `poll()` in fact does return `POLLERR` in `pfds[0].revents` when the CPU hogging is in progress. Also, it seems like all the sleep- and timeout durations are set to 0 (although that is presumably an artifact of the debugging process). I'm now running a modified build that will output more error information as soon as it locks up again.

**Comment by escitalopram** [comment]
It looks like it has nothing to do with the `poll()`. It seems like the lockup occurs after 2^31-1 samples. I'm currently testing a fix based on that, and if it works, I'll submit a pull request.
