### ISSUE TITLE
Feature: Can CLIENT_NUM be a startup option?

### ISSUE THREAD

**Issue by dellgreen** [jackaudio/jack2#160]
I have a 128 channel Dante card. I am currently running tests with 64 concurrent players using Jackd2. In Qjackctl only 60 of the 64 are showing up. If i recompile jackd changing CLIENT_NUM to 128 then I get 64 clients as expected.

Is there a particular reason that 64 client max was chosen? 
Could it be a added as a startup option to avoid recompiling and continue to use distro package version

**Comment by sletz** [comment]
Le 26 nov. 2015 � 12:48, dellgreen <notifications@github.com> a �crit :

> I have a 128 channel Dante card. I am currently running tests with 64 concurrent players using Jackd2. In Qjackctl only 60 of the 64 are showing up. If i recompile jackd changing CLIENT_NUM to 128 then I get 64 clients as expected.
> 
> Is there a particular reason that 64 client max was chosen? 

This constant is used in some "compile time allocated arrays"


> Could it be a added as a startup option to avoid recompiling and continue to use distro package version

Nope since this is actually constants  a "compile time allocated arrays."

**Comment by dellgreen** [comment]
Ok, many thanks
