### ISSUE TITLE
64bit jackd2 and 32bit clients

### ISSUE THREAD

**Issue by QkiZMR** [jackaudio/jack2#183]
Is it possible to use 64bit jackd2 with 32bit clients like Renoise, vsthost or Wine? I'm on Ubuntu and if I use that configuration I got no sound and midi.

**Comment by falkTX** [comment]
some recent changes broke IPC semaphores between 64bit and 32bit.
I don't know what exactly changed and where sorry, but I can confirm it started happening on Ubuntu 15.04 (codename 'vivid').

**Comment by QkiZMR** [comment]
If I compile jackd2 to 32bit binaries (on 64bit system) there will not be problems with semaphores?

**Comment by QkiZMR** [comment]
I installed Jackd2 from KXStudio repositories and problem gone.

**Comment by Gimmeapill** [comment]
I can confirm the issue is still here on Arch 64 (jack2 1.9.10).

**Comment by falkTX** [comment]
Adding some information to this.
https://lists.debian.org/debian-glibc/2016/03/msg00029.html
https://sourceware.org/bugzilla/show_bug.cgi?id=17980

The old (working) behavior was never officially supported.

**Comment by Ace17** [comment]
I confirm this problem currently affects Debian "testing" (stretch).
