### ISSUE TITLE
Problem compiling jack2 with opus

### ISSUE THREAD

**Issue by asbaklm** [jackaudio/jack2#184]
Hi there

I'm trying to compile jack2 on Mint / Ubuntu 14.04 with opus for netjack2 but it doesn't seem to like the opus_custom.h file and fails. jack2 builds provided --opus=no is specified.

I'm using latest opus 1.1.2. For some reason opus also doesn't install opus_custom.h in /usr/local/include/opus so this has to be copied in manually.

There aren't any Ubuntu libopus-dev packages installed on the system.

What am I doing wrong, or is netjack2 opus not working at the moment?

**Comment by lilrc** [comment]
Hi!

Well, there are a few glitches in the build system which are on my ToDo list, but I am terribly short on time for the time being. See #176. Also #37 is relevant. You will definitely need the -dev packages to build jack2 from source anyway, but as noted in #37 you will not get the opus_custom.h header, which is needed.

In the end you will need opus built with --custom-modes, which Mint does not provide, so you will need to compile it from source.

PR #145 is also related.

**Comment by asbaklm** [comment]
I see! 

Thanks a lot for the clarification about building Opus with --custom-modes.

The jack dev package I used on Ubuntu/Mint was this one. libjack-jackd2-dev:amd64

I then created and installed a dummy jackd package and put it on hold to try and prevent any accidental installations of jack packages so I didn't have both Ubuntu libraries and self-compiled ones on the system.

PR#145 was interesting to read. Many thanks again, I really appreciate your help.

**Comment by asbaklm** [comment]
So I tried it after removing previous opus build and replacing it with newly compiled versions with --custom-modes but it still doesn't seem to work.

There aren't any Ubuntu opus dev packages installed, the previous opus libraries were uninstalled.
I tried it with opus 1.1.2 and opus 1.1.1

[36/37] Linking build/lib32/common/libjack.so
/usr/bin/ld: skipping incompatible /usr/local/lib/libopus.so when searching for -lopus
/usr/bin/ld: skipping incompatible /usr/local/lib/libopus.a when searching for -lopus
/usr/bin/ld: skipping incompatible //usr/local/lib/libopus.so when searching for -lopus
/usr/bin/ld: skipping incompatible //usr/local/lib/libopus.a when searching for -lopus
/usr/bin/ld: cannot find -lopus
collect2: error: ld returned 1 exit status

Waf: Leaving directory

**Comment by lilrc** [comment]
Are you compiling with --mixed? In that case you also need to compile opus as a 32-bit library.

**Comment by asbaklm** [comment]
Yes I was using --mixed. Thank you very much, I hadn't realised.

**Comment by karllinden** [comment]
Please open a new issue if you have any other problems. Thanks.
