### ISSUE TITLE
Add support for aarch64

### ISSUE THREAD

**Issue by bjharper** [jackaudio/jack2#198]
There is a workaround for packed structures for other architectures in /common/jack/systemdeps.h can the __aarch64__ environment be added please....

#if defined(__arm__) || defined(__aarch64__)|| defined(__ppc__) || defined(__powerpc__)
    #undef POST_PACKED_STRUCTURE
    #define POST_PACKED_STRUCTURE
#endif /* __arm__ || __aarch64__ || __ppc__ || __powerpc__ */

Ill see if I can workout how to make a patch.

Without this workaround on aarch64 platforms jack2d compiles successfully but on startup fails with memory alignment issues and a SIGBUS fault.

Thanks,
Brad.

**Comment by sletz** [comment]
Yes please prepare a patch or merge request

Le 30 mars 2016 � 09:02, bjharper <notifications@github.com> a �crit :

> arm || aarch64 || ppc || powerpc */

**Comment by bjharper** [comment]
Please find the patch attached.

Best Regards

Brad.

[jack2_add_aarch64.txt](https://github.com/jackaudio/jack2/files/195030/jack2_add_aarch64.txt)

**Comment by sletz** [comment]
Applied thanks.

Le 30 mars 2016 � 09:47, bjharper <notifications@github.com> a �crit :

**Comment by lilrc** [comment]
Looks like this is resolved. Closing. Reopen if necessary.
