### ISSUE TITLE
Why are devices being reserved with maximum priority?

### ISSUE THREAD

**Issue by egasimus** [jackaudio/jack2#202]
https://github.com/jackaudio/jack2/blob/7bdad4966b29f721c384bdfe6921a1e5c1d84561/dbus/audio_reserve.c#L84

My Focusrite Scarlett 8i6 USB sound card worked great with JACK on my last few laptops but is now giving me headaches in Arch Linux on Thinkpad W510. ALSA and PulseAudio access work fine, but JACK doesn't, and won't let me try more than once (unless I reboot): after the first failed attempt to launch JACK server, a ReserveDevice1 instance lingers and stops subsequent lauches even if I plug the card into another USB port.

I tried manually releasing that lock via D-Feet, but priority wouldn't allow me to. Digging through the dbus sources, I came across the above piece of code. I've occassionally had ReserveDevice1 issues on other machines, but nothing that didn't resolve itself. Now I'm stuck and can't configure my soundcard.

Tagging @sletz :)

**Comment by falkTX** [comment]
are you using the latest git version?

**Comment by egasimus** [comment]
`jack2dbus 1.9.10-4` from Arch community repo. Building from git is next.

**Comment by falkTX** [comment]
I believe there was a commit about this.
jack was not releasing the device if it failed to open it the first time.

**Comment by falkTX** [comment]
here https://github.com/jackaudio/jack2/commit/57e16b9a056ace3e9de02387bd38f73f9901684d

**Comment by egasimus** [comment]
Works! Thanks @falkTX :)
