### ISSUE TITLE
Raspberry Pi + Raspbian and Sonic Pi - Jack problem?

### ISSUE THREAD

**Issue by Taxicletter** [jackaudio/jack2#203]
Since a kernel update for my Raspberry Pi 3 (kernel version 4.4.6-v7+), **Sonic Pi** opens with a_ critical server error_ and then stops. Looking for a solution, I found Sam Aarons github page (http://github.com/samaaron/sonic-pi/issues) where they say it's a JACK problem.

Is there something I (as user, I'm not a programmer) can do to fix that problem? Some update or install or configuring something?

Thanks a lot

**Comment by 7890** [comment]
Hi, this message "critical server error" most probably doesn't originate from jackd.
Please re-open the issue (if still relevant) with more info, thank you.
