### ISSUE TITLE
Can't build on Ubuntu - /tests/iodelay.cpp - error: 'UINT32_MAX' was not declared in this scope

### ISSUE THREAD

**Issue by loglesby** [jackaudio/jack2#223]
```
[ 86/193] Compiling tests/iodelay.cpp
../tests/iodelay.cpp:171:43: error: 'UINT32_MAX' was not declared in this scope
../tests/iodelay.cpp:171:55: error: 'UINT32_MAX' was not declared in this scope
../tests/iodelay.cpp:172:44: error: 'UINT32_MAX' was not declared in this scope
../tests/iodelay.cpp:172:56: error: 'UINT32_MAX' was not declared in this scope

../tests/cpu.c: In function 'process':
../tests/cpu.c:81:31: warning: variable 'in' set but not used [-Wunused-but-set-variable]

Waf: Leaving directory `/home/vagrant/jack2/build'
Build failed
 -> task in 'jack_iodelay' failed (exit status 1):
	{task 31340368: cxx iodelay.cpp -> iodelay.cpp.4.o}
['/usr/bin/g++', '-Wall', '-I/home/vagrant/jack2/build', '-I/home/vagrant/jack2', '-I/home/vagrant/jack2/build/linux', '-I/home/vagrant/jack2/linux', '-I/home/vagrant/jack2/build/posix', '-I/home/vagrant/jack2/posix', '-I/home/vagrant/jack2/build/common/jack', '-I/home/vagrant/jack2/common/jack', '-I/home/vagrant/jack2/build/common', '-I/home/vagrant/jack2/common', '-DHAVE_DOXYGEN=1', '-DHAVE_ALSA=0', '-DHAVE_FIREWIRE=0', '-DHAVE_FREEBOB=0', '-DHAVE_IIO=0', '-DHAVE_PORTAUDIO=0', '-DHAVE_WINMME=0', '-DHAVE_CELT_API_0_11=0', '-DHAVE_CELT_API_0_8=0', '-DHAVE_CELT_API_0_7=0', '-DHAVE_CELT_API_0_5=0', '-DHAVE_CELT=0', '-DHAVE_OPUS=0', '-DHAVE_SAMPLERATE=0', '-DHAVE_SNDFILE=0', '-DHAVE_READLINE=1', '-DHAVE_PPOLL=1', '-DUSE_CLASSIC_AUTOLAUNCH=1', '-DCLIENT_NUM=64', '-DPORT_NUM_FOR_CLIENT=768', '-DADDON_DIR="/usr/local/lib/jack"', '-DJACK_LOCATION="/usr/local/bin"', '-DUSE_POSIX_SHM=1', '-DJACKMP=1', '../tests/iodelay.cpp', '-c', '-o', '/home/vagrant/jack2/build/tests/iodelay.cpp.4.o']
```

**Comment by mseeber** [comment]
Which version of jack2 are you compiling?  Please make sure to build from a clean build environment.

Which version of glibc `ldd --version` and gcc `g++ --version` are you using?

This is strange, in master, stdint.h was included in this file in ff1ed2c4524095055140370c1008a2d9cccc5645 so this should not happen on master.

**Comment by loglesby** [comment]
Was trying to build from ff1ed2c - rolled back 1 commit and it built fine. Will update with glib and gcc versions as soon as I can.

**Comment by loglesby** [comment]
`ldd (Ubuntu EGLIBC 2.15-0ubuntu10) 2.15`
`g++ (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3`

**Comment by loglesby** [comment]
```
vagrant@precise64:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04 LTS"
```

**Comment by mseeber** [comment]
Oh, EGLIBC, so you are on an embedded system? Most likely on ARM? 32bit?

This is most likely a compiler bug, maybe even this one:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=52764
The description matches your specifications.

If you have the option of upgrading your compiler and your libc or your OS, that would be a solution.

If that is not an option, you could revert the commit for your purposes locally, since you won't compile for c++14 with gcc 4.6 anyway.

**Comment by mseeber** [comment]
Oh wow, have a look at this mess, JACK even has a reference for this and defines this macro on it's own:

https://github.com/jackaudio/jack2/blob/7bdad4966b29f721c384bdfe6921a1e5c1d84561/common/jack/types.h#L38

https://github.com/jackaudio/jack2/blob/7bdad4966b29f721c384bdfe6921a1e5c1d84561/posix/JackSystemDeps_os.h#L29

Seems like it really was a compiler/c++ standard problem.

**Comment by loglesby** [comment]
Yep, wacky compiler issue.
