### ISSUE TITLE
jackd does not report the final configured rate correctly for alsa device

### ISSUE THREAD

**Issue by tomty89** [jackaudio/jack2#232]
So I have a USB audio class device that supports only 16Bit/48KHz signal. I confirmed that by checking the hardware parameters with `aplay -l`. Windows also told me so.

```
HW Params of device "hw:W2":
--------------------
ACCESS:  MMAP_INTERLEAVED RW_INTERLEAVED
FORMAT:  S16_LE
SUBFORMAT:  STD
SAMPLE_BITS: 16
FRAME_BITS: 32
CHANNELS: 2
RATE: 48000
PERIOD_TIME: [1000 2730667)
PERIOD_SIZE: [48 131072]
PERIOD_BYTES: [192 524288]
PERIODS: [2 1024]
BUFFER_TIME: [2000 5461334)
BUFFER_SIZE: [96 262144]
BUFFER_BYTES: [384 1048576]
TICK_TIME: ALL
--------------------
```

When I start `jackd` on it with `-r 44100`, neither does it tell me that this rate can't be used with that device, nor does it report back the fact that it started the device with the only supported rate (48000):

```
[tom@localhost ~]$ jackd -d alsa -d hw:W2 -r 44100 -P
jackdmp 1.9.10
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2014 Grame.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
no message buffer overruns
no message buffer overruns
no message buffer overruns
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
audio_reservation_init
Acquire audio card Audio0
creating alsa driver ... hw:W2|-|1024|2|44100|0|0|nomon|swmeter|-|32bit
configuring for 44100Hz, period = 1024 frames (23.2 ms), buffer = 2 periods
ALSA: final selected sample format for playback: 16bit little-endian
ALSA: use 2 periods for playback
```

I once thought that maybe jack use libsamplerate or zita-resampler to resample the mix before sending it off to the device. But I read from an old issue that jack does not do that. Finally `mpv` showed me that I was wrong:

```
[cplayer] Starting playback...
[af] Audio filter chain:
[af]   [in] 44100Hz stereo 2ch floatp
[af]   [out] 44100Hz stereo 2ch floatp
[af]   [ao] 44100Hz stereo 2ch floatp
[ao] Trying audio driver 'jack'
[ao/jack] requested format: 44100 Hz, stereo channels, floatp
[ao/jack] Channel layouts:
[ao/jack]  - waveext
[ao/jack] result: stereo
[ao/jack] using soft-buffer of 9600 samples.
[cplayer] AO: [jack] 48000Hz stereo 2ch floatp
[cplayer] AO: Description: JACK audio output
[af] Adding filter lavrresample 
[af] Audio filter chain:
[af]   [in] 44100Hz stereo 2ch floatp
[af]   [lavrresample] 48000Hz stereo 2ch floatp [a]
[af]   [out] 48000Hz stereo 2ch floatp
[af]   [ao] 48000Hz stereo 2ch floatp
[cplayer] starting audio playback
[cplayer] playback restart complete
```

So `jackd` did open the device with the rate 48000. It just didn't tell me that.

**Comment by falkTX** [comment]
Why did you close this?

**Comment by tomty89** [comment]
@falkTX oh I was just sort of cleaning up issues opened by myself. It hadn't drawn any attention at all (for over a year) so I figure maybe most people don't think that's a problem.

**Comment by falkTX** [comment]
that's no reason to close it though. if you close it you only lower the chances of it getting viewed.
true that some bugs do not have any activity, but it's usually because the developers cannot reproduce it.
leaving the bug open serves as a reference, if someone later on is able to reproduce or has the same issue, they can comment there.
