### ISSUE TITLE
jack_wait crashes jackd

### ISSUE THREAD

**Issue by tglanfield** [jackaudio/jack2#248]
$ jackd --version
jackdmp 1.9.11 

$ dpkg -l | grep 'jackd2 '
ii  jackd2                                 1.9.10+20150825git1ed50c92~dfsg-4 amd64        JACK Audio Connection Kit (server and example clients)

$ uname -a
Linux xterm 4.8.0-2-amd64 #1 SMP Debian 4.8.15-2 (2017-01-04) x86_64 GNU/Linux

Calling jack_wait -c on a server running jackd results in the following traceback from jackd which then exits.

Jack: JackSocketServerChannel::Execute : fPollTable i = 1 fd = 15
Jack: JackSocketServerChannel::Execute : fPollTable i = 1 fd = 15
Jack: JackSocketServerChannel::ClientCreate socket
Jack: JackSocketServerChannel::BuildPoolTable size = 3
Jack: JackSocketServerChannel::BuildPoolTable fSocketTable i = 1 fd = 15
Jack: JackSocketServerChannel::BuildPoolTable fSocketTable i = 2 fd = 20
Jack: JackSocketServerChannel::Execute : fPollTable i = 1 fd = 15
Jack: JackSocketServerChannel::Execute : fPollTable i = 2 fd = 20
Jack: JackSocketServerChannel::Execute : poll client error err = Success
Jack: JackSocketServerChannel::ClientKill ref = -1 fd = 20
Jack: Client was not opened : probably correspond to server_check
Jack: JackClientSocket::Close
Jack: JackSocketServerChannel::BuildPoolTable size = 2
Jack: JackSocketServerChannel::BuildPoolTable fSocketTable i = 1 fd = 15
Jack: JackSocketServerChannel::Execute : fPollTable i = 1 fd = 15
Jack: JackSocketServerChannel::ClientCreate socket
Jack: JackSocketServerChannel::BuildPoolTable size = 3
Jack: JackSocketServerChannel::BuildPoolTable fSocketTable i = 1 fd = 15
Jack: JackSocketServerChannel::BuildPoolTable fSocketTable i = 2 fd = 20
Jack: JackSocketServerChannel::Execute : fPollTable i = 1 fd = 15
Jack: JackSocketServerChannel::Execute : fPollTable i = 2 fd = 20
Jack: JackRequest::ClientCheck
Jack: Check protocol client = 8 server = 8
Jack: JackRequest::ClientOpen
Jack: JackEngine::ClientExternalOpen: uuid = 0, name = wait
Jack: JackEngine::AllocateRefNum ref = 2
Jack: JackPosixSemaphore::Allocate name = jack_sem.1001_default_wait val = 0
Jack: JackSocketNotifyChannel::Open name = wait
Jack: JackClientSocket::Connect : addr.sun_path /dev/shm/jack_wait_1001_0
Jack: JackShmMem::new index = 2 attached = 39788000 size = 422 
Jack: JackExternalClient::Open name = wait index = 2 base = 39788000
Jack: JackPosixProcessSync::TimedWait time out = 5000000
Jack: JackPosixProcessSync::TimedWait finished delta = 7961.0
Jack: JackEngine::NotifyAddClient: name = wait
Jack: JackDriver::ClientNotify ref = 2 driver = system name = wait notify = 0
Jack: JackExternalClient::ClientNotify ref = 0 client = wait name = system notify = 0
Jack: JackDriver::ClientNotify ref = 2 driver = freewheel name = wait notify = 0
Jack: JackExternalClient::ClientNotify ref = 1 client = wait name = freewheel notify = 0
Jack: JackSocketServerChannel::ClientAdd ref = 2 fd = 20
Jack: JackSocketServerChannel::BuildPoolTable size = 3
Jack: JackSocketServerChannel::BuildPoolTable fSocketTable i = 1 fd = 15
Jack: JackSocketServerChannel::BuildPoolTable fSocketTable i = 2 fd = 20
Jack: JackSocketServerChannel::Execute : fPollTable i = 1 fd = 15
Jack: JackSocketServerChannel::Execute : fPollTable i = 2 fd = 20
Jack: JackRequest::ClientClose
Jack: JackEngine::ClientExternalClose ref = 2
Jack: JackEngine::ClientCloseAux ref = 2
Jack: JackEngine::ReleaseRefnum server quit
JackTemporaryException : now quits...
Jack main caught signal 2
Jack: JackServer::Stop
Jack: JackThreadedDriver::Stop
Jack: JackPosixThread::Stop
Jack: JackSocketServerChannel::ClientRemove ref = 2 fd = 20
Jack: JackClientSocket::Close
Jack: JackSocketServerChannel::BuildPoolTable size = 2
Jack: JackSocketServerChannel::BuildPoolTable fSocketTable i = 1 fd = 15
Jack: JackSocketServerChannel::Execute : fPollTable i = 1 fd = 15
Jack: JackRequest::Notification
Jack: JackDriver::ClientNotify ref = 1 driver = freewheel name = freewheel notify = 18
Jack: JackDriver::ClientNotify ref = 1 driver = freewheel name = freewheel notify = 18
Jack: JackDriver::ClientNotify ref = 1 driver = freewheel name = freewheel notify = 18
Jack: JackDriver::ClientNotify ref = 1 driver = freewheel name = freewheel notify = 18
Jack: JackEngine::ClientNotify: no callback for notification = 4
Jack: JackEngine::ClientNotify: no callback for notification = 4
Jack: JackSocketServerChannel::Execute : fPollTable i = 1 fd = 15
Jack: JackRequest::Notification
Jack: JackRequest::Notification kQUIT
Jack: JackSocketServerChannel::Execute : JackQuitException
Jack: JackPosixThread::ThreadHandler : exit
Jack: JackPosixThread::Stop
Jack: JackEngine::ClientNotify: no callback for notification = 15
Jack: JackEngine::ClientNotify: no callback for notification = 15
Jack: JackServer::Close
Jack: JackServerSocket::Close /dev/shm/jack_default_1001_0
Jack: JackClientSocket::Close
scan: deleted port hw:1,0,0 in-hw-1-0-0-MidiSport-2x2-MIDI-1
Jack: JackEngine::PortUnRegister ref = 0 port_index = 5
Jack: JackEngine::PortDisconnect ref = -1 src = 5 dst = 65535
Jack: JackPosixThread::ThreadHandler : exit
Jack: JackGraphManager::DisconnectAllOutput port_index = 5 
Jack: JackConnectionManager::RemoveOutputPort ref = 0 port_index = 5 
Jack: JackEngine::ClientNotify: no callback for notification = 10
Jack: JackEngine::ClientNotify: no callback for notification = 10
scan: deleted port hw:1,0,1 in-hw-1-0-1-MidiSport-2x2-MIDI-2
Jack: JackEngine::PortUnRegister ref = 0 port_index = 6
Jack: JackEngine::PortDisconnect ref = -1 src = 6 dst = 65535
Jack: JackGraphManager::DisconnectAllOutput port_index = 6 
Jack: JackConnectionManager::RemoveOutputPort ref = 0 port_index = 6 
Jack: JackEngine::ClientNotify: no callback for notification = 10
Jack: JackEngine::ClientNotify: no callback for notification = 10
scan: deleted port hw:1,0,0 out-hw-1-0-0-MidiSport-2x2-MIDI-1
Jack: JackEngine::PortUnRegister ref = 0 port_index = 7
Jack: JackEngine::PortDisconnect ref = -1 src = 7 dst = 65535
Jack: JackGraphManager::DisconnectAllInput port_index = 7
Jack: JackConnectionManager::RemoveInputPort ref = 0 port_index = 7 
Jack: JackEngine::ClientNotify: no callback for notification = 10
Jack: JackEngine::ClientNotify: no callback for notification = 10
scan: deleted port hw:1,0,1 out-hw-1-0-1-MidiSport-2x2-MIDI-2
Jack: JackEngine::PortUnRegister ref = 0 port_index = 8
Jack: JackEngine::PortDisconnect ref = -1 src = 8 dst = 65535
Jack: JackGraphManager::DisconnectAllInput port_index = 8
Jack: JackConnectionManager::RemoveInputPort ref = 0 port_index = 8 
Jack: JackEngine::ClientNotify: no callback for notification = 10
Jack: JackEngine::ClientNotify: no callback for notification = 10
Jack: JackAudioDriver::Detach
Jack: JackEngine::PortUnRegister ref = 0 port_index = 1
Jack: JackEngine::PortDisconnect ref = -1 src = 1 dst = 65535
Jack: JackGraphManager::DisconnectAllOutput port_index = 1 
Jack: JackConnectionManager::RemoveOutputPort ref = 0 port_index = 1 
Jack: JackEngine::ClientNotify: no callback for notification = 10
Jack: JackEngine::ClientNotify: no callback for notification = 10
Jack: JackEngine::PortUnRegister ref = 0 port_index = 2
Jack: JackEngine::PortDisconnect ref = -1 src = 2 dst = 65535
Jack: JackGraphManager::DisconnectAllOutput port_index = 2 
Jack: JackConnectionManager::RemoveOutputPort ref = 0 port_index = 2 
Jack: JackEngine::ClientNotify: no callback for notification = 10
Jack: JackEngine::ClientNotify: no callback for notification = 10
Jack: JackEngine::PortUnRegister ref = 0 port_index = 3
Jack: JackEngine::PortDisconnect ref = -1 src = 3 dst = 65535
Jack: JackGraphManager::DisconnectAllInput port_index = 3
Jack: JackConnectionManager::RemoveInputPort ref = 0 port_index = 3 
Jack: JackEngine::ClientNotify: no callback for notification = 10
Jack: JackEngine::ClientNotify: no callback for notification = 10
Jack: JackEngine::PortUnRegister ref = 0 port_index = 4
Jack: JackEngine::PortDisconnect ref = -1 src = 4 dst = 65535
Jack: JackGraphManager::DisconnectAllInput port_index = 4
Jack: JackConnectionManager::RemoveInputPort ref = 0 port_index = 4 
Jack: JackEngine::ClientNotify: no callback for notification = 10
Jack: JackEngine::ClientNotify: no callback for notification = 10
Jack: JackDriver::Close
Jack: JackConnectionManager::DirectDisconnect last: ref1 = 0 ref2 = 0
Jack: JackGraphManager::DisconnectRefNum cur_index = 2 ref1 = 0 ref2 = 0
Jack: JackEngine::ClientInternalClose ref = 0
Jack: JackEngine::ClientCloseAux ref = 0
Jack: JackGraphManager::RemoveAllPorts ref = 0
Jack: JackDriver::ClientNotify ref = 0 driver = freewheel name = system notify = 1
Jack: JackPosixSemaphore::Destroy name = jack_sem.1001_default_system
Released audio card Audio0
audio_reservation_finish
Jack: JackDriver::Close
Jack: JackConnectionManager::DirectDisconnect last: ref1 = 1 ref2 = 1
Jack: JackGraphManager::DisconnectRefNum cur_index = 2 ref1 = 1 ref2 = 1
Jack: JackEngine::ClientInternalClose ref = 1
Jack: JackEngine::ClientCloseAux ref = 1
Jack: JackGraphManager::RemoveAllPorts ref = 1
Jack: JackPosixSemaphore::Destroy name = jack_sem.1001_default_freewheel
Jack: JackEngine::Close
Jack: JackClientSocket::Close
Jack: no message buffer overruns
Jack: JackPosixThread::Stop
Jack: JackPosixThread::ThreadHandler : exit
Jack: Succeeded in unlocking 82274202 byte memory area
Jack: JackShmMem::delete size = 0 index = 0
Jack: ~JackDriver
Jack: ~JackDriver
Jack: Succeeded in unlocking 1186 byte memory area
Jack: JackShmMem::delete size = 0 index = 1
Jack: Cleaning up shared memory
Jack: Cleaning up files
Jack: Unregistering server `default'

**Comment by falkTX** [comment]
This is not a crash. you're running jackd as temporary, so it automatically quits after the (one and) last client quits, in this case jack_wait.
Also your version of jack2 is quite old, a lot has changed since 2015-08-25.
