### ISSUE TITLE
Download links are down

### ISSUE THREAD

**Issue by tmavuk** [jackaudio/jack2#258]
The DropBox download links on the website are broken. If you could provide links for Win 64-bit setup, it'd be much appreciated.

**Comment by AlCan13** [comment]
I am also needing Win 64-bit download to work, please.
is it so difficult or time consuming that you can not resolve this for a week(s)???
so many people depend on this now!

**Comment by sletz** [comment]
The latest versions of jack2 for windows and osx are included with radium.
OSX: http://users.notam02.no/~kjetism/radium/demos/macosx/?C=M;O=D
Windows: http://users.notam02.no/~kjetism/radium/demos/windows64/?C=M;O=D

**Comment by ssfrr** [comment]
also now downloadable from github: https://github.com/jackaudio/jackaudio.github.com/releases

**Comment by AlCan13** [comment]
thank you guys.
Appreciate your help.

**Comment by AlexanderPlaza** [comment]
I would highly recommend you update the website with that link to the github page.

**Comment by mseeber** [comment]
@AlexanderPlaza noted, this is already work in progress, the push of the changes to the webserver is just blocked by something that needs to be organized first. The Download page would look like this right now: https://jackaudio.github.io/downloads/

**Comment by mvastola** [comment]
@mseeber FYI, if you don't already know this, the source code links on https://github.com/jackaudio/jackaudio.github.com/releases link to a snapshot of the [jackaudio/jackaudio.github.com](https://github.com/jackaudio/jackaudio.github.com) repo at the time the releases were posted.

**Comment by mseeber** [comment]
@mvastola Yes, this is a known limitation that currently exists.

**Comment by Gimmeapill** [comment]
Broken Dropbox links for months. Sorry guys, but this gives a pretty amateurish image of the project. How hard can it be to put a link to [https://github.com/jackaudio/jackaudio.github.com/releases] on the web site?

**Comment by Gimmeapill** [comment]
OK, got it. https://github.com/jackaudio/jackaudio.github.com is the website template, and the 1.9.11 release tarball there is from the first of April so it probably makes only fart noises or something like that.
My bad & sorry for the harsh comment.
Still, that web site needs an update...

**Comment by Gimmeapill** [comment]
Download links fixed - Thanks falkTX !

**Comment by falkTX** [comment]
Nice, thanks for confirming.
Any other broken links just let me know (or better, open a bug report!)
