### ISSUE TITLE
64-bit windows installer installs in "Program Files (x86)"

### ISSUE THREAD

**Issue by ssfrr** [jackaudio/jack2#259]
The default path for the windows 64-bit installer (downloaded from [here](https://github.com/jackaudio/jackaudio.github.com/releases/download/jack2-1.9.10_6/Jack_v1.9.10_64_setup.exe)) installs to "C:\Program Files (x86)\Jack". AFAIK that's the expected path for a 32-bit application on 64-bit windows. Should it be "Program Files" rather than the "(x86)" variant as it's a 64-bit application?

**Comment by lordcheeto** [comment]
It should be, but it doesn't break anything. It's [just a convention](https://www.howtogeek.com/129178/why-does-64-bit-windows-need-a-separate-program-files-x86-folder/) that was introduced with 64-bit Windows.

The [CreateInstall setup files](https://github.com/jackaudio/jack2/blob/master/windows/Setup/jack64.ci) would need to be updated with the [WOW64Redirection flag](http://www.createinstall.com/help/install-64-application.html).

**Comment by szszoke** [comment]
This doesn't seem to be the case anymore. The 64-bit installer correctly installs in `Program Files` instead of `Program Files (x86)`.
@falkTX this issue can be closed.

**Comment by falkTX** [comment]
Indeed, thanks for the notification.
