### ISSUE TITLE
macOS Sierra - No Binaries Found for Jack2

### ISSUE THREAD

**Issue by hasnainbangash** [jackaudio/jack2#260]
Could someone please provide with me **jack2 binaries that work with macOS Sierra**? The dropbox linked on http://jackaudio.org/downloads/ returns a "File Not Found" page and I don't have the dependencies to compile jack on OSX myself. I am running jack on arch linux and want to use net jack on macOS Sierra in order to connect them both but I can't find a **complete package of jack2 with jackrouter and jackpilot that is compatible with macOS Sierra**. The version on brew is jack1 and does not come with jackrouter and jackpilot and is not starting with macOS Sierra.
I hope jack connection kit is still in active development because it is a great program.
Thanks

**Comment by hasnainbangash** [comment]
I found the link to the latest mac build here:
https://github.com/jackaudio/jackaudio.github.com/releases

Does jack 0.92_b3 come with netjack?

**Comment by hasnainbangash** [comment]
I can confirm that jack on arch linux and jack 0.92_b3  macOS sierra can be connected through the net driver (jack_load netmanager  on server/master) and net back-end in qjackctl (slave) through ethernet; although with clicks and xruns.

**Comment by Goles** [comment]
Thanks for that @hasnainbangash
