### ISSUE TITLE
Wishlist: APT package without DBUS

### ISSUE THREAD

**Issue by npes-95** [jackaudio/jack2#262]
I was recently trying to run jack2 on a headless Raspberry Pi (installed using apt-get), and ran into problems when DBUS stopped the server from starting because it couldn't open an X11 window. 

Eventually I figured out how to install jack2 without DBUS using the instructions given in the README, but it might be useful to make available a separate APT package that does not come with jackdbus compiled by default?

I'm willing to have a go at implementing this myself, but this would be my first time contributing to open source, so there would have to be some oversight from a more experienced contributor.

**Comment by falkTX** [comment]
This is not something that needs to be done in JACK project,
You need to request this in your distro, which for you I guess it's Debian.

**Comment by npes-95** [comment]
Okay I see, I'll get on that :)
