### ISSUE TITLE
integration with gnome

### ISSUE THREAD

**Issue by miguel-negrao** [jackaudio/jack2#268]
I think of jack as a service, similar to printing, or wifi. When I need it I activate it, when I don't need it I deactivate it, and sometimes I need to change the configuration (e.g. from alsa to firewire). This type of services in gnome are usually configured in the system configuration control center and also with drop-down menus in the top bar.

It would be very useful if jack could be configured on a gnome system in the control center, like printers, wifi, or this type of services. It would also be nice to have visual feedback on the state of jack on the top bar and be able to start stop it from there. My question is, has something like this been discussed ? 

As far as I'm aware there isn't any GUI that shows 1-1 the jackdbus configuration, and allows changing it. Qjackctl uses it's an internal configuration and overwrites the settings in jackdbus instead of fetching the current configuration using dbus. Currently the user experience for using jack is quite rough... I think the experience would be much more pleasant in a gnome system if it was properly integrated into the gnome guis and if it was configures out of the box as a service (systemd unit ?). Now that ubuntu is also switching to gnome, the number of users of gnome is going to increase quite a lot, this would be useful for a lot of users.

**Comment by falkTX** [comment]
Cadence does exactly what you mention, regarding jackdbus 1-1 configuration.
See http://kxstudio.linuxaudio.org/cadence

**Comment by miguel-negrao** [comment]
Ah, somehow I wasn't aware of cadence. Indeed that is great for configuring and checking on the status of jack via dbus, works great on my debian testing system.

**Comment by SpotlightKid** [comment]
See also https://github.com/SpotlightKid/jack-select,

Concerning QJackCtl storing its own configuration: how else would different configurations you can switch between be stored? Via D-Bus you can only get the current configuration.

Anyway, this issue can be closed, can it not?

**Comment by SpotlightKid** [comment]
Because there are at least two solutions, which do (part of) what you are asking. Admittedly, the info about the current parameters of JACK, which Cadence or jack-select are showing, consist of relatively few major pieces of data, but these could be extended.

Anyway, I think that this is really out of the scope of jack. It already provides a way to get at the information. Clients, which use this information are highly dependant on the environment, in which they are used (desktop, console, etc.).

**Comment by miguel-negrao** [comment]
Right, the suggestion would probably be more appropriate in gnome issue tracker than here. Feel free to close it.

**Comment by SpotlightKid** [comment]
Also, feel free to have a look at `jack-select` and suggest improvements in its issue tracker.
