### ISSUE TITLE
JackPosixSemaphore times out when laptop is suspended overnight

### ISSUE THREAD

**Issue by anderspapitto** [jackaudio/jack2#269]
If I suspend my laptop overnight (I'm not sure how long is actually needed, but overnight does it every time), the connection to all clients breaks (generally, Reaper and/or Pulseaudio). I see this in the output of journalctl after resuming

```
May 31 09:38:13 gurney xsession[1530]: JackPosixSemaphore::TimedWait err = Connection timed out
May 31 09:38:13 gurney xsession[1530]: SuspendRefNum error
May 31 09:38:13 gurney xsession[1530]: JackClient::Execute error name = REAPER
```

I have version 1.9.10

```
$ jackd --version
jackdmp 1.9.10
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2014 Grame.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
no message buffer overruns
no message buffer overruns
no message buffer overruns
jackdmp version 1.9.10 tmpdir /dev/shm protocol 8
```

I'm on linux, kernel version 4.10.10, distro NixOS

**Comment by falkTX** [comment]
your version of jack is too old, latest git is no longer using semaphores for linux.
I'll do a release soon (RC1), so NixOS will be able to pick it up. Please re-test after that.

**Comment by anderspapitto** [comment]
ok. In that case, the README should be updated as well - it currently says things like "The use of POSIX named semaphore is implemented but still a bit unstable." even in the master branch.

Where can I go/watch to keep track of the new RC?

**Comment by falkTX** [comment]
someone in the NixOS community has been trying to force a jack2 release for quite some time, I'm sure it will get updated in NixOS quickly after the RC is out.

**Comment by anderspapitto** [comment]
I installed a build of master and the problem is indeed gone. I'll close this.
