### ISSUE TITLE
"alsa_in -r" bad reception of values

### ISSUE THREAD

**Issue by MarioMey** [jackaudio/jack2#278]
Manual says:
> -r  sample_rate
>     Set sample_rate. The program resamples as necessary.  So you can connect a 44k1 jackd to a soundcard only supporting 48k. (default is jack sample_rate)

When I do, I get:
```
mario@circo3d-md:~$ alsa_in -j mic_webcam -d hw:C920 -r 48k -v
Jack: JackClient::SetupDriverSync driver sem in flush mode
Jack: JackPosixSemaphore::Connect name = jack_sem.1000_default_mic_webcam
Jack: JackPosixSemaphore::Connect sem_getvalue 0
Jack: Clock source : system clock via clock_gettime
Jack: JackLibClient::Open name = mic_webcam refnum = 4
WARNING: Rate doesn't match (requested 48Hz, get 16000Hz)
WARNING: buffer size does not match: (requested 2048, got 262144)
WARNING: period size does not match: (requested 1024, got 131072)
selected sample format: 16bit
Jack: JackClient::PortRegister ref = 4 name = mic_webcam:capture_1 type = 32 bit float mono audio port_index = 11
Jack: JackClient::PortRegister ref = 4 name = mic_webcam:capture_2 type = 32 bit float mono audio port_index = 12
Jack: JackClient::Activate
...
```
Despite that the microphone (Logitech C920 webcam) doesn't have 48kHz as one possible sample rate... look at the line: "WARNING: Rate doesn't match (requested **48Hz**, get 16000Hz)". That it is very different to **48kHz**.
But, if I do:
```
alsa_in -j webcam-mic -c 2 -d hw:C920 -r 480000 -v
```
it says:
```
...
WARNING: Rate doesn't match (requested 48000Hz, get 32000Hz)
...
```
This is different. This command is converting wrong 48k to 48000. Or manual is wrong.

**Comment by MarioMey** [comment]
Debian-Mate 9, x64
Jack 1.9.11

**Comment by 7890** [comment]
You can not use 'k' in the sample rate argument. This is ambiguous in the man page, where 44k1 and 48k are used as shortcuts to say 44100 and 48000.
