### ISSUE TITLE
Killing one jackd affects other jackd servers

### ISSUE THREAD

**Issue by milasudril** [jackaudio/jack2#280]
I start a secondary JACK server in my screenshot script

    export JACK_DEFAULT_SERVER=dummy
    jackd --no-mlock -p 64 --no-realtime -d dummy -p 4096 &
    jack=$!
    timeout 10 jack_wait -w --server $JACK_DEFAULT_SERVER

    # Start client and do stuff with it

When the script should exit

    kill $jack

Now, it is impossible to connect to the "real" jack server. Killing it

    kill -9 $jack

solves the problem. I guess it deletes too much when it does a clean shutdown.

Error messages:
 > Connect: can't connect named futex name = jack_sem.system err = No such file or directory
Cannot read socket fd = 13 err = No such file or directory
CheckRes error
JackSocketClientChannel read fail
Cannot open New session.anja client
JackShmReadWritePtr1::~JackShmReadWritePtr1 - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

Jack version:

 > jackdmp 1.9.11
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
no message buffer overruns
no message buffer overruns
no message buffer overruns
jackdmp version 1.9.11 tmpdir /dev/shm protocol 8

**Comment by falkTX** [comment]
That `jack_sem.system` is suspicious.
Are you using the kxstudio repositories?
I know this is "broken" in there at the moment.

**Comment by milasudril** [comment]
It is 1.9.11~20161209-1~xenial5, which I believe is the kx package. Xenial is at 1.9.10.

**Comment by falkTX** [comment]
Then this is something only related to kxstudio. Normal jack2 builds don't have this issue.
I was testing some optimizations and left it there for now.
I'll try to update the jack2 package to fix this, on the weekend.
