### ISSUE TITLE
Please provide POSIX fallbacks for all OS-specific implementations

### ISSUE THREAD

**Issue by yurivict** [jackaudio/jack2#283]
Currently, for example, JackSynchro doesn't have a POSIX implementation. On Linux it is substituted with JackLinuxFutex.

As a result, Jack2 only supports a few systems. Please make sure that it builds on POSIX systems without OS-specific functions. Jack1 works on the FreeBSD, and Jack2 doesn't due to these problems.

In other words, it should build with only "../posix/" includes.

**Comment by falkTX** [comment]
But there is a posix implementation of it already, using semaphores. (sem_init/post/timedwait, etc)
It was changed by me to a futex to work around limitations with semaphores, and also for optimization with internal clients (not enabled by default).

See https://github.com/jackaudio/jack2/blob/master/posix/JackPosixSemaphore.cpp
Probably the wscript just needs an extra rule for freebsd

**Comment by yurivict** [comment]
It doesn't build when I remove "../linux" from the config file. Could you please make sure it builds without "../linux" then?

The error is:
```
/usr/ports/audio/jack2/work/jack2-1.9.11-RC1/common/JackPlatformPlug.h:23:10: fatal error: 'JackPlatformPlug_os.h' file not found
#include "JackPlatformPlug_os.h"
         ^~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by yurivict** [comment]
@falkTX Are you able to remove '../linux' and build on linux?

**Comment by yurivict** [comment]
This is a show-stopper on FreeBSD.

It should build without the "linux" directory. When I tried to build it the POSIX-only build failed.
