### ISSUE TITLE
Compiling dbus for 288df20 fails

### ISSUE THREAD

**Issue by R-a-l-f** [jackaudio/jack2#288]
Hi,

I only install and use jackd, but I'm used to build jackd and jackdbus, just to delete the jackdbus package :D.

When trying to build jackdbus 1.9.10.r283.g288df203 x86_64 on Arch Linux I got

`[  6/279] Compiling dbus/controller_iface_control.c
In file included from ../dbus/controller_internal.h:26:0,
                 from ../dbus/controller_iface_control.c:32:
/usr/src/jack2/jack2-rocketmouse/src/jack2/common/jack/control.h:270:5: error: unknown type name ‘jackctl_server’; did you mean ‘jackctl_server_t’?
     jackctl_server * server_ptr,
     ^~~~~~~~~~~~~~
     jackctl_server_t

Waf: Leaving directory `/usr/src/jack2/jack2-rocketmouse/src/jack2/build'
Build failed
 -> task in 'jackdbus' failed (exit status 1): 
	{task 139776331430864: c controller_iface_control.c -> controller_iface_control.c.17.o}
['/usr/bin/gcc', '-march=x86-64', '-mtune=generic', '-O2', '-pipe', '-fstack-protector', '--param=ssp-buffer-size=4', '-Wall', '-D_FORTIFY_SOURCE=2', '-I/usr/src/jack2/jack2-rocketmouse/src/jack2/build/linux', '-I/usr/src/jack2/jack2-rocketmouse/src/jack2/linux', '-I/usr/src/jack2/jack2-rocketmouse/src/jack2/build/posix', '-I/usr/src/jack2/jack2-rocketmouse/src/jack2/posix', '-I/usr/src/jack2/jack2-rocketmouse/src/jack2/build/dbus', '-I/usr/src/jack2/jack2-rocketmouse/src/jack2/dbus', '-I/usr/src/jack2/jack2-rocketmouse/src/jack2/build', '-I/usr/src/jack2/jack2-rocketmouse/src/jack2', '-I/usr/src/jack2/jack2-rocketmouse/src/jack2/build/common', '-I/usr/src/jack2/jack2-rocketmouse/src/jack2/common', '-I/usr/src/jack2/jack2-rocketmouse/src/jack2/build/common/jack', '-I/usr/src/jack2/jack2-rocketmouse/src/jack2/common/jack', '-I/usr/include/opus', '-I/usr/include/dbus-1.0', '-I/usr/lib/dbus-1.0/include', '-DHAVE_DOXYGEN=1', '-DHAVE_ALSA=1', '-DHAVE_FIREWIRE=1', '-DHAVE_FREEBOB=0', '-DHAVE_IIO=0', '-DHAVE_PORTAUDIO=0', '-DHAVE_WINMME=0', '-DHAVE_CELT_API_0_11=1', '-DHAVE_CELT_API_0_8=0', '-DHAVE_CELT_API_0_7=0', '-DHAVE_CELT_API_0_5=0', '-DHAVE_CELT=1', '-DHAVE_OPUS_OPUS_CUSTOM_H=1', '-DHAVE_OPUS=1', '-DHAVE_SAMPLERATE=1', '-DHAVE_SNDFILE=1', '-DHAVE_READLINE=1', '-DHAVE_PPOLL=1', '-DHAVE_EXECINFO_H=1', '-DHAVE_UCONTEXT_GREGS=1', '-DHAVE_UCONTEXT=1', '-DHAVE_NGREG=1', '-DUSE_CLASSIC_AUTOLAUNCH=1', '-DCLIENT_NUM=64', '-DPORT_NUM_FOR_CLIENT=768', '-DADDON_DIR="/usr/lib/jack"', '-DJACK_LOCATION="/usr/bin"', '-DUSE_POSIX_SHM=1', '-DJACKMP=1', '-DJACK_DBUS=1', '-DHAVE_CONFIG_H', '-DSERVER_SIDE', '-DHAVE_CELT=1', '-DHAVE_OPUS=1', '-DHAVE_DBUS_1=1', '-DHAVE_EXPAT=1', '../dbus/controller_iface_control.c', '-c', '-o', '/usr/src/jack2/jack2-rocketmouse/src/jack2/build/dbus/controller_iface_control.c.17.o']
==> ERROR: A failure occurred in build().
    Aborting...`

Building "classic" without "dbus" worked without issues.

Regards,
Ralf

**Comment by slyrus** [comment]
Same here.

**Comment by falkTX** [comment]
Forgot to test this, a small typo made it to the git repo.
Now fixed.
