### ISSUE TITLE
Can't launch jack2 because of undefined symbol error

### ISSUE THREAD

**Issue by krafczyk** [jackaudio/jack2#290]
I compiled and installed the latest jack using the git arch package https://aur.archlinux.org/packages/jack2-git

When I attempt to launch jack with cadence, I get the following error message:
`ERROR: Can't load "/usr/lib/jack/jack_alsa.so": /usr/lib/jack/jack_alsa.so: undefined symbol: _ZN4Jack15JackAudioDriverC2EPKcS2_PNS_16JackLockedEngineEPNS_14JackLinuxFutexE`

demangling, this is: `Jack::JackAudioDriver::JackAudioDriver(char const*, char const*, Jack::JackLockedEngine*, Jack::JackLinuxFutex*)`

Any ideas why this is happening?

**Comment by falkTX** [comment]
some leftovers from previous install?

**Comment by krafczyk** [comment]
I don't think so.. arch removed the old jack install before installing the new. In addition all the jack libraries I've looked at have appropriate time stamps.

**Comment by krafczyk** [comment]
I did a git bisect and this problem first starts at commit 112b6bdf.

**Comment by falkTX** [comment]
There's nothing special about that class compared to the other ones.
Others have been using the code without issues so far, so I believe it's something with your setup.

So, please provide as much info as you can.
Compiler, flags, etc etc

**Comment by krafczyk** [comment]
So I've been able to reproduce the same error on another computer, same operating system.

I run Arch. 
```
uname -a
Linux schumann 4.12.3-1-ARCH #1 SMP PREEMPT Sat Jul 22 15:32:02 UTC 2017 x86_64 GNU/Linux
```

compiler: 

```
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/7.1.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc-multilib/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp
Thread model: posix
gcc version 7.1.1 20170630 (GCC)
```

Details of configure and install is in this git repo: https://aur.archlinux.org/packages/jack2-git
Basically it's like this for dbus version:
```
python2 waf configure --prefix=/usr --clients=128 --ports-per-application=1536 --alsa  --firewire --dbus --autostart=dbus
python2 waf build $MAKEFLAGS
python2 waf install --destdir="$pkgdir"
```

`$MAKEFLAGS` consists of just -j I believe.

**Comment by krafczyk** [comment]
@falkTX: It turns out, you were right.

Apparently, the old version of jack server was still being called through dbus even though I had already deleted it from my disk. There must be some sort of caching going on through dbus.

My clue was that I was adding `jack_info` statements as well as changing existing `jack_info` statements and these changes were not making an appearance when I tried to restart jack.

Restarting my computer allowed the master version to run correctly.

That said, do you know whether I have to reboot my machine every time I re-compile or change the server a little bit? Is there a procedure I can do to 'purge' the old jack server from memory?

**Comment by krafczyk** [comment]
I've solved this issue as well.

For anybody who encounters this problem, after you install a new version of jack, if you're using cadence (and perhaps other systems I'm not sure), Pressing the 'Stop' button doesn't deactivate the original dbus controller. Running `jack_control exit` in a separate terminal actually de-activates it. This will actually remove any old code from dbus. you can then run the new version properly.

It's possible that this is an issue with cadence, but I'm not knowledgeable enough yet to know. I may submit a patch to cadence if I figure out the problem.

**Comment by krafczyk** [comment]
Okay, it turns out that the 'Force Restart' button is enough to restart the dbus controller. So cadence is okay.

For anybody needing this Issue, The proper procedure with cadence is:

'Stop' any currently running jack instance
'Force Restart' To reload the dbus controller.
