### ISSUE TITLE
netjack2 (1.9.10) can no longer talk to older clients

### ISSUE THREAD

**Issue by bquandt** [jackaudio/jack2#30]
Looks like 1.9.10 netjack2 can't talk to older clients, ie 1.9.8 or 1.9.9 tested against.

Does not matter which one is running netmaster, ie tested both senarios, netmaster running on 1.9.10, or running on 1.9.9

here's my uname -a
`Linux ipod7 3.2.23 #2 SMP Thu Nov 1 16:58:25 PDT 2012 x86_64 GNU/Linux`

I've also tested this against OSX Mountain Lion and Snow Leopard.  Similar problems (albeit I think there are more issues under OSX regarding mulitcasting to sort through as well).

And thanks to Robin Gareus, and Roman Mamedov, tested against armhf Debian, ie
`Linux debian 3.4.29-20130407.1341-rm1+ #34 Sun Apr 7 19:56:56 YEKT 2013 armv7l GNU/Linux`.  Behavior is identical to debian to debian amd64 testing as stated above.

**Comment by requeijaum** [comment]
Was this fixed?

**Comment by 7890** [comment]
It was an issue with the binary "packed" format IIUC. There is probably more info in the mailing list archive if you want to dig deeper. If you feel this is still an issue, please update to 1.9.12 and report back your findings. Thank you for caring about JACK!
