### ISSUE TITLE
character ' ' should have been escaped

### ISSUE THREAD

**Issue by biopsin** [jackaudio/jack2#306]
Hi,
Installed jack-1.9.10 / dbus-1.12.0 / python-dbus-1.2.4
unshure what to do?

>  ~ $ jack_control start
> Traceback (most recent call last):
>   File "/usr/bin/jack_control", line 399, in <module>
>     main()
>   File "/usr/bin/jack_control", line 158, in main
>     bus = dbus.SessionBus()
>   File "/usr/lib/python2.7/site-packages/dbus/_dbus.py", line 211, in __new__
>     mainloop=mainloop)
>   File "/usr/lib/python2.7/site-packages/dbus/_dbus.py", line 100, in __new__
>     bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
>   File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 122, in __new__
>     bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
> dbus.exceptions.DBusException: org.freedesktop.DBus.Error.BadAddress: In D-Bus address, character '
> ' should have been escaped

**Comment by falkTX** [comment]
v1.9.10 is quite old now, are distro is this?
can you update it?

**Comment by biopsin** [comment]
https://www.voidlinux.eu/ - can't update unless official release, but I can package the prerelease for my selv and test. This error started not long ago after updating dbus I assume.
