### ISSUE TITLE
Distorted sound with Pure Data

### ISSUE THREAD

**Issue by ws260621690** [jackaudio/jack2#313]
Hi, 
When I try to route audio via jack from Pure Data (v. 0.48), the sound gets heavily distorted. I am currently using OSX High Sierra on a new MacBook Pro with the newest version of JackOSX (v. 0.92).

**Comment by 7890** [comment]
Hi, unfortunately the JackOSX package is static at this time. If it's not an issue of Pure Data, there is currently nothing we can do.
