### ISSUE TITLE
next release after 1.9.11-RC1

### ISSUE THREAD

**Issue by dvzrv** [jackaudio/jack2#314]
@falkTX: Will the next release available from here be 1.9.12 or 1.9.11 after 1.9.11-RC1?
Judging from the commits, it will be 1.9.12, but I just want to have it confirmed, as I have been building jack2 for Arch in version 1.9.11_RC1 recently and stupid me did not think of the underscore in the package version (doesn't update very well to 1.9.11).
Having 1.9.12 as next release tarball will save me some trouble! :)

**Comment by falkTX** [comment]
Next release will be 1.9.12 correct.
Just need to find some spare time and do it.

**Comment by falkTX** [comment]
1.9.12 is now tagged and released.
