### ISSUE TITLE
Manipulating connection on host from remote machine in the network

### ISSUE THREAD

**Issue by matansag** [jackaudio/jack2#315]
Is there any way one machine can control the jack connections ( connect, disconnect, get info ) of other machine in the same network ?
for example , Machine B  manipulate Machine A connections
Thanks

**Comment by dvzrv** [comment]
You could use ssh for that?

**Comment by matansag** [comment]
hi @dvzrv  
let me explain what i'm trying to achieve

i have server that run python and i wish that the server, using python JACK-Client (or other library) will be able to modify connection ( mainly disconnect and connect ) on other PCs running jack

because i think jack have network capabilities, i'm trying to avoid ssh

**Comment by 7890** [comment]
The infrastructure to connect / disconnect is available. JACK itself doesn't provide a network service for handling connections. It's left to the user if ssh or a JACK client taking remote command works best for achieving remote connection handling.
