### ISSUE TITLE
add firewire driver settings to man page of jackd

### ISSUE THREAD

**Issue by dvzrv** [jackaudio/jack2#321]
When starting jack2 with the firewire driver (libffado 2.3.0 or 2.4.0) and a provided device name

`/usr/bin/jackd -R -p 512 -d firewire -d /dev/fw1 -n 3 -p 64 -r 44100
`

jack2 fails with `firewire ERR: FFADO: Error creating virtual device` :

```
Started JACK Audio.
no message buffer overruns
no message buffer overruns
no message buffer overruns
jackdmp 1.9.12
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2017 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
1515099869811969:  (ffado.cpp)[  92] ffado_streaming_init: libffado 2.3.0-Unversioned directory built Nov 20 2017 07:37:40
firewire ERR: FFADO: Error creating virtual device
Cannot attach audio driver
JackServer::Open failed with -1
no message buffer overruns
Failed to open server
```
When using the firewire driver without device name

`/usr/bin/jackd -R -p 512 -d firewire -n 3 -p 64 -r 44100
`

jack2 works as intended:

```
no message buffer overruns
no message buffer overruns
no message buffer overruns
jackdmp 1.9.12
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2017 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
1515100065965061:  (ffado.cpp)[  92] ffado_streaming_init: libffado 2.3.0-Unversioned directory built Nov 20 2017 07:37:40

```

I know that this works with 1.9.10. Has something changed, that I'm not aware of? Is this intended?
What happens in the case, where there are multiple firewire audio interfaces present?

**Comment by dvzrv** [comment]
According to the more verbose output

```
no message buffer overruns
no message buffer overruns
no message buffer overruns
jackdmp 1.9.12
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2017 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
1515105060199991:  (ffado.cpp)[  92] ffado_streaming_init: libffado 2.3.0-Unversioned directory built Nov 20 2017 07:37:40
1515105060200010: Debug (Element.cpp)[ 129] setVerboseLevel: Setting verbose level to 6...
1515105060200017: Debug (StreamProcessorManager.cpp)[1668] setVerboseLevel: Setting verbose level to 6...
1515105060200019: Debug (devicemanager.cpp)[1253] setVerboseLevel: Setting verbose level to 6...
1515105060200023: Debug (ffado.cpp)[ 119] ffado_streaming_init: Starting with realtime scheduling, base priority 15
1515105060200026: Debug (DeviceStringParser.cpp)[ 283] isValidString: isvalid? /dev/fw1
1515105060200030: Error (devicemanager.cpp)[ 234] addSpecString: Invalid spec string: /dev/fw1
1515105060200033: Fatal (ffado.cpp)[ 128] ffado_streaming_init: Could not add spec string /dev/fw1 to device manager
firewire ERR: FFADO: Error creating virtual device
Cannot attach audio driver
JackServer::Open failed with -1
no message buffer overruns
Failed to open server

```

`DeviceStringParser.cpp` seems to be the culprit here.

**Comment by dvzrv** [comment]
Okay. This seems to be more of a documentational issue.
I shouldn't have used the device node as device name, as [Jonathan Woithe explains in his mail on the ffado-devel mailing list](https://sourceforge.net/p/ffado/mailman/message/36179886/).

However, none of these settings can be found in `man 1 jackd`, only in `jackd -d firewire --help` (and also only mentioned in passing in the latter).

It appears, that the format is:

>  hw:x,y,z
> 
>   x is the bus (called a port in libraw1394)
>   y is the device node id
>   z is a direction flag (unnecessary in nearly every situation)

or:

>   -d guid:<device's GUID>
> 
> The GUID is that which is reported by "ffado-test ListDevices".

I'm unsure yet, as to how `x` (defaults to `0`) can be found, but it in any case, it clears up this issue.
However, the firewire documentation should be added to the man page, which is why I'm renaming this issue accordingly.

**Comment by 7890** [comment]
@dvzrv  just in case, there is a pull-request waiting to add firewire help to the manpage: #300 

ffado-test ListDevices shows both the GUID and node numbers.

Normally if you have one adapter and one interface, two devices show up under /dev/fw*, one of which is the adapter (normally only accessible for root) and the other is the interface with permissions allowing the user to read/write. 
```
$ l /dev/fw*
crw------- 1 root root  251, 0 Dec 29 18:00 /dev/fw0
crw-rw---- 1 root audio 251, 1 Dec 29 18:00 /dev/fw1

$ sudo ffado-test ListDevices
-----------------------------------------------
FFADO test and diagnostic utility
Part of the FFADO project -- www.ffado.org
Version: 2.4.9999-2723M
(C) 2008, Daniel Wagner, Pieter Palmers
This program comes with ABSOLUTELY NO WARRANTY.
-----------------------------------------------

=== 1394 PORT 0 ===
  Node id  GUID                  VendorId     ModelId   Vendor - Model
   0       0xff2584e39b078a2e  0x00FF2584  0x00000000   Linux Firewire - 
   1       0x0040ab0000c3585f  0x000040AB  0x00010049   EDIROL - EDIROL FA-66

```
The x defaults to 0 (1394 PORT 0) -dhw:0 (default) takes the first usable node from that port which in above configuration would be node 1. If you have only one adapter and interface installed leaving out the -d option often "just works" if /dev/fw* permissions are good (user in audio group etc.). I'd recommend to find out the GUID out once, then put that to a small script. If jackd starts up you can be 100% sure that it uses the intended interface.

Related: it could be handy to integrate the ffado-test ListDevices function to the firewire backend, something like jackd -dfirewire --list-devices.

**Comment by dvzrv** [comment]
@7890 Thanks!

I'm now using the GUID for my device.
Certainly looking forward to your pull request being merged!

Something in the vein of `jackd -dfirewire --list-devices` would certainly be very useful, but according to Jonathan Woithe the output of all the ffado tools can not be relied upon (then again, I'm now using ffado-test in my SuperCollider setup script).

Will close this, once #300 is merged.

**Comment by 7890** [comment]
request for close

**Comment by falkTX** [comment]
right, we can close this now. thanks.
