### ISSUE TITLE
jack2-1.9.12 first buffer having no valid input. 

### ISSUE THREAD

**Issue by benravin** [jackaudio/jack2#323]
I'm using the latest JACK version1.9.12. I compiled on Linux Ubuntu PC and used to capture audio and analyze.

When I used simple_client.c application by modifying to read input from line in and do some audio analyses, what  I notices is the first buffer from Jack call back function is 
all zeros. 
Why is the first buffer not having valid audio samples ?

**Comment by falkTX** [comment]
this is expected when using jack2 with async (the default).
one audio cycle is used as safety against bad clients, among other reasons.

**Comment by benravin** [comment]
How to use jack2 with sync option enabled ?  pls provide an example.

**Comment by falkTX** [comment]
start jack with the -S option, or enable it in whatever gui tool you use.

**Comment by benravin** [comment]
I'm not using any gui. Infact I modify the simple_client example app and using it. Which API i need to use for enabling sync ?

**Comment by falkTX** [comment]
no API, it's a jack server option.
see `man jackd`

**Comment by benravin** [comment]
As mentioned earlier I use the simple client example C application and build it. Then execute the simple_client application in command line. I can see it starts the jack server with some default values. How these default values are set. How to modify it ?

In example app the API called are as follows,

jack_options_t options = JackNullOption;
client = jack_client_open (client_name, options, &status, server_name);

**Comment by falkTX** [comment]
Default values are read from ~/.jackdrc file, or jackdbus if set that as default autostart option when building jack2.

**Comment by benravin** [comment]
How to modify the default settings in .jackdrc file ? Can I use GUI Qjackctl to change the settings such as sample rate buffers/period etc and save it. Will it change the .jackdrc ?

**Comment by falkTX** [comment]
You just modify the file..?
And yes to saving question.

Also... this is something you can pretty much find by yourself if you actually *try* ;)
