### ISSUE TITLE
alsa_in destroys my speakers if jack is started with a buffer size of 4096

### ISSUE THREAD

**Issue by shimpe** [jackaudio/jack2#324]
[fubar_session.wav.gz](https://github.com/jackaudio/jack2/files/1633193/fubar_session.wav.gz)

I have a USB mic. It works perfectly with ALSA, and it works like a charm using jack with alsa_in, except if jack is started with a buffer size of 4096, then it records stuff like what is attached (if I happen to speak while recording, one can also hear the speech being mingled with the noise) **(warning, better to look at it in a wav file editor than to actually play it).**

This the line I use to start alsa_in:

alsa_in -d hw:AT2020USB -j mic:AT2020USB -r 44100

I'm currently on arch linux, kernel 4.14.13-1-ARCH #1 SMP PREEMPT Wed Jan 10 11:14:50 UTC 2018 x86_64 GNU/Linux )

**Comment by synthnassizer** [comment]
Hi keep the buffer size equal in jack server and alsa_in.
To force this to be the case, start jack with specific sample rate, period
and buffers.

I start jack with

jackd -dalsa -dhw:DSP24,0 -r${SAMPLING_RATE} -p${PERIOD} -n${BUFFERS}
sleep 2
alsa_in -d hw:DMX6Fire -r${SAMPLING_RATE} -p${PERIOD} -n${BUFFERS}


I hope this will help you.
