### ISSUE TITLE
ERROR: Invalid container address 'driver':'softmode':'(null)' supplied to method 'SetParameterValue'

### ISSUE THREAD

**Issue by guitarxuser** [jackaudio/jack2#327]
The build and installation of the jack 1.9.12 version of jack2 on a ubuntu 16.04 with an installed 1.9.11 version leads to an error ERROR: Invalid container. To roll back this installation, you must remove the jack binaries from the dir's /usr/local/bin and /usr/local/lib, otherwise you don't get the original version running

**Comment by falkTX** [comment]
this is pretty normal..
installing a software with shared libraries, you get to these kind of conflicts if the new binary uses old libraries, and vice-versa.
either build the new software the same way it was built before, or remove the old version first and then install the new.

**Comment by guitarxuser** [comment]
Thx, falkTX, but I've seen a lot of requests with this error, but nobody says what to do it this case, therefor I opened this issue. Cheers

**Comment by falkTX** [comment]
You can't really do anything though.
If you want to replace your distro's JACK version, on debian/ubuntu, the setup is quite complicated that 99% of users will not do it correctly.
There is specific build flags on the packages in order to make them multi-arch friendly.
Install prefix is /usr, but libdir is not /usr/lib or /usr/local/lib, but a custom location that depends on the native architecture.

Quoting what I wrong on another place.

> Well, on Debian jack libs will be installed on /usr/lib/<arch>/.
> When you build JACK from source, without passing some specific configure flags, it will install its jack libs to /usr/local/lib/.
> With this you end up with 2 different JACK versions installed on your system, which is really asking for trouble.
> 
> Your qjackctl might be setup to launch /usr/bin/jackd (which is the Debian’s JACK), but then it will use JACK libs from /usr/local/lib/ since jackd has no rpath linker settings. (/usr/local/lib takes preference over /usr/lib/).
> The core of JACK has changed since 1.9.10, now uses futexes for sync instead of posix semaphores for example.
> So on this case the jackd and libjackserver.so will conflict with each other, perhaps not even start.
> 
> Without the manual prefix, running jackd will call /usr/local/bin/jackd and get the correct libs from /usr/local/lib/.
> But then an application might somehow use the JACK libs from /usr/lib/ (hardcoded path), which will generate conflicts too.
> 
> You might think that building JACK with --prefix=/usr is enough, but remember Debian has multiarch, so prefix=/usr will still generate conflicts (/usr/lib/libjack.so vs /usr/lib/x64_64-linux-gnu/libjack.so)
> The actual configuration command for Debian is ./waf --prefix=/usr --classic --libdir=/usr/lib/x64_64-linux-gnu --alsa --dbus --firewire.
> KXStudio builds add --clients=256 --ports-per-application=2048 --autostart=dbus.
> 
> Even if you manage to build it correctly, you now broke 32bit clients on a 64bit system, as you have to build that taken into consideration Debian’s multiarch setup.
> You’ll have to build with “-m32” in CFLAGS, CXXFLAGS and LDFLAGS, custom libdir, and then do a manual selective install of the jack libs in order to get 32bit clients working on a 64bit Debian system.

**Comment by guitarxuser** [comment]
...understood, playing around with could lead to such like strange behavior, but you explanation shows the cause of that and possible solution
