### ISSUE TITLE
 jack_control: File "/usr/bin/jack_control"  print 'shit'

### ISSUE THREAD

**Issue by rampartisan** [jackaudio/jack2#328]

**Comment by rampartisan** [comment]
Hey everyone,

Trying to run jack_control on my raspberry pi 3, which is running an OS built by buildroot. I end up with this lovely error!

jack_control: File "/usr/bin/jack_control", Line 80
print 'shit'
Syntax Error: Missing paraenthesis in call to 'print'. Did you mean to print(int 'shit')

Apart from being hilarious, does anyone have any debugging steps I can take?

**Comment by falkTX** [comment]
try using `python3 /usr/bin/jack_control`

**Comment by rampartisan** [comment]
@falkTX I still receive the same error unfortunately

**Comment by dvzrv** [comment]
AFAIK jack_control is not python3 ready (see #308) and needs to be run with python2 (legacy).

**Comment by falkTX** [comment]
sorry, I meant python2 there.

**Comment by rampartisan** [comment]
Ok, I will give it a go with python2. Unfortunately pyhthon2 is not built into buildroot so I will have to add it myself.

Is there any command line alternative to jack_control? At the moment I am simply trying to start jack in order to receive MIDI

**Comment by falkTX** [comment]
jackd? jack_control is for dbus control, usually you use jackd if starting jack from CLI.

**Comment by rampartisan** [comment]
I have swapped to using jackd. However the fact that jack_control would not work on my buildroot system was annoying me so I used the python 2to3 to create a patch that I will be submitting to them.
