### ISSUE TITLE
Undocumented crash when using libjack and libjackserver

### ISSUE THREAD

**Issue by chris-kuhr** [jackaudio/jack2#331]
Hi *,

I am dokumenting this behavior here, since it is known but undocumented.

I observed some strange behavior of libjack and libjackserver.

If I have a multiprocessing application with one jack server fork and one jack client fork, jack_client_open crashs.

Here the backtrace:
#0  __strcmp_ssse3 () at ../sysdeps/x86_64/multiarch/../strcmp.S:174
#1  0x00007f83dddb803f in jack_find_driver_descriptor(_JSList*, char const*) () from /usr/local/lib/libjackserver.so.0
#2  0x00007f83dddb9ef8 in Jack::JackServerGlobals::Init() () from /usr/local/lib/libjackserver.so.0
#3  0x00007f83dddb64f8 in jack_client_open_aux(char const*, JackOptions, JackStatus*, __va_list_tag*) () from /usr/local/lib/libjackserver.so.0
#4  0x00007f83dddb67b1 in jack_client_open () from /usr/local/lib/libjackserver.so.0
#5  0x0000000000414f04 in talker_Process (arguments=0x63f680 <arguments>) at ../src/net/avb/talker/talker_process.c:395
#6  0x000000000042d487 in avbruntime (arguments=0x63f680 <arguments>) at ../src/avbruntime.c:644
#7  0x000000000042e888 in main (argc=11, argv=0x7ffebee6f678) at ../src/main.c:144

The interesting thing is, jack_client_open keeps crashing if I remove all the jack server code.

It was neccessary to remove the -ljackserver linker option as well, because the client code linked against libjackserver.so instead of libjack.so.

If the order of linker option is changed, first link libjack and afterwards libjackserver, it works.

For anyone having the same issue.

BR,
Ck

**Comment by 7890** [comment]
Archiving this hint
