### ISSUE TITLE
Invert sound

### ISSUE THREAD

**Issue by gamersalpha** [jackaudio/jack2#346]
Hello there, 
so i bought a broken headset with inversed stereo, 
can u explain me please how invert the left and right sound with jack2 please

![image](https://user-images.githubusercontent.com/32466950/39439022-7580c1f2-4ca6-11e8-859e-e2f36788de1c.png)

**Comment by nik-gnomic** [comment]
![q00avucl](https://user-images.githubusercontent.com/37479089/40691766-b5c92e8c-63a5-11e8-9537-0472e52f5f8d.png)

**Comment by falkTX** [comment]
Yeah, it is as simple as that. Just connect in1 to out2, and in2 to out1, crossing the connections.
