### ISSUE TITLE
Jack 2 + Windows incompatibility in stdint.h header with systemdeps.h

### ISSUE THREAD

**Issue by WhatFor** [jackaudio/jack2#353]
Hi,

I've found that the `systemdeps.h` in `/common/jack` includes the line:

`#if (!defined(int8_t) && !defined(_STDINT_H))` (line 71).

However this caused typedef conflicts on int16, int32 and uint32 types in `stdint.h` (MS default).

The MS file contains the define `_STDINT` (no `_H`), which is a mismatch against the `!defined()` in `systemdeps.h`

I'm far from understanding the reasons of this, and didn't want to suggest a PR as I'm not sure of the effects of making the change, but changing the name in `systemdeps.h` fixed the conflicts for me.

Thanks for the great package and work. 😊🚀

**Comment by davidebeatrici** [comment]
@clvn's solution: clvn/jack2@e7b06bf685676db25c11e07367fc9c5043a10a68.

Another possible solution, tested with MSVC 14.23.28105 (2019):
```c
typedef INT8 int8_t;
typedef UINT8 uint8_t;
typedef INT16 int16_t;
typedef UINT16 uint16_t;
typedef INT32 int32_t;
typedef UINT32 uint32_t;
typedef INT64 int64_t;
typedef UINT64 uint64_t;
```
