### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by 7890** [jackaudio/jack2#359]
I get this error:
```
...
[102/253] Compiling linux/alsa/alsa_seqmidi.c
../linux/alsa/alsa_driver.c: In function ‘alsa_driver_configure_stream’:
../linux/alsa/alsa_driver.c:599:3: warning: implicit declaration of function ‘snd_pcm_sw_params_set_tstamp_type’ [-Wimplicit-function-declaration]
   err = snd_pcm_sw_params_set_tstamp_type(handle, sw_params,
   ^
../linux/alsa/alsa_driver.c:600:8: error: ‘SND_PCM_TSTAMP_TYPE_MONOTONIC’ undeclared (first use in this function)
        SND_PCM_TSTAMP_TYPE_MONOTONIC);
```
I think it relates to the last commit 67e4b4368e73616a6e0aa020925ead75cd57221e

**Comment by falkTX** [comment]
leaving a note for myself later to see https://github.com/jackaudio/jack1/commit/aa7e30bd74d7830abe0a649df4f2c6185541a32d

**Comment by 7890** [comment]
It was a too old libasound2-dev package (on Ubuntu).
Maybe some #ifdef foo could handle versions to retain legacy compat.

**Comment by 7890** [comment]
A follow-up note, on another system "unpatching" this commit worked doing this in the jack2 folder:
```
wget https://github.com/jackaudio/jack2/commit/67e4b4368e73616a6e0aa020925ead75cd57221e.patch
interdiff 67e4b4368e73616a6e0aa020925ead75cd57221e.patch /dev/null > 67e4b4368e73616a6e0aa020925ead75cd57221e.patch.reversed.patch
patch -p1 < 67e4b4368e73616a6e0aa020925ead75cd57221e.patch.reversed.patch
```
I'm sure there is a simpler way but this worked so it might be useful for "legacy" people.

**Comment by falkTX** [comment]
yeah, I am aware of this.
but I want to do this part carefully.
jack1 added code very similar to this, only without that specific new definition.

I will handle this sometime this month.

**Comment by 7890** [comment]
FYI jack1 compiles on the same system without issues.

**Comment by falkTX** [comment]
Now fixed in latest git master
