### ISSUE TITLE
Build Fails RPi 3

### ISSUE THREAD

**Issue by drewhoener** [jackaudio/jack2#374]
Trying to build on Raspberry Pi 3 with ALSA, no DBus
Build fails at different places each time

`Build failed
 -> task in 'alsa' failed (exit status 1):
        {task 1985782736: c alsa_driver.c -> alsa_driver.c.8.o}
['/usr/bin/gcc', '-Wall', '-fPIC', '-I/home/pi/jack2/build', '-I/home/pi/jack2', '-I/home/pi/jack2/build/common', '-I/home/pi/jack2/common', '-I/home/pi/jack2/build/common/jack', '-I/home/pi/jack2/common/jack', '-I/home/pi/jack2/build/linux', '-I/home/pi/jack2/linux', '-I/home/pi/jack2/build/posix', '-I/home/pi/jack2/posix', '-I/usr/include/alsa', '-DHAVE_DOXYGEN=0', '-DHAVE_ALSA=1', '-DHAVE_FIREWIRE=0', '-DHAVE_FREEBOB=0', '-DHAVE_IIO=0', '-DHAVE_PORTAUDIO=0', '-DHAVE_WINMME=0', '-DHAVE_CELT_API_0_11=0', '-DHAVE_CELT_API_0_8=0', '-DHAVE_CELT_API_0_7=0', '-DHAVE_CELT_API_0_5=0', '-DHAVE_CELT=0', '-DHAVE_OPUS=0', '-DHAVE_SAMPLERATE=0', '-DHAVE_SNDFILE=1', '-DHAVE_READLINE=0', '-DHAVE_SYSTEMD=0', '-DHAVE_PPOLL=1', '-DHAVE_EXECINFO_H=1', '-DHAVE_NGREG=1', '-DUSE_CLASSIC_AUTOLAUNCH=1', '-DCLIENT_NUM=64', '-DPORT_NUM_FOR_CLIENT=768', '-DADDON_DIR="/usr/local/lib/jack"', '-DJACK_LOCATION="/usr/local/bin"', '-DUSE_POSIX_SHM=1', '-DJACKMP=1', '-DHAVE_CONFIG_H', '-DSERVER_SIDE', '-DHAVE_ALSA=1', '../linux/alsa/alsa_driver.c', '-c', '-o', '/home/pi/jack2/build/linux/alsa/alsa_driver.c.8.o']
`

**Comment by falkTX** [comment]
Please attack full build log, and build with "./waf -j 1".

**Comment by drewhoener** [comment]
stdout and stderr build log with -j 1
[jack_build.log](https://github.com/jackaudio/jack2/files/2349344/jack_build.log)

**Comment by 7890** [comment]
please see #359

**Comment by falkTX** [comment]
Now fixed in latest git master
