### ISSUE TITLE
jack2 is incompatible with Java Audio on OS X

### ISSUE THREAD

**Issue by eclab** [jackaudio/jack2#378]
After installing jack2, Java Audio applications cannot launch.   

This is made especially bad because jack2 has a broken uninstall script, and so is essentially impossible to uninstall, and as a result for most non-hacker users those applications are permanently borked after installing jack a single time.  This is very bad style.

**Comment by 7890** [comment]
How can this be related?
What's the error message?

**Comment by eclab** [comment]
> How can this be related?

?? I thought it was clear.  After installing jack2 on OS X, I can't run any application which uses Java Audio: it bombs with various internal (non-Java) error messages.   This is exacerbated by the fact that Jack has a broken uninstaller which doesn't uninstall a great many items, so if a user installs Jack, he can't run any Java audio apps any more *and* even if he runs the uninstaller, he *still* can't run any Java audio apps any more: from his perspective, installing Jack has permanently ruined Java audio.

> What's the error message?

I'm sorry to say I can't tell you -- I spent several hours removing Jack2 from my Mac through analysis of the installer (see the other posted issue).  I will not be installing Jack2 again to determine and post the error.  I do recall googling for the error and finding a similar error involving OpenGL, but that is likely coincidence.

**Comment by 7890** [comment]
"Java audio" is ambiguous, without any error text nothing can be done to help you more.
The uninstaller should work though, that's a bug.
