### ISSUE TITLE
Deprecate newly added, but useless MIDI function

### ISSUE THREAD

**Issue by falkTX** [jackaudio/jack2#382]
I dont remember the name of it now, but there is a function related to midi, which is present in jack2 but not in jack1.
We should deprecate it for next release, and eventually remove it.
But backwards compatibility we keep the exported function, but just remove it from the headers.

**Comment by sletz** [comment]
With is `jack_midi_reset_buffer` going to be suppressed ? We use it.

**Comment by falkTX** [comment]
Use it where? It does pretty much the same as the clear function, except for initializing a few more things.
I do not understand why it was added in the first place.
What is the reason for it to exist?

**Comment by sletz** [comment]
As far as a remember : I wanted to use the MIDI buffer as "raw" data, to transport control data for a JACK audio/MIDI network application. Adding this `jack_midi_reset_buffer` was quite helpful, and a minimal addition to the API. 

What is the issue with keeping it in JACK2 ? (and so adding in JACK 1)

**Comment by sletz** [comment]
If you remove it, then our Faust code using JACK will break.. ))-; 
See https://github.com/grame-cncm/faust/search?q=jack_midi_reset_buffer&unscoped_q=jack_midi_reset_buffer

**Comment by sletz** [comment]
Note that this API is part of the latest published JackOSX package also...

**Comment by falkTX** [comment]
being deprecated gives it enough time to change.
and the ABI would always be there for compatibility reasons.
Marking it as deprecated would at least help people to not use it anymore.

anyway, I really think there needs to be a real case for something to be added to the API.
I find the name quite confusing. was there a discussion before adding it?

**Comment by falkTX** [comment]
if it was for internal purposes, you could have just maintained an internal jack patch-set.
this seems like adding something to jack api just for 1 specific and internal use case.
If you have not said something now, I would believe no one else ever needed it.

**Comment by sletz** [comment]
Possibly, nobody ever thought JACK MIDI API could be used this way, to deal with untyped data. We can possibly maintain a patch, but I guess this will be too complex on the long term. 
Again what is the problem in maintaining the API?

**Comment by falkTX** [comment]
Problem is not having consistency of the APIs, between jack1 and jack2.
I had this issue in mind for quite some time, but always forgot to raise it.

Maintaining a patch for this should be no real work at all.
I dont want to remove the exported symbol from the library, as to not break existing applications.
It simply (in due time) should not part of the public jack headers.
For an internal use, you can simply define the function locally, no need to patch JACK I believe.

**Comment by sletz** [comment]
So do you mean I will need to define the `jack_midi_reset_buffer` entry point, and have it to link with the available code in libjack?

**Comment by falkTX** [comment]
yes, should work just as before. nothing breaks. except 1 extra function you have to define yourself (that is part of the libjack symbols but not exposed in the header files).
I think this is a good compromise.

**Comment by sletz** [comment]
OK seems fine, thanks a lot !

**Comment by falkTX** [comment]
great, glad we have an understanding :)
I am closing this issue again then.
