### ISSUE TITLE
deprecate jack session manager for the sake of defragmentation and scope of the project

### ISSUE THREAD

**Issue by diovudau** [jackaudio/jack2#389]
Jack Session can be considered a protocol without users. I'm asking to make that official by deprecating the session api and encourage existing client software to remove it from their feature set.
This will make the scope of Jack more clear: an audio server.  It will also reduce the risk of fragmentation, that new software in the future might think jack session is a good idea and implement it in favour of more established and accepted solutions (see below)

Explanation:

Historically I was one of the most vocal people to include session management in jack itself, seeing it as a push to make session support more widespread because if you already had jack then you got the session manager, no other tool needed. So I thought.

However I now would like to seriously propose to take the session management out of jack again, To not break API/ABI in the form of deprecating it. (Maybe remove it entirely in a new version)

1) I personally don't know anyone or any program that uses jack session, except if there is a parallel NSM implementation. 

2) Around the same time jack session was implemented the Non Session Manager was released. Its proper and strict documentation,  well designed feature set and adoption made it the de-facto standard session manager for pro audio in Linux. Having Jack Session with its prominent name may lead non-insiders to believe it is important to support, wasting resources in the end.

3) Jack is an audio/music server. Removing session management makes that more clear.

**Comment by 7890** [comment]
Hi, did you ask around on LAD, jack mailing lists if eventually anybody is using this feature?

**Comment by 7890** [comment]
For better understanding, do you refer to "-C" file option that jackd takes to setup internal clients and do connections?

**Comment by falkTX** [comment]
The -C option is not session management, just loading an initial sorta project.
It helps the cases where you want things to start as soon as possible.

Anyway, NSM is the obvious winner regarding session management.
Not sure the best way to deprecate JACK session, or if we need to.
Let's leave this issue open for discussion

**Comment by falkTX** [comment]
Forgot about this ticket, but it has been referenced from another one.
There is nothing else to do here, correct? JS is marked deprecated, devs have started to make applications with NSM support instead of JS, and we have a few different frontends to NSM too.

Note that, due to JACK wanting to keep backwards compatibility, the JS API has to remain.
Maybe one day it will be a no-op, in case we have another JACK version or something. (does pipewire implement JS? really do not know..)

I will close this ticket then
