### ISSUE TITLE
[OSX] client name length restriction

### ISSUE THREAD

**Issue by HaHeho** [jackaudio/jack2#392]
I've encountered errors, when trying to instantiate a client with an individual name with an extended name. The example shows the error message when instantiating a client with the name `ThisNameIsJustTooLongTheLimitIsQuiteLow`:
> Allocate: can't check in named semaphore name = js_ThisNameIsJustTooLongTheLimi err = File name too long
> Cannot allocate synchro
> Destroy: can't destroy semaphore name = js_ThisNameIsJustTooLongTheLimi err = Bad file descriptor
> Cannot create new client
> Cannot open ThisNameIsJustTooLongTheLimitIsQuiteLow client

I'm using _"OSX v10.14"_, the binary package _"jackOSX Version 0.92_b3"_ and the _"JACK Python API"_ [https://github.com/spatialaudio/jackclient-python](url). The latter should not matter, but using OSX might be the cause.

The problem seems to be related to acquiring a semaphore for a file related to the desired client name. Looking for a solution I've found a comment on a semaphore name length limitation on OSX of 30. That being related seems to be true, since limiting the client name length to 27 prevents the error (30 minus 3 of the prepended `js_` ... not sure where this prefix comes from, probably the Python API).

I assume that problem is not new to you, but I couldn't find any information on it. Limiting the client name length (to such a low amount) on my side is pretty inconvenient. Does somebody have a better solution or knows how to avoid the limitation?!

**Comment by 7890** [comment]
I can confirm this behavior. The jack_test for travis builds also complain about short client names.
```
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4" is too long to be used as a JACK client name.
Please use 63 characters or less
JackShmReadWritePtr1::~JackShmReadWritePtr1 - Init not done for -1, skipping unlock
!!! ERROR !!! opening a client with maximum possible client name size does not work!
Allocate: can't check in named semaphore name = js_AAAAAAAAAAAAAAAAAAAAAAAAAAAA err = File name too long
Cannot allocate synchro
Destroy: can't destroy semaphore name = js_AAAAAAAAAAAAAAAAAAAAAAAAAAAA err = Bad file descriptor
Cannot create new client
Cannot open AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3 client
```
https://travis-ci.org/jackaudio/jack2/jobs/487912075
If that needs to be fixed, the only way I currently see is to introduce another indirection from (short) semaphore name to the "normal" length max name. There is no quick fix in sight so it might be a good idea to put that information to a reasonable place for now.

**Comment by HaHeho** [comment]
Thank you for finding another reference for the behaviour.

The limitation is inconvenient but of course not a dealbreaker. So if it would be a bigger effort, then a  fix is not essential. BUT the behaviour should be documented of course. What are you referring to when you say a reasonable place?

Also, should the API function for accessing the client name length limitation not report an OS specific value then (as it seems only on MacOS)?
https://github.com/jackaudio/jack2/blob/9fe56af980e4a7279cfe826a2b1f8bf1f799763a/common/JackAPI.cpp#L1475-L1478

**Comment by falkTX** [comment]
`jack_client_name_size` needs to return the correct value for osx.
It is a limitation on how we use it, so becomes a limitation of jack as well.

**Comment by HaHeho** [comment]
> `jack_client_name_size` needs to return the correct value for osx.
> It is a limitation on how we use it, so becomes a limitation of jack as well.

Yes, that's how it seems to me as well. But I cannot tell if this effects more parts of the implementation, so wether the internal CONST value or only the API return value needs to be changed.

**Comment by 7890** [comment]
Can there be an issue if a "long" name JACK want's to connect to OSX "short" name JACK or vice versa? I can see two possible fixes: limit it for OSX only or limit it for all platforms to the lowest known working. I haven't yet a clear idea on what would happen if the limit is lowered for existing applications. Having the same valid lengths on every platform can have some benefits. Not to forget about possible differences in jack1 / jack2 implementations.

**Comment by 7890** [comment]
Side-note, I'm thinking that a lot of things can go to the metadata db. Limitations like for the client name won't be limiting anymore. For instance using it for long human names, translations, aliases, links to fancy icons etc etc.

**Comment by falkTX** [comment]
this is the same issue as #474 which is very likely fixed now.
closing this one, please continue any discussion on the other ticket.
