### ISSUE TITLE
write_midi_event

### ISSUE THREAD

**Issue by icubex** [jackaudio/jack2#394]
Couldn't find any clear example how to use write_midi_event so came up with the following working code (a basic virtual MIDI cable) that you might add to your examples section. Any comments ?

import jack

midiInBuffer = []
midiOutBuffer = []

client = jack.Client('jack')

midi_in = client.midi_inports.register('midi_in)
midi_out = client.midi_outports.register('midi_out')

@client.set_process_callback

def process(frames):

  midi_out.clear_buffer()
  if (len(midiOutBuffer)):
    for msg in midiOutBuffer:
      midi_out.write_midi_event(0, msg)
      print('MIDI sent = ', msg)
  midiOutBuffer.clear()

  for offset, data in midi_in.incoming_midi_events():
    msg = struct.unpack('3B', data)
    midiInBuffer.append(msg)
    print('MIDI rcvd = ', msg)

client.activate()

print(client.midi_inports)
print(client.midi_outports)

#forward all incoming messages from midi_in to midi_out
while True:
  for msg in midiInBuffer
    midiOutBuffer.append(msg)
    print('MIDI fwd = ', msg)
  midiInBuffer.clear()

**Comment by 7890** [comment]
Hi, this doesn't look like a C program (?)
FYI: all the examples contained in the JACK source are small C or C++ programs (see examples-clients/*).

**Comment by icubex** [comment]
True, it's Python.

**Comment by 7890** [comment]
Could it possibly be added to the home of the library doing the Python -> JACK bindings?

**Comment by icubex** [comment]
I presume so .. which repo would you suggest ?

**Comment by 7890** [comment]
Wherever you go it from ..

**Comment by icubex** [comment]
I didn't get it from anywhere .. I now submitted it to https://github.com/spatialaudio/jackclient-python

**Comment by 7890** [comment]
Excellent!
