### ISSUE TITLE
Unable to use JackRouter when started by QjackCtl

### ISSUE THREAD

**Issue by lethevimlet** [jackaudio/jack2#405]
Hi, I downloaded the latest release of Jack2 and tried to use JackRouter with Ableton Live

I noticed something strange, I'm able to select JackRouter under ASIO devices when I start Jack PortAudio shortcut. the problem is that I'm unable to select JackRouter when starting Jack server through QJackCtl start button.

I also notice inconsistent version naming on the download page

![image](https://user-images.githubusercontent.com/2963923/50426629-5de4c800-0893-11e9-9dcc-5eacaf90c7c9.png)

Any idea of why this might be happening?

**Comment by falkTX** [comment]
This issue has been reported several times now.
Stuff changed in MacOS that no longer allows the stuff JACK is doing.

And the Windows installers are old compared to the source, correct.
JACK2 has a new maintainer (me), we are focusing on new features and Linux support for now.
Windows stuff will be handled again at a later point in time.

**Comment by lethevimlet** [comment]
I'm using Windows btw, not Mac, thou I imagine changes made for Mac also affect Windows releases. 

Do you know where can I download old compiled versions of Jack2?

**Comment by lethevimlet** [comment]
I see JackRouter in AbletonLive, the problem is when a select it in the dropdown of devices, It works when I start Jack with Jack PortAudio shortcut but it fails when I start Jack with QJackCtl. 

I tried to mimic the same arguments in QJackCtl than the ones in JackPortAudio shortcut.
`jackd.exe -R -S -d portaudio -d "ASIO::ASIO4ALL v2"` 
as well as messing with all the options with no luck. 

I believe there must be some sort of inconsistency between both setups.

**Comment by alfonso73** [comment]
Hi all, i have no problems (well just only one about SuperCollider server not booting) working with Jack (x64) on Win10 64 bit with the following apps and starting Jack from Jack Control GUI
1. Ableton Live (OK)
2. Pure Data (OK)
3. Carla (OK)

As i said before the only problem is SuperCollider 10.1 (x64) server not booting and giving error.
@lethevimlet wich kind of log do you have when starting Jack from JackControl?
