### ISSUE TITLE
JackOSX memory leak?

### ISSUE THREAD

**Issue by dyfer** [jackaudio/jack2#424]
Hello,
I'm using JackOSX 0.92_b3 on macOS 10.13.6 and 10.14.

Each time I start jack, either from command line or through JackPilot, the memory footprint of `coreaudiod` increases by ~120MB, and then by another ~50MB when closing jack (`coreaudiod` usually takes <10MB of memory). This memory footprint stays that way until `coreaudiod` or the system itself is restarted; at some point I had `coreaudiod` occupy 8GB of memory after multiple starts/stops of jack.

I know that JackOSX is not actively maintained, so I'm not sure what's the way forward. After reading different posts from @sletz I arrived at the [jackosx sourceforge repository](https://sourceforge.net/p/jackosx/code/) hoping to be able to maybe tinker with the source; this however seems to be outdated (looks like version 0.89?), not reflecting the "newest" JackOSX (0.92_b3). I'd appreciate any help on this.

**Comment by 7890** [comment]
@dyfer Thanks for pointing this out, of course memory consumption should be deterministic and mainly depend on the limits set for number of clients, number of ports, backend in use etc. and cleaned up nicely after shutting down JACK.
As you know from posts the JackOSX is static. I invite you to join efforts on this repository. There will be a new OSX release at some point in time. It might be that some of  [jackosx sourceforge repository](https://sourceforge.net/p/jackosx/code/) can be re-used when it's missing in here. Nobody has taken the lead for giving JACK on OSX more attention, it would be somebody using OSX on a regular basis with affinity to audio and software development willing to invest an amount of time for the details.

**Comment by dyfer** [comment]
@7890 thank you for the answer. I'll try to look at the JackOSX source, however, as I pointed out, it seems to be outdated in relation to the binary distribution of JackOSX. 
The link to the source (under the JackOSX link on the [download page](http://jackaudio.org/downloads/)) does not include current sources for JackRouter and other macOS elements of JackOSX. Do you have any leads where (if at all) changes to the jackosx source (between versions 0.89 and 0.92_b3) have been published?

**Comment by 7890** [comment]
Unfortunately not. Indeed the last entry in jackrouter/TJackClient.cpp is 
```
07-11-07 : Version 0.85 : S Letz
```
However in jackrouter2/Source/JackRouterPlugIn.cpp:
```
...
01-03-08 : Version 0.87 : S Letz
...
15-07-11 : Version 0.95 : S Letz
```
It might be that all sources are current but we don't understand the version numbering for releases.
@sletz could possibly tell more.

**Comment by sletz** [comment]
AFAICA this should be the latest code. Not that the JackRouter kind of plugin is considered obsolete by Apple for years. I have a 10 MO zip archive of all the JackOSX related stuff on my disk. Where should I put it?

**Comment by 7890** [comment]
@sletz if there is nothing confidential in it, one way would be to put it to a new empty repository so it's archived for later inspection.

**Comment by sletz** [comment]
Here is the file http://www.filedropper.com/jackosx

**Comment by dyfer** [comment]
Thank you @sletz and @7890 !
Is it OK if I put this on my [mirror/fork of the old jackosx repo](https://github.com/dyfer/jackosx/)?

**Comment by sletz** [comment]
OK.

**Comment by dyfer** [comment]
As this pertains to the currently unmaintained macOS JackRouter, I think it can be closed.
