### ISSUE TITLE
alsarawmidi vs a2jmidid

### ISSUE THREAD

**Issue by miquecg** [jackaudio/jack2#431]
I still don't have a clear understanding of the differences between `alsarawmidi` and `a2jmidid`. I know that both expose ALSA MIDI devices to JACK but I don't see why choosing one over other.

I'm using Cadence for my needs and I have the option of installing `a2jmidid` package. What I don't see is where to pass the flag `alsarawmidi`. There's a similar thing under Alsa driver tab but AFAIK this should be a setting of the engine not the driver.

I'm asking this because I've read that JACK MIDI is better (less jitter) than ALSA MIDI, but I'm not sure on how to use the former.

**Comment by 7890** [comment]
I think it's main differences are about timing jitter/latency (don't take this for granted). a2jmidid will probably replace the other MIDI backends in the future (don't take this for granted). 
This tool can measure how MIDI performs in JACK: https://github.com/x42/jack_midi_latency

**Comment by miquecg** [comment]
There's a discussion about this very same question [here](http://linux-audio.4202.n7.nabble.com/Is-Xalsarawidi-the-same-as-Xraw-or-Xseq-td106370.html).

Apparently both options are compatible. `a2jmidid` is the bridge between ALSA MIDI hardware ports and JACK, while `alsarawmidi` is ¿an alternate driver for ALSA MIDI? [1]

> `jackd` ALSA backend has the `-X` option for telling which MIDI driver to use

I'm using `jack2-dbus` with Cadence. As I've said, I don't how I'd pass this `-X` flag to jack within Cadence, if possible at all.

[1] http://linux-audio.4202.n7.nabble.com/Is-Xalsarawidi-the-same-as-Xraw-or-Xseq-tp106370p106413.html

**Comment by 7890** [comment]
Passing no -X option and using a2jmidid should give acceptable results, but the tool can measure it against other setups. No insights on how to configure Cadence however in qjackctl there is a drop-down in Tab Settings/Parameters 'MIDI Driver'.

**Comment by miquecg** [comment]
I've asked for clarification to Cadence developers [1]. Actually my setup is good enough, I'm not perceiving any noticeable delay in sound for the moment.

By the way, I have a MIDI keyboard connected through USB. Is this also affected by jitter?

[1] https://github.com/falkTX/Cadence/issues/245

**Comment by 7890** [comment]
There will always be jitter and latency, the question is how much. It can be measured (including measurement error) to know if it fits the purpose. Usually even a few milliseconds aren't an issue if the setup is not doing any scientific timing sensitive stuff.
I can see how the multiple options for bridging MIDI into JACK can be confusing. This will be better once reduced to a single backend which should incorporate only the good aspects of the existing.
