### ISSUE TITLE
virtual audio device

### ISSUE THREAD

**Issue by richyxi** [jackaudio/jack2#438]
how can i create a virtual audio device?

**Comment by dvzrv** [comment]
The question is rather: "How can I write a useful ticket that doesn't contain only one unspecific question?" or "How do I not use a bug tracker for a software project as help line?" ;-)

Joke aside: You will be better off asking questions, where people are actually there to help you with a _setup_ problem. Try #opensourcemusicians on [freenode.net](http://freenode.net/), the [Linux Audio User mailing list](https://lists.linuxaudio.org/listinfo/linux-audio-user), or the [Linux Musicians forum](https://linuxmusicians.com/), or just searching .
