### ISSUE TITLE
Frequent periodic xruns

### ISSUE THREAD

**Issue by inverted-chan** [jackaudio/jack2#439]
Hello, I am not sure if this is the correct place to ask such a question, but here it is.

I am running up-to-date Manjaro with jack2 1.9.12. For few weeks, Cadence with alsa->pulseaudio->jack bridge has been working well. Today, something broke. When I pressed 'Start' button the xruns count started increasing in a periodic way. When I changed the buffer size to a much larger one, the issue persisted, just that xruns weren't that frequent. DSP load is ok, less than 5%.

I ran the jack2 with the command (and pressed Ctrl+C soon after)
```
/usr/bin/jackd -v -dalsa -r48000 -n2 -Chw:PCH,0 -Phw:PCH,0 >log.txt
```

Since then, I've tried installing jack2-git from AUR, and ran the command again, but the output is pretty much the same. [output](https://gist.github.com/inverted-chan/da92a9cac78b4202eafbfb9fec010675)

It has happened twice, and I am not sure why it got fixed the first time.
Issue is still present when pulseaudio is shut down. How can I get rid of it? Thanks.

**Comment by dvzrv** [comment]
Hi! As this is an issue tracker for the software itself, not a help forum for _setup problems_, [I would suggest the same as I did earlier](https://github.com/jackaudio/jack2/issues/438#issuecomment-470469958), maybe with the slight addition of the [arch-proaudio mailing list](https://lists.archlinux.org/listinfo/arch-proaudio) or your Manjaro forum/mailing list equivalent.

**Comment by inverted-chan** [comment]
I am posting this if anyone ever encounters the same and finds this ticket. 

Fast-boot in BIOS and Windows OS that I dual-boot with was most-likely the cause. I forced linux shutdown, disabled fast-boot in both bios and windows, shut down windows, booted into linux, and now jack works.

**Comment by dvzrv** [comment]
> I am posting this if anyone ever encounters the same and finds this
> ticket. 

I doubt that the issue you're experiencing is caused by fast boot, but
rather by some other hardware related setting on your device.

Either way: The solution to your problem is specific to your hardware
(or software) setup and therefore not relevant for this issue tracker or
even the average JACK user.

This issue was closed for a reason. Relevant resources to present or
solve your issue have been made available to you. Please stop using the
issue tracker as a forum.

**Comment by inverted-chan** [comment]
so, i shouldn't even have said that the problem was solved afterwards if i posted the problem in a wrong place? okay, i get it, thank you.
