### ISSUE TITLE
Getting error: JackPosixProcessSync::LockedTimedWait (Connection timed out)

### ISSUE THREAD

**Issue by bendavis78** [jackaudio/jack2#441]
I'm getting the following error when starting the jack server. I tried first using jackdbus, then uninstalled that and installed jackd standalone, but got the same result:

```
Mon Mar 18 10:51:34 2019: Starting jack server...
Mon Mar 18 10:51:34 2019: JACK server starting in non-realtime mode                                                   
Mon Mar 18 10:51:34 2019: self-connect-mode is "Don't restrict self connect requests"                                 
Mon Mar 18 10:51:34 2019: Acquired audio card Audio1
Mon Mar 18 10:51:34 2019: creating alsa driver ... hw:PCH,0|hw:PCH,0|256|2|44100|2|2|nomon|swmeter|-|32bit            
Mon Mar 18 10:51:34 2019: configuring for 44100Hz, period = 256 frames (5.8 ms), buffer = 2 periods                   
Mon Mar 18 10:51:34 2019: ALSA: final selected sample format for capture: 32bit integer little-endian                 
Mon Mar 18 10:51:34 2019: ALSA: use 2 periods for capture
Mon Mar 18 10:51:34 2019: ALSA: final selected sample format for playback: 32bit integer little-endian                
Mon Mar 18 10:51:34 2019: ALSA: use 2 periods for playback
Mon Mar 18 10:51:39 2019: ERROR: JackPosixProcessSync::LockedTimedWait error usec = 5000000 err = Connection timed out
Mon Mar 18 10:51:39 2019: ERROR: Driver is not running
Mon Mar 18 10:51:39 2019: ERROR: Cannot open client name = dbusapi                                                    
Mon Mar 18 10:51:39 2019: ERROR: failed to create dbusapi jack client                                                 
Mon Mar 18 10:51:39 2019: ERROR: Unknown request 4294967295                                                           
Mon Mar 18 10:51:39 2019: ERROR: CheckSize error size = 0 Size() = 12                                                 
Mon Mar 18 10:51:39 2019: ERROR: CheckRead error
```
What process is "timing out" here? How do I know what to troubleshoot next?

I'm using Arch linux, with all installed packages up-to-date. Here's some other (possibly) relevant info:

*CPU*: Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
*Memory*: 8GB
*Jack2 version*: 1.9.12-8
*Kernel*: Linux 4.14.24-rt19-1-rt x86_64 GNU/Linux

/proc/asound/cards:
```
 0 [HDMI           ]: HDA-Intel - HDA Intel HDMI
                      HDA Intel HDMI at 0xf7214000 irq 52
 1 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xf7210000 irq 49
```

**Comment by 7890** [comment]
@bendavis78 We can hardly support every jack package out in the universe.

If you think it's an error of jackd, please
-build jack from current source (see dbus related options)
-test if it works without dbus, with just a dummy jack
-make sure nothing else can interfere with jack getting a handle on the audio hardware
-make sure the audio hardware supports the selected sample rate
-run jackd in verbose mode

**Comment by bendavis78** [comment]
For anyone else coming across this issue via Google, the issue was that jack was not finding the correct device. Instead of hw:1, I used hw:PCH in my config, and that seemed to fix it. After that, I also realized I needed to stop pulseaudio before starting jack. Once I stopped pulseaudio, then started jack, then started pulseaudio again, everything worked.
