### ISSUE TITLE
How to reduce amount of locked shared memory area

### ISSUE THREAD

**Issue by sonicpp** [jackaudio/jack2#442]
I am doing some experiments with JACK2 on ARM (Buildroot/Linux) with very limited amount of available RAM (circa 100MiB). When I start jackd, it fails with following message:
```Cannot lock down 82278944 byte memory area (Cannot allocate memory) bus error```

I tried to reduce amount of allocated memory by system/apps and finally was able to run JACK2 daemon, but this is not appropriate solution for me.

I tried to disable memory locking, but it seems it has no effect, see bug #222 
I also tried to find the place where is locked this amount of shared memory, but with no success. Why is this exactly 82278944 bytes, no matter how many channels I use? Could someone point me to place in source code where is calculated this value? It would be very helpful to reduce it by 20 or 30 MiBs.

Thanks

**Comment by 7890** [comment]
waf configure has some options to limit:
```
--clients=CLIENTS     Maximum number of JACK clients
--ports-per-application=APPLICATION_PORTS Maximum number of ports per application
```
It might have an effect on memory footprint.

**Comment by sonicpp** [comment]
Thanks, I will give it a try

**Comment by sonicpp** [comment]
So I tried to edit configure options and was able to reduce it by circa 12 MiB (I expected more, but fortunatelly it is enough for my system). Here are some results:

| clients | ports-per-application | size|
|---|---|---|
| 64 | 768 | 82278944 |
| 4 | 768 | 81889664 |
| 8 | 32 | 69791328 |
| 4 | 32 | 69789824 |
| 2 | 16 | 69526336 |

Thanks!
