### ISSUE TITLE
Unable to build the client library using only LGPL sources

### ISSUE THREAD

**Issue by vikwil** [jackaudio/jack2#444]
Several of the LGPL licenced .c and .cpp files that are required for building libjack.so includes GPL licenced header files. Take for instance `common/JackLibAPI.cpp`, it includes
- `common/JackCompilerDeps.h` which is GPL
- `common/JackSystemDeps.h` which is GPL
- `JackGlobals.h` which in turn includes `JackConstants.h` which is GPL
- etc.

The GPL licenced header files that seem necessary to build for Linux at the moment are:
```
common/JackCompilerDeps.h
common/JackConstants.h
common/JackControlAPI.h
common/JackDriverLoader.h
common/JackException.h
common/JackNetSocket.h
common/JackSystemDeps.h
common/promiscuous.h
posix/JackCompilerDeps_os.h
posix/JackNetUnixSocket.h
posix/JackShmMem_os.h
posix/JackSystemDeps_os.h
```
Note that some of these files differ in licence between platforms, e.g. `windows/JackCompilerDeps_os.h`, `windows/JackShmMem_os.h`, and `windows/JackSystemDeps_os.h` are all LGPL.

Would it possible to change the licence for these files to LGPL?

**Comment by falkTX** [comment]
good point.
libjack was always supposed to be LGPL, if it is not then it needs fixing.

We need to see the authors of these files and contact them.

@sletz you wrote most of these files, they have copyright attributed to Grame
can you change them to be LGPL please?

**Comment by sletz** [comment]
I will not, but please do (keeping the GRAME copyright) .

**Comment by falkTX** [comment]
I can't just blatantly modify the license of files not created by me...
Please when you find some time, do it yourself.
Alternatively write down a small text giving permission for the change, signed by GRAME.
Thanks

**Comment by sletz** [comment]
Just did that here for the file that were originally done by GRAME ehttps://github.com/jackaudio/jack2/commit/e298b4409d186ef99cfb83e7b1d4a496cdb2c431
pushed on master

(I was after the commit that a develop branch in now in place... sorry for that).

**Comment by falkTX** [comment]
no worries, I will merge master to develop.
I have to write an email announcing these git repo changes...

**Comment by falkTX** [comment]
thanks for the fix btw.

@vikwil are you using a tool to check for this, or is it something you noticed manually?

**Comment by vikwil** [comment]
Thanks for addressing this so promptly!

I do not have any automatic tool to check for this, I noticed this while moving to a different build system.

@sletz Thanks for the quick fix, I see you changed the `common/JackException.h`, would you also consider changing `common/JackException.cpp`?

Finally, there is also the file `common/promiscuous.c` which is included in the build and GPL licensed.

**Comment by sletz** [comment]
Done in https://github.com/jackaudio/jack2/commit/56f760d986717faf7c76657083d06707b7852fb4

**Comment by vikwil** [comment]
After the changes made by @sletz the remaining files seem to be:

- `common/JackControlAPI.h` included by `common/JackDriverLoader.h` via `common/JackTools.cpp`
- `common/promiscuous.h` and `common/promiscuous.c` pulled in by `common/shm.c` and `linux/JackLinuxFutex.cpp`

The JackControlAPI I guess is not supposed to be a part of the client library. I have a fix that will exclude it from the dependency chain, I will submit a pull request for this.

@sdrik You seem to have added the promiscuous stuff in #257. Is this intended to be included in the jacklib? If that is the case the licences should change. If not, can we pry it out?

**Comment by sdrik** [comment]
The promiscuous stuff is definitely intended to be included in the jacklib. No problem in relicensing those file to LGPL. See PR #447.

**Comment by vikwil** [comment]
Thank you @sdrik for changing the license.

I made PR #448 which should remove the JackControlAPI transitive dependency.

**Comment by 7890** [comment]
was merged in a465c2bd366f039895787e70cafd929fd2e501be

**Comment by 7890** [comment]
Oops.. was that too quick?

**Comment by vikwil** [comment]
This is resolved for my purposes, I have not checked the wscripts in details since I don't use them. Also I have only checked for the linux platform.

I'm OK with closing this issue.

**Comment by falkTX** [comment]
nice, thanks to bring this up to our attention. I will close it then
