### ISSUE TITLE
netmanager loses a lot of packets while jack_netsource doesn't seem to lose a packet.

### ISSUE THREAD

**Issue by crocket** [jackaudio/jack2#457]
Raspberry Pi 3 B+ runs netmanager or jack_netsource (jack 1.9.12) on gentoo aarch64.
My desktop computer runs netjack2 or netjack1 (jack 1.9.12) on gentoo amd64.

## Network Configuration

`192.168.30.1` (Raspberry Pi) <--ethernet--> `192.168.30.2` (My Desktop)
`192.168.80.10`(Raspberry Pi) <--WiFi--> wireless router <--ethernet--> `192.168.80.12`(My Desktop)
wireless router <--ethernet--> the internet

## On Raspberry Pi 3 B+

```
jackd -P 99 -d alsa -d hw:sndrpihifiberry,0 -p 256 -n 2 -P
```

```
jack_load -i -c netmanager
or
jack_netsource -H 192.168.30.2 -o 1 -i 2 -O 0 -I 0 -n 2 -N gentoo
```

## On my desktop computer

```
jackd -P 99 -d net -a 192.168.30.1 -l 0 -P2 -C1
or
jackd -P 99 -d netone
```

## What happens

While playing videos or music, netmanager loses one packet per several minutes initially. After a few minutes, packet loss grows to the point where I can't listen to anything because there are a lot of continuous crackles in audio.

```
Packet(s) missing from... -1 1
Wrong packet type : a
NetMaster : missing last data packet from 'gentoo'
NetMaster : missing last data packet from 'gentoo'
NetMaster : missing last data packet from 'gentoo'
NetMaster : missing last data packet from 'gentoo'
NetMaster : missing last data packet from 'gentoo'
....(hundreds of missing packets)
```

It seems that jack_netsource doesn't report a single packet drop.

## Questions

* Is it a hardware issue or a software issue?
* Was WiFi involved in huge amounts of packet drops?

**Comment by 7890** [comment]
A _generic_ comment for this issue is that wireless connections aren't usually a good fit for connecting jack. The probability of out-of-order and/or dropped packets (UDP) is much higher for wireless than for wired local area network.

**Comment by crocket** [comment]
@7890 I don't know whether WiFi was involved in the first place. I made netjack2 communicate via an ethernet interface.

**Comment by crocket** [comment]
I disabled WiFi. netjack2 is directly connected to my desktop via an ethernet cable.

netmanager still loses a lot of packets.

```
NetMaster : missing last data packet from 'gentoo'
Packet(s) missing from... -1 4
Packet(s) missing from... -1 1
Packet(s) missing from... 2 0
Packet(s) missing from... 0 3
Packet(s) missing from... 0 2
Packet(s) missing from... 2 1
Packet(s) missing from... 1 3
```

**Comment by crocket** [comment]
Is it possible that Raspberry Pi 3 B+ loses a lot of UDP packets over a direct ethernet connection and jack_netsource ignores packet drops to a degree until netxruns are caused?

**Comment by crocket** [comment]
The cause seems to be the mismatch of ethernet speed between Raspberry Pi 3 B+ and gentoo desktop.
After setting ethernet speed to 100Mbps on both Raspberry Pi 3 B+ and gentoo desktop, I don't see packet drops.
