### ISSUE TITLE
JACK 64bit Application Support For Windows

### ISSUE THREAD

**Issue by MrTeeXD** [jackaudio/jack2#466]
Hello, so i was told to contact the devs of OBS and i found out that JACK only has support for 32Bit Applications for Windows. Can it be possible for JACK to support 64Bit Applications as well, i want to use this for audio routing

**Comment by kmatheussen** [comment]
Hi, this is not correct. Jack supports both 32bit and 64bit applications.

**Comment by MrTeeXD** [comment]
@kmatheussen Oh then how can OBS not pick up the Input Client? am i missing something?

**Comment by kmatheussen** [comment]
I don't know. Maybe OBS was been compiled against a too old version of
libjack which had incompatible header files. Probably not.

**Comment by MrTeeXD** [comment]
Oh dear, now how else will i be able to sent Audio from Carla to OBS

**Comment by kmatheussen** [comment]
Can you explain exactly what you mean by "OBS not pick up the Input
Client"? Is there an error message in obs or jackd? Have you been in
contact with the OBS developers about the issue?

**Comment by MrTeeXD** [comment]
Hello, no there are no error messages that appeared, it looks like when the JACK Server is activated, OBS does not list the Input Client in the Audio Sources in both settings and Audio Source. As for Jackd, i have no idea on how to activate it

**Comment by kmatheussen** [comment]
Do you use qjackctl to start jack (i.e. jackd)? Any messages in the message
window when OBS tries to connect?

Are you sure the 64 bit version of OBS is even compiled against jack? Have
you asked the OBS developers? This is most likely the wrong forum to get
help fixing this problem.

**Comment by MrTeeXD** [comment]
The Message Window showed nothing about OBS trying to connect, even adding it as a client within JACK does nothing, I dont know what to do. As for OBS compiled against jack, that i may have to ask about to the OBS Devs

**Comment by MrTeeXD** [comment]
This issue needs to be closed
