### ISSUE TITLE
error in 1557c4 commit

### ISSUE THREAD

**Issue by jgastonraoul** [jackaudio/jack2#467]
Hi,
There is a problem in 1557c4fddfb8107612350da4af4bb4d03bc76f43 commit : some merge message remains in lines 611 to 615 of file common/JackEngine.cpp.

```
<<<<<<< HEAD
    if (uuid < 0) {
=======
    if (jack_uuid_empty(uuid)) {
>>>>>>> f7f2244b07ee0a723853e838de85e25471b8903f
```
Regards,
Jérémie

**Comment by falkTX** [comment]
I missed that when solving merge conflicts.
Somehow I did not get notified when the CI build failed, need to fix that.

Thanks for noticing, fixed now.
