### ISSUE TITLE
Try to compile jack2 source code on window's 10 code block but didn't get any success

### ISSUE THREAD

**Issue by Gauravarora09** [jackaudio/jack2#471]
when i try to compile jack2 source code on windows 10 code blocks it show header files are missing.so i copy from github and add them . now it shows another header file is missing. there are lots of header files.please tell me i have to add these all header files by my own or i did something wrong.

**Comment by falkTX** [comment]
Building for windows is not supported at the moment.
We are focusing on finishing the API (metadata), and then do jack1 feature parity and cleanup.
Until that happens, Windows is left on the side.

That said, PRs are welcome.
