### ISSUE TITLE
No JackRouter in the device list while running the command "jackd -d portaudio -l"

### ISSUE THREAD

**Issue by Gauravarora09** [jackaudio/jack2#478]
Not able to get the JackRouter in the device list when i run the command "jackd -d portaudio -l".
At the end, after listing all the other devices, i get-

Cannot initialize driver
JackServer::Open failed with -1
Failed to open server

Even though i have initialized the driver with setting the target as "C:\Program Files (x86)\Jack\jackd.exe" -R -S -d portaudio -d "ASIO::ASIO4ALL v2" in the Jack portaudio properties.

**Comment by falkTX** [comment]
jack router is no longer supported and has been removed from jack2.
new maintainers welcome for it
