### ISSUE TITLE
compile error with clang 8.0.1

### ISSUE THREAD

**Issue by markand** [jackaudio/jack2#486]
Hello,

I'm trying to build jack2 with clang (configured to use libc++) instead of GCC. I get the following error while in GCC it builds fine:

```
../posix/JackNetUnixSocket.cpp:172:16: error: no viable conversion from returned value of type '__bind<int &, sockaddr *, unsigned lon
g>' to function return type 'int'
        return bind(fSockfd, reinterpret_cast<socket_address_t*>(&fRecvAddr), sizeof(socket_address_t));
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 warnings and 1 error generated.
```

**Comment by falkTX** [comment]
this is already fixed in latest git, release will be out soon

**Comment by markand** [comment]
Thanks for this quick response :)

I presume from this [commit](https://github.com/jackaudio/jack2/commit/d851fada460d42508a6f82b19867f63853062583)?

I'll apply it locally for the moment. I've searched for existing issues but I didn't find them. I should have checked the git version before. Sorry for the noise!
