### ISSUE TITLE
Disable log spam

### ISSUE THREAD

**Issue by piegamesde** [jackaudio/jack2#489]
If I make a JACK client, it will automatically spam my stdout with JACK log messages. This is not acceptable. Please let me create silent JACK clients.

I am currently making a TUI application and thanks to the logs it looks like this:
![image](https://user-images.githubusercontent.com/14054505/63090713-73ab1880-bf5c-11e9-9e81-d14482f5b945.png)

**Comment by falkTX** [comment]
Disable jack verbose mode and you will not see these messages.

**Comment by falkTX** [comment]
I mean when starting up jack.

if that is not enough, use the info and error functions like in http://www.jackaudio.org/api/group__ErrorOutput.html#ga1555b7b4ae4056a42c70a3fa278ae17f

**Comment by piegamesde** [comment]
Thank you very much. I knew about the `--verbose` option, which was not enough for me, but I had completely missed that one could set custom log callbacks.
