### ISSUE TITLE
JACK daemon with LGPL license

### ISSUE THREAD

**Issue by twischer-adit** [jackaudio/jack2#500]
We are interested in loading audio processing plugins internally due to startup and runtime performance gain. But some parts of the JACK daemon and libjackserver are licensed under GPL.
We do not want to (and cannot) publish our proprietary audio processing plugins (we are also not the owner of all components). Therefore my question:

Would it be possible to license complete JACK under LGPL?

**Comment by falkTX** [comment]
No, and please do not ask again.

You should still be able to make use of internal clients though, I do not think LGPL is needed for that

**Comment by twischer-adit** [comment]
Hello @falkTX 

> You should still be able to make use of internal clients though, I do not think LGPL is needed for that

Sorry to bother you. This is currently a critical discussion on our site. So far our understanding is, that the viral effect of the GPL already exists if GPL code and proprietary code is loaded at runtime into one program. So an internal JACK client is not linked to any GPL libraries but it is loaded into the jackd which has the GPL license.
Therefore we would expect that the viral effect exists.
If you are aware of any explanation why this viral effect does not exist in this case it would be great if you could give me a hint.

Thanks a lot.

**Comment by falkTX** [comment]
you are not linking against libjackserver but you link against libjack.
the thing is that both libjackserver and libjack implement the common JACK APIs, so they work for both internal and external clients.

now in regards to runtime, this is what I am not sure about legalities..
there are a few daws that `dlopen` libjack and thus dont link against it, but they use libjack, not libjackserver
we have a similar issue with daws and commercial plugins, as they run in the same process.

obviously I am not a lawyer, so I do not know how far this can be pushed.
but relicensing to LGPL would involve getting agreement from every single contributor to JACK.
looking at https://raw.githubusercontent.com/jackaudio/jack2/develop/AUTHORS.rst the list is not small.
and I am really not going to be the one doing that.
JACK2 is not my original project, I am just maintaining it at the moment (and not alone). Even if I would agree (which I state again, I do not) you would still need to get approval of all those people
