### ISSUE TITLE
Port type discussion

### ISSUE THREAD

**Issue by piegamesde** [jackaudio/jack2#515]
While writing #514 I came across some weird things about port types I'd like to discuss. But first off, a few comprehension questions:

- What semantic meaning does a port's type have?
- How does Jack handle connecting ports of different type?
- How does Jack handle custom port types?
- When does Jack make the difference between Audio and Midi mixdown? Again, what about custom port types?

**Comment by falkTX** [comment]
very good questions but sadly I cannot provide good answers.
jack provides no support at all for custom port types, one has to implement all the things about a new type (buffers, mixdown, how to read and write, etc)
for the others, this might be of help https://github.com/jackaudio/jackaudio.github.com/wiki/A_guide_to_the_Jack2_source_code

**Comment by piegamesde** [comment]
- If there is a midi driver and an audio driver – can multiple drivers be active at the same time?
- If so, where does Jack choose to use which driver?

**Comment by falkTX** [comment]
yes and yes, and it is complicated...

some midi drivers are implemented as engine slave drivers (alsarawmidi), some are implemented as audio driver options (alsa seq and raw modes).
and coming soon (code taken from jack1) are midi "drivers" as internal clients (a2jmidid based code)

no idea how coremidi and windows midi is handled, I dont use those systems

**Comment by piegamesde** [comment]
So, the current API exposes a string called "port type" without properly defining its semantic meaning. And using a string that is not one of the `JACK_DEFAULT_*_TYPE` provided constants results in unknown behavior. I thus propose the following:

- Limit the port type property to the few known strings and check it at port creation
- Currently allowed types: `JACK_DEFAULT_AUDIO_TYPE` and `JACK_DEFAULT_MESSAGE_TYPE`. `JACK_DEFAULT_MIDI_TYPE` will be deprecated and bent back to `JACK_DEFAULT_MESSAGE_TYPE`.
- Deprecate the current port creation function in favor to helper functions that have a fixed value: `jack_port_register` will become something like `jack_port_register_audio` and `jack_port_register_message`.
- Add helper methods that automatically set the `JACK_METADATA_EVENT_TYPES`/`JACK_METADATA_SIGNAL_TYPE` flag (that naming convention is quite unfortunate btw)

**Comment by falkTX** [comment]
The 3 port types sound sane to me. I do not think there is a need to deprecate MIDI stuff though.
Neither is the port-register deprecation needed either.

helper functions could be made, sure. but I would make them inline, so we do not have to get new symbols in the jack API just for them.
(meaning, a new client that uses it to create MIDI ports would remain backwards compatible with old JACK releases)
