### ISSUE TITLE
jack-devel Mailinglist down

### ISSUE THREAD

**Issue by 7890** [jackaudio/jack2#518]
```
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  jack-devel@lists.jackaudio.org
    The mail server could not deliver mail to jack-devel@lists.jackaudio.org.  The account or domain may not exist, they may be blacklisted, or missing the proper dns entries.
Reporting-MTA: dns; ips73.ips.ch

Action: failed
Final-Recipient: rfc822;jack-devel@lists.jackaudio.org
Status: 5.0.0
```
Any chance this gets repaired?

**Comment by falkTX** [comment]
Did you miss the discussion recently there?
The mailing list is down after the move of jackaudio.org to another server.

**Comment by 7890** [comment]
I did not miss the discussion there, no. It was just not obvious that the decision is final, after some participants made clear that this is a bad idea.
I'm going to setup a new list on sourceforge.net for jack-devel. It's a pitty that this must be done now that the current mailing list is already down. This makes the transition very odd, eg. to subscribe the previously subscribed members. Do you eventually have saved a list of those?

**Comment by falkTX** [comment]
someone already reached out to me and Paul Davis, so an alternative is perhaps underway.

I thought it was pretty clear in the jack ML that it was shutting down.
It was just a matter of time until the servers got moved.

**Comment by 7890** [comment]
What a great example of good communication! I guess it will happen "sometime this year"?
Meanwhile, I've already setup a list. So.. do you have saved a list of the subscribers?
It's obvious that this should have happened _before_ shutting down the list.

**Comment by falkTX** [comment]
It is so obvious and somehow we completely forgot about it...
I have dealt with you before, I do not want your help, thank you.

**Comment by piegamesde** [comment]
Just to be sure: I don't think giving out the list of subscribers would be GDPR compliant.

**Comment by kmatheussen** [comment]
Did you block 7890 for what he/her said in this thread? Why?

I agree about the sentiment though. It's weird shutting down the mailing list so abruptly. We should have gotten time to set up an alternative and to post address to the new mailing list on the old mailing list.

**Comment by kmatheussen** [comment]
If there's any chance you could reopen the mailing list so we could do that, that would be great.

**Comment by falkTX** [comment]
There is a misunderstanding here perhaps
The mailing list shut down was unintentional, a side effect from moving domains.
I cannot just "turn it back on", as it is just gone now.

Trying to fix something else in the webserver and tired of always having to ask the old owner about small "silly" things, I decided to stop being lazy and do something proper about it.
So I set up with Paul Davis to move the jackaudio.org from old dreamhost to one I control.
First we setup just DNS to it pointed to a new hosting provider (the one that hosts kx.studio and a few other things).
All was fine, but not truly complete. After a few days ensuring it works fine, we set out to move the domain as well.
In the middle of the process, while it was already going and about to be finalized (that is, no longer in our hands), I wondered about what would happen with the mailing that uses the jackaudio.org domain.. well shit, we realized what the move meant - mailing list would be gone.
dreamhost provides a mailing list service together with domains and other things. Paul spent quite some time talking to dreamhost support asking what could be done about it.
It could not be moved, but at least we got a backup.
We were lucky to realize in time that it would be gone. If not, the mailing list would have disappeared and I would not have sent that email noticing the people there... (as you know, just a few days later and it no longer worked)

Now, there are things happening that would allow to get the mailing list back.
Though as I mentioned in the email, I will not be the one maintaining it.

Worst case scenario, we put the mailing list together with the others of linuxaudio.org (LAU, LAC, LAD, LAA). They share very similar interests. I already have confirmation that we can do this.

**Comment by 7890** [comment]
@falkTX Please be assured, the help was not directed towards you personally.

However when looking at JACK as something that serves a superior purpose beyond your personal toy, it's bad to see how things develop.

Just blocking out users won't solve the core of the issues, which in this case is the _accidental_ and permanent shutdown of the mailing list, combined with total ignorance and the absence of any reasonable attempts to improve or mitigate the situation.

Said that, I think you need help, both personally and to maintain JACK.

**Comment by falkTX** [comment]
JACK is not a toy, I take maintaining it to be quite the serious task.
A new JACK2 release was delayed until it was 100% confirmed to work as intended. @dvzrv confirmed a last-needed fix yesterday.

Sorry it does not evolve in the way you would like it to, we got different goals I guess.
I am glad that maintenance of JACK is not up to you.

I will see what is the status regarding the mailing list. Might be time to try the fallback plan.

In any case, this conversation is going nowhere, I am locking this topic.

**Comment by falkTX** [comment]
The mailing list is back up, now at https://lists.linuxaudio.org/archives/jackaudio/

Accounts do not get automatically moved over, you have to re-subscribe.
The archive is all in there still though.
