### ISSUE TITLE
Friendly name for channels

### ISSUE THREAD

**Issue by szszoke** [jackaudio/jack2#521]
Hello!

Making two devices from BOSS work under Linux.

The BOSS KATANA and the BOSS SY-300.

They both have a lot of playback and capture channels and it's really easy to get lost amon them.

I was wondering if it's possible to tell Jack to use a specifi name for individual channels instead of `capture_{n}` and `playback_{n}`.

**Comment by szszoke** [comment]
I forgot to mention that I am using the ALSA driver

**Comment by 7890** [comment]
Sure, you can use port aliases, eg.
```
jack_alias "system:capture_1" "boss_katana:capture_1"
```
You can refer to port `boss_katana:capture_1` now.
Currently defined aliases for ports are shown with `jack_lsp -A`.
