### ISSUE TITLE
32bit libjack contains undefined symbol "db_create" when jack is built in mixed mode

### ISSUE THREAD

**Issue by mickski56** [jackaudio/jack2#523]
As title. This is with jack 1.9.14, which should I think build 32bit libjack without db support, yet this symbol somehow ends up in mixed mode 32bit libjack.

**Comment by falkTX** [comment]
That is correct.
Do you get an error somewhere?

**Comment by mickski56** [comment]
yes
WINEARCH=win32 WINEPREFIX=${HOME}/.wine wine /usr/lib/wine/regsvr32.exe wineasio.dll

0009:err:module:load_so_dll failed to load .so lib "/usr/bin/../lib/wine/wineasio.dll.so": /usr/local/lib/libjack.so.0: undefined symbol: db_create
regsvr32: Failed to load DLL 'wineasio.dll'

**Comment by mickski56** [comment]
commit a39d2df15e13bc406f780ae6e91c7c1a61b68f76
Fixes the isssue for me Thanks.

**Comment by falkTX** [comment]
Forgot to close this issue before, doing that now!
