### ISSUE TITLE
ALSA backend doesn't build on raspbian

### ISSUE THREAD

**Issue by hires** [jackaudio/jack2#532]
Using the following waf config line indicates it will build ALSA backend files but no ALSA-related files are compiled or linked:

./waf configure --destdir=/usr/lib/waf configure --alsa=yes --prefix=/usr

I'm using release 1.9.14. Thanks!

**Comment by falkTX** [comment]
Try removing the `=yes` and just use `--alsa`

**Comment by hires** [comment]
The following config line worked:

./waf configure --alsa --portaudio=no --prefix=/usr

I'm not sure what the difference of --destdir made. But --alsa=yes was one I tried before and it also didn't work.
