### ISSUE TITLE
Question About JackAudio ASIO

### ISSUE THREAD

**Issue by MrTeeXD** [jackaudio/jack2#538]
So, after reading the Wiki, I came across the Word "JackAudio ASIO" and what I was wondering is, does JACK2 come with JackAudio ASIO for Windows. Last time I used JACK2, i looked everywhere in the Folder for this specific item and I did not find it.

**Comment by falkTX** [comment]
JACK does not include that. The ASIO support is done by portaudio, which JACK on Windows can use as a backend

**Comment by MrTeeXD** [comment]
Ohhh i see. Closing this issue

**Comment by kmatheussen** [comment]
Jack includes something called "JackRouter ASIO" though, which might be what you are looking for (a general asio driver that connects to jack): https://jackaudio.org/faq/jack_on_windows.html
