### ISSUE TITLE
JackRouter doesn't appear in OSX Sound prefs input or output - so isn't working?

### ISSUE THREAD

**Issue by davenewt** [jackaudio/jack2#544]
Hi, I found out about Jack2 and excitedly installed it on OSX Mojave 10.14.5

Installed fine, rebooted, all good. Run JackPilot, and I can see its window, stop/start it, and open the connections manager.

BUT when I open the OSX Sound prefs pane, **JackRouter doesn't appear anywhere** (not under Input or Output)

I've uninstalled/reinstalled/rebooted several times, looked elsewhere for anyone solving this issue, but cannot find anything to help, so hoping someone here might have an answer. Thanks in advance.

**Comment by tquintas** [comment]
Having the exact same problem, on the same macOS, tried to find the audio device's download or any installation but I found nothing... I'm also hopping someone has an answer. Thanks!

**Comment by gdhgdhgdh** [comment]
The JackRouter binary included in the JackOSX 0.92_b3 installer is a 32-bit binary, and macOS Catalina dropped support for 32-bit code.

As a workaround I have been using this `JackBridge` instead. Lots of pain having to accept security popups, etc. but it will work until macOS 10.16, which drops support for kernel extensions.

https://github.com/madhatter68/JackRouter

**Comment by KonVas** [comment]
MacOS: 10.15
I must have spent half of the day to make it work. Working on almost any possible workarounds, including binding it to both multi output and aggregate devices with no luck. What I am doing: I am starting the Jack server and (Version: 0.6.0), and then I am running the JackBridge -> `JackBridge#0: Activated with SyncMode = Yes, ZeroHostTime = 82f66bac000` and then using something like this in SuperCollider: `Server.default.options.outDevice_("JackBridge"); //seems available 
s.reboot;` and then connecting JackBridge outputs to system outputs from the server's `graph` GUI. At this point I can listen to the sound coming from SC but when I am routing JackBridge to another app like Audacity to record or even to Google Meet/Skype for example I get silence. I have checked the Audio and MIDI Set Up of my OS and JackBridge out sliders are non responsive, not muted but just not working. Is there anyone else had this problem so far with a possible solution?

**Comment by falkTX** [comment]
jack-router is no longer supported or part of jack2.
see also https://github.com/jackaudio/jack2/issues/618#issuecomment-710426612
