### ISSUE TITLE
thru_client compilation issue

### ISSUE THREAD

**Issue by Gruggel** [jackaudio/jack2#549]
I am trying to compile thru_client.c with gcc v. 7.4.0 on Ubuntu 18.04.1, but the line
in = jack_port_get_buffer ( input_ports[i], nframes );
in "process" results in the error
/home/me/projects/MyTestApp/src/jackportinfo.cpp: In function ‘int process(jack_nframes_t, void*)’:
/home/me/projects/MyTestApp/src/jackportinfo.cpp:51:35: error: invalid conversion from ‘void*’ to ‘jack_default_audio_sample_t* {aka float*}’ [-fpermissive]
         in = jack_port_get_buffer ( input_ports[i], nframes );

The installed version of Jack is 1.9.12 and I have installed the dev-libs:
sudo apt install libjack-jackd2-dev

Am I using incompatibe libs? 
Is this the correct version of the docs? https://jackaudio.org/api/group__PortFunctions.html#ga209880b64774dd039c703ea8e3b9ca63

**Comment by falkTX** [comment]
You need to cast the return to `jack_default_audio_sample_t*`.
In C you can directly take a void* and make it any pointer type, but this is not allowed in C++

**Comment by sigm** [comment]
That compiles. Thanks. But why does jack_port_get_buffer return a pointer of type void? Why not  "jack_default_audio_sample_t*"?

**Comment by kmatheussen** [comment]
The data returned by jack_port_get_buffer depends on the port type.
Ports can have MIDI, for instance. (well, currently it can only
contain MIDI or audio, at least in the main repo)

**Comment by sigm** [comment]
Also, the line

jack_set_process_callback ( client, process, 0 );

yields the error message:

/home/me/projects/MyTestApp/src/jackportinfo.cpp:119:52: error: invalid use of non-static member function ‘int JackPortInfo::process(jack_nframes_t, void*)’
     jack_set_process_callback ( client, process, 0 );

Looks a bit like the first hiccup, bit I have not been able to fix this with type casts.

**Comment by falkTX** [comment]
you need to use a static function there. pass the pointer to your class so you can use it there.

**Comment by sigm** [comment]
That seems to be it: gcc is happy. Thanks.
