### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by LeandroStanger** [jackaudio/jack2#563]
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing JACK on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by h1z1** [comment]
But... why?

**Comment by falkTX** [comment]
JACK needs to be a system service, with all applications finding its single instance so they can share audio with each other.
So I do not think it fits Flakpak design

It is kinda like asking to have a Flatpak for pulseaudio, avahi, or X11 or any other system wide service.
Is that even possible for stuff like Flatpaks?
