### ISSUE TITLE
Can Jack connect two apps with different sampling frequencies and buffer size?

### ISSUE THREAD

**Issue by vocobox** [jackaudio/jack2#566]
I am trying to use Jack 2 (0.92_B3) on MacOS 10.12.6 to send audio from an Arturia drum machine (the producer) to Jamulus (the consumer). I ran JackPilot and wonder if it can be used to share audio content between applications with different audio settings.

Connecting the sound producer to Jack
- Each time I try to select Jack in Spark device list, Spark display an error message : "Couldn't change buffer size". I tried all buffer size setting in Jack without success. **How can I guess the expected buffer size on the producer application? Is it possible to let Jack adapt to it?** Spark does not display sampling frequency and buffer size until the device is loaded.

Connecting the sound consumer to Jack
- At the beginning Jamulus threw an error asking for 48KHz sampling frequency. This halted the Jack server with an error popup, so I restarted the Jack server with 48KHz setting.
- When trying to select Jack as input in Jamulus, JackPilot pops another error : "Another application has changed the sampling rate" which is surprising, since the two applications where both on the same sampling rate.
- Then restart Jamulus and Jack with 48KHz, it is fine.

**Will Jack be able to resample from consumer to producer sampling rates automatically?**

NB : Hog mode is off.

**Comment by jkbd** [comment]
Also posted here: https://github.com/corrados/jamulus/issues/142.
