### ISSUE TITLE
Jack on Windows can't open WDM-KS devices even though QJackCtl lists them

### ISSUE THREAD

**Issue by elliotclee** [jackaudio/jack2#568]
On Windows with Jack 1.9.11 from the official site, I configure things with qjackctl and then start jackd. I get the message when starting:

Can't open Windows WDM-KS::Microphone (iO|2), PortAudio will use default input device.
Can't open Windows WDM-KS::Speakers (iO|2), PortAudio will use default output device.

When I run jackd -d portaudio -l those inputs/outputs are not listed. However, when I use qjackctl they are on the list.

I noticed that the version of libportaudio_x64_64.a in git is really old - is it possible that qjackctl is using a different portaudio than jackd? Could you update everything to the latest portaudio to see if that fixes it?

**Comment by falkTX** [comment]
Please try again with the latest 1.9.15 release, thanks.
(uninstall the old one first)

**Comment by elliotclee** [comment]
That fixes it - thank you!
