### ISSUE TITLE
Client unable to connect to JACK server v.1.9.14

### ISSUE THREAD

**Issue by hgshoggins** [jackaudio/jack2#569]
Is there a notable change in JACK's API between version `1.9.12` and `1.9.14`?
Clients that were able to connect to `1.9.12` are now unable to do so with `1.9.14`. Example with Rivendell ElvishArtisan/rivendell#569: reverting to `1.9.12` makes it able to connect again, even with a full recompile against the correct headers.
On my Fedora 32 machine with my downgraded JACK version `1.9.12`, now PulseAudio plugins can't connect anymore. I guess it has something to do with a major change between versions.
Any hint?

**Comment by falkTX** [comment]
Yes, meta-data was implemented, which changes a lot of stuff in JACK internal data.
You need to restart the jack server after such an update.

How did you install rivendell? The report seems as if the JACK version used by it is different from the system one.
Are you able to use rivendell with JACK1? That would be a good test too.
If the application presents JACK2 related messages with JACK1 installed, something then is really messed up

**Comment by hgshoggins** [comment]
Regarding Rivendell, the exact process was:
- [x] I had a hand-compiled version of Rivendell on a Fedora 31 machine (with `jack-audio-connection-kit-1.9.12-10.fc31.x86_64`)
- [x] Upgraded this machine to Fedora 32, now shipping with `jack-audio-connection-kit-1.9.14-2.fc32.x86_64`
- [x] Noticed that Rivendell's `caed` would not connect anymore to JACK
- [x] Uninstalled Rivendell's  binaries
- [x] Recompiled and reinstalled it against `jack-audio-connection-kit-devel-1.9.14-2.fc32.x86_64`
- [x] Even after a full machine reboot, no success in connecting `caed` to JACK, it fails with a socket connection error
- [x] So I downgraded JACK on my Fedora 32 machines with imported RPMs. I now have:
  * `jack-audio-connection-kit-1.9.12-10.fc31.x86_64`
  * `jack-audio-connection-kit-dbus-1.9.12-10.fc31.x86_64`
  * `jack-audio-connection-kit-devel-1.9.12-10.fc31.x86_64`
- [x] Rivendell's `caed` now correctly connects to JACK
- [ ] Now PulseAudio's plugins like `module-jack-sink` or `module-jack-source` can't connect. I guess this is expected because they're adapted to JACK v. `1.9.14`

My best shot would be to understand what I can patch in Rivendell's code to make it connect again to JACK v. `1.9.14` instead of this ugly downgrade.

**Comment by hgshoggins** [comment]
(I don't think I can easily test `caed` with JACK1)

**Comment by falkTX** [comment]
There is nothing to patch, JACK remains API compatible for pretty much all of JACK1 and JACK2 releases.
Clients link against the JACK library, so issues regarding versions are not possible unless applications decide to (wrongly) with a mismatching libjack.so library.

Do any other JACK applications work?

**Comment by hgshoggins** [comment]
It looks like I'm only experiencing issues with Rivendell, not with other JACK-enabled applications. All of these have been installed through packages, and are supposedly "in sync" with this version of JACK as they are shipped with Fedora 32.
Only my hand-compiled Rivendell installation is unable to communicate with JACK once it's back to c. `1.9.14`.
I noticed though that `/usr/include/jack/jack.h` (and all header files located in `/usr/include/jack/` haven't been updated with the upgrade from `1.9.12` to `1.9.14`... should I be concerned about this?

**Comment by falkTX** [comment]
The headers are not important, no.

Could it be that perhaps you have custom-built libjack somewhere in /usr/local ?

**Comment by hgshoggins** [comment]
Doesn't seem so.
```
# locate libjack.so
/usr/lib64/libjack.so
/usr/lib64/libjack.so.0
/usr/lib64/libjack.so.0.1.0
/usr/lib64/carla/jack/libjack.so.0
```
Could Carla's `libjack.so.0` get in the way?

**Comment by falkTX** [comment]
nah, carla is too deep in there to cause an issue.

I am out of ideas here, sorry.

**Comment by hgshoggins** [comment]
Thank you, I'll check with Rivendell directly and report here.

**Comment by hgshoggins** [comment]
Hitting the same issue with v. `1.9.14` but on a Fedora 33 machine.
Although I hate linking things that have nothing in common, I find the issue https://github.com/hydrogen-music/hydrogen/issues/840 really similar, and I believe it's worth looking at it. It's not the same OS not the same Jack version, but the clues are the same.

Unfortunately I can't debug as deep, `caed` won't let me see where it tries to find the `jackd` socket, but obviously it fails to do so, and states that there is no running Jack server.

I tried to dig into the file structure of Jack to see what could potentially cause clients to not recognize a running Jack server, and went into `/dev/shm`. Is there anything I should look at? The file structure seems different between two versions: `1.9.12` has this: 
```bash
[root@grosrobert]# ls -l /dev/shm/jack*
-rw-rw-r-- 1 radiom radiom 107341338 23 oct.  16:31 /dev/shm/jack-1000-0
-rw-rw-r-- 1 radiom radiom      1187 23 oct.  16:31 /dev/shm/jack-1000-1
srwxrwxr-x 1 radiom radiom         0 23 oct.  16:31 /dev/shm/jack_default_1000_0
-rwxrwxr-x 1 radiom radiom        12 23 oct.  16:31 /dev/shm/jack_sem.1000_default_freewheel
-rwxrwxr-x 1 radiom radiom        12 23 oct.  16:31 /dev/shm/jack_sem.1000_default_pa_jack_sink
-rwxrwxr-x 1 radiom radiom        12 23 oct.  16:31 /dev/shm/jack_sem.1000_default_pa_jack_source
-rwxrwxr-x 1 radiom radiom        12 23 oct.  16:31 /dev/shm/jack_sem.1000_default_system
-rw-rw-rw- 1 radiom radiom     70744 23 oct.  16:31 /dev/shm/jack-shm-registry
```
whereas `1.9.14` shows a bit more:
```bash
[root@petitpaul]# ls -l /dev/shm/jack*
-rw-rw-r-- 1 radiom radiom 107341338  3 nov.  22:54 /dev/shm/jack-1000-0
-rw-rw-r-- 1 radiom radiom      1187  3 nov.  22:54 /dev/shm/jack-1000-1
srwxrwxr-x 1 radiom radiom         0  3 nov.  22:54 /dev/shm/jack_default_1000_0
-rwxrwxr-x 1 radiom radiom        12  3 nov.  22:54 /dev/shm/jack_sem.1000_default_freewheel
-rwxr-xr-x 1 radiom radiom        12  3 nov.  22:39 /dev/shm/jack_sem.1000_default_pa_jack_sink
-rwxr-xr-x 1 radiom radiom        12  3 nov.  22:39 /dev/shm/jack_sem.1000_default_pa_jack_source
-rwxrwxr-x 1 radiom radiom        12  3 nov.  22:54 /dev/shm/jack_sem.1000_default_system
-rw-rw-rw- 1 radiom radiom     70744  3 nov.  22:39 /dev/shm/jack-shm-registry

/dev/shm/jack_db:
total 224
-rw-rw---- 1 radiom radiom 303104  3 nov.  22:54 __db.001
-rw-rw---- 1 radiom radiom  40960  3 nov.  22:54 __db.002
-rw-rw---- 1 radiom radiom  49152  3 nov.  22:54 __db.003
-rw-rw-r-- 1 radiom radiom  12288  3 nov.  22:54 metadata.db
```

Could it be that the `-devel` libraries used during client compilation try to find a different file structure than the one that is actually deployed by a running `1.9.14` Jack server? I guess the actual socket is `/dev/shm/jack_default_1000_0` for all the systems so clients should not struggle to find them and connect, but anyway that's what's happening.

I'm really lost, and it's been a while since I could upgrade some machines because doing so would break our whole system.

**Comment by hgshoggins** [comment]
Despite having recompiled again and again, and reinstalled it over, it refused to connect.
Then... it did.

Sorry for the noise.
