### ISSUE TITLE
JACK 1.9.11 64 bit Windows installs in incorrect location

### ISSUE THREAD

**Issue by x42** [jackaudio/jack2#574]
Jack_v1.9.11_64_setup.exe contains both 32 and 64bit binaries, but installs both to in the 32bit folder "Program Files (x86)".

This is an issue with 64bit Ardour looking for jackd.exe in "Program Files" on a 64bit system.

(If jackd is started manually then ardour/mixbus finds is and seems to work. The issue is just with Ardour starting JACK)

Forwarded from https://tracker.ardour.org/view.php?id=7903

**Comment by johne53** [comment]
I think this was done deliberately (for Mixbus). Back in the early Mixbus, the 32-bit and 64-bit Jack binaries needed to share a common root for their install folder. I can't remember why we did this but I'm pretty sure that's the reason. After some investigation today, it seems that the reason why Ardour can't launch Jack (on Windows) is that it uses the code originally written for Mixbus when it was being built with MSVC. The same code will probably work for a gcc build but it needs to be tested.

**Comment by johne53** [comment]
johne53 wrote:
> Back in the early Mixbus, the 32-bit and 64-bit Jack binaries needed to share a common root for their install folder.

After giving this some more thought, I've remembered that the early releases of Mixbus needed to install their own bundled version of Jack and it was probably only the pre-bundled versions that needed to share a common root. There's a good chance it probably isn't necessary for the official Jack installer - IF - the official version modifies the user's PATH to show where it installed Jack.

Of course that's only the view from Mixbus's perspective... other apps might have evolved their own requirements too by now.

**Comment by x42** [comment]
> I think this was done deliberately (for Mixbus)

Ah that explains it. Thanks.
Back when Mixbus required JACK, there have only been 32bit builds of Mixbus.
So this was a workaround to get things going on when using Mixbus on 64bit systems.

The bug report still stands then, on a 64bit system, 64bit binaries should not be in "Program Files (x86)".

**Comment by falkTX** [comment]
Fixed in 1.9.15 release
