### ISSUE TITLE
Regression: can't start JACK after #592

### ISSUE THREAD

**Issue by terencode** [jackaudio/jack2#614]
Starting with d9f84dcca39e22653e92eadd45926d3982d58272 I'm unable to start JACK2 (dbus) on my usb soundcard (scarlet solo 2nd gen/) .
Here is what the log reports:
```
Sun Jul 12 19:40:07 2020: Listening for D-Bus messages
Sun Jul 12 19:40:30 2020: Starting jack server...
Sun Jul 12 19:40:30 2020: JACK server starting in realtime mode with priority 60
Sun Jul 12 19:40:30 2020: self-connect-mode is "Don't restrict self connect requests"
Sun Jul 12 19:40:31 2020: Acquired audio card Audio2
Sun Jul 12 19:40:31 2020: creating alsa driver ... hw:USB,0|hw:USB,0|64|3|48000|0|0|nomon|swmeter|-|32bit
Sun Jul 12 19:40:31 2020: configuring for 48000Hz, period = 64 frames (1.3 ms), buffer = 3 periods
Sun Jul 12 19:40:31 2020: ALSA: final selected sample format for capture: 32bit integer little-endian
Sun Jul 12 19:40:31 2020: ALSA: use 3 periods for capture
Sun Jul 12 19:40:31 2020: ALSA: final selected sample format for playback: 32bit integer little-endian
Sun Jul 12 19:40:31 2020: ALSA: use 3 periods for playback
Sun Jul 12 19:40:31 2020: ERROR: ALSA: poll time out, polled for 1030 usecs, Retrying with a recovery, retry cnt = 1
Sun Jul 12 19:40:31 2020: ERROR: ALSA: poll time out, polled for 1031 usecs, Retrying with a recovery, retry cnt = 2
Sun Jul 12 19:40:31 2020: ERROR: ALSA: poll time out, polled for 1034 usecs, Retrying with a recovery, retry cnt = 3
Sun Jul 12 19:40:31 2020: ERROR: ALSA: poll time out, polled for 1036 usecs, Retrying with a recovery, retry cnt = 4
Sun Jul 12 19:40:31 2020: ERROR: ALSA: poll time out, polled for 1033 usecs, Retrying with a recovery, retry cnt = 5
Sun Jul 12 19:40:31 2020: ERROR: ALSA: poll time out, polled for 1032 usecs, Reached max retry cnt = 5, Exiting
Sun Jul 12 19:40:31 2020: ERROR: JackAudioDriver::ProcessAsync: read error, stopping...
Sun Jul 12 19:40:36 2020: ERROR: JackPosixProcessSync::LockedTimedWait error usec = 5000000 err = Connection timed out
Sun Jul 12 19:40:36 2020: ERROR: Driver is not running
Sun Jul 12 19:40:36 2020: ERROR: Cannot open client name = dbusapi
Sun Jul 12 19:40:36 2020: ERROR: failed to create dbusapi jack client
Sun Jul 12 19:40:36 2020: Released audio card Audio2
Sun Jul 12 19:43:51 2020: Controller deactivated.
```

ArchLinux with linux 5.7.8

**Comment by fps** [comment]
Hi,

I think this change just exposes some other issues in the software. Maybe we should make the poll time out and the number of retries configurable via options..

**Comment by fps** [comment]
Hm, interesting. In your output you have a line:

<pre>
Sun Jul 12 19:40:31 2020: ERROR: ALSA: poll time out, polled for 1030 usecs, Retrying with a recovery, retry cnt = 1
</pre>

Your period time is 1.3ms. The poll timeout should really be (1.3 * 1.5)ms = 1.9ms. At least if I understand the code correctly here: https://github.com/jackaudio/jack2/blob/d9f84dcca39e22653e92eadd45926d3982d58272/linux/alsa/alsa_driver.c#L903

Oh, ok, the floor() rounds the 1.9 to 1ms. And that's what the poll is called with as timeout. The code is wrong anyways. Let's say we have a period size of 8 at 48khz sampling rate. That gives a period time of 0.16ms, even multiplied with 1.5 this gives only 0.25ms which would then be rounded down to 0ms. And that's a rather useless poll timeout.. 

But that's not the issue in your case. The driver polls for 1ms five consecutive times for a total of 5ms. So in 5ms the ALSA driver didn't return an event on the poll descriptors for 5ms and then the driver bailed out..

**Comment by fps** [comment]
What happens if you revert https://github.com/jackaudio/jack2/commit/4341f8086f795bdbb3203aa3046098ddef2f6651 on top of your HEAD? Is the regression still there?

**Comment by fps** [comment]
Another thing you could try would be to increase MAX_RETRY_COUNT to something like 5000. Maybe the alsa driver is just slow to start up and it will eventually return events on the descriptor..

**Comment by falkTX** [comment]
> Oh, ok, the floor() rounds the 1.9 to 1ms. And that's what the poll is called with as timeout. The code is wrong anyways. Let's say we have a period size of 8 at 48khz sampling rate. That gives a period time of 0.16ms, even multiplied with 1.5 this gives only 0.25ms which would then be rounded down to 0ms. And that's a rather useless poll timeout..

That is a very good catch! I will remove the floor there.

**Comment by fps** [comment]
This leaves us with float->integer conversion though. And I'm never sure what rules precisely apply. Maybe better replace the <code>floor()</code> with <code>ceil()</code>? Do we want to poll for *at most* 1.5 times the period time or for *at least* 1.5 times the period time? I have a hunch that it's *at least* 1.5 times the period time. In that case <code>ceil()</code> would be the right thing to use..

**Comment by falkTX** [comment]
hmm on those cases a `(int)(value + 0.5f)` will do the trick, without the need to call external functions.
I will add that in, seems much better to wait 1ms without result rather than miss timing by not having waited an extra 1ms

**Comment by fps** [comment]
For very small period sizes like, for example 8 frames per period, like in the above example <code>(int)(value + 0.5f)</code> will still round down to 0 causing a 0ms poll. So <code>ceil()</code> is really needed here. Or just adding 1.0f instead of 0.5, That would approximate <code>ceil()</code> pretty well..

But I'm not convinced that such a short poll timeout is really what we want. Do we want the alsa driver to die (and taking the server basically with it - it's non-functional after 5 consecutive poll timeouts happening) if the alsa driver fails to deliver buffers for such  a short amount of time?

Sure it's audible and it's a sign of something going on with the alsa driver, but maybe just dying with no way for the user to remedy the situation (making e.g. poll timeouts or the number of retrys configurable) might not be the best option going forward.

**Comment by falkTX** [comment]
the commit in question has been reverted.

would be nice to revisit this at some point and see how to the better wait time working for everybody..
but in any case, this specific issue is "fixed" as the old behaviour has been restored.
