### ISSUE TITLE
macosx/generate.pkg.sh Produces a Huge Installer.

### ISSUE THREAD

**Issue by jsl303** [jackaudio/jack2#622]
I built from source on MacOS.
```
python3 ./waf configure --prefix /usr/local
python3 ./waf
python3 ./waf install
```
Then I ran `./generate-pkg.sh /usr/local` inside macosx folder.
However, it generated pkg installer  that's almost 2GB.
How do I package only the ones you need?
Thanks!

**Comment by falkTX** [comment]
You need to use --destdir during install (to a temp dir), and then grab the relative usr/local from there.
That way the installer will have only JACK stuff.

btw, there are working installers at https://github.com/jackaudio/jack2-releases/releases
these include qjackctl application too.

Testing of that is really, really welcome.
I just need to create an uninstall script and tweak qjackctl things, and the macOS package will be complete.

**Comment by fdch** [comment]
Hi, I did the following to get the package built:
```
./waf configure --prefix /
./waf
./waf install --destdir installed
 ./macosx/generate-pkg.sh $(pwd)/installed
```

> btw, there are working installers at https://github.com/jackaudio/jack2-releases/releases
> these include qjackctl application too.

However, I downloaded and will try the latest release. Thanks for that.

**Comment by falkTX** [comment]
1.9.15 has been released and the installer ends up with the correct size.
