### ISSUE TITLE
Windows: JACK 1.9.11_64, if installed on the system, causes Mixxx 2.2.4 64-bit to crash on startup.

### ISSUE THREAD

**Issue by siana** [jackaudio/jack2#623]
Running on Windows 10 64-bit 20.04
repro:
Install latest Jack 64-bit release for Windows
Install latest Mixxx 64-bit release for Windows
Observe: Mixxx crashes on startup.
Uninstall JACK
Observe: Mixxx no longer crashes on startup.
The crash occurs during PortAudio initialisation in Mixxx, presumably while loading the ASIO driver provided by JACK. It doesn't matter whether JACK server is running or not.

A similar looking issue has occurred in FlexASIO version 1.4. It was remedied in version 1.5. PortAudio was chain loaded by FlexASIO, but because the DLL basename matched an already loaded module, but was not compatible, FlexASIO would crash. Is it plausible that the mechanism is similar at all? Corresponding issue https://github.com/dechamps/FlexASIO/issues/47

Potentially related issues:
https://github.com/rodrigodzf/Jack-Audio-For-Unity/issues/15
https://github.com/jackaudio/jack2/issues/393
https://github.com/jackaudio/jack2/issues/275
https://github.com/jackaudio/jack2/issues/332
https://github.com/jackaudio/jack2/issues/380
https://github.com/jackaudio/jack2/issues/351
https://github.com/corrados/jamulus/issues/93

It is actually completely untenable that a software causes a multitude of other applications to break so rampantly and with no connection obvious to the user. In my opinion, release should be nuked or only distributed with a visible warning.

**Comment by falkTX** [comment]
I did not notice this was so serious, thanks for bring that up (again).
So JackRouter is a problem on Windows, I guess for the upcoming binary releases it will be better to not install/ship-with it.

I just removed the (old) macos and windows links from the jackaudio.org download page, so, thanks.

Updated binaries are coming hopefully later this month, I am on the final steps for setting up the CI/CD.

**Comment by siana** [comment]
Let me know if i can help with anything at all! I'm thinking a NSIS installer can be built on Linux (though i never tried) so would NSIS script be a relevant task?

JackRouter is useful. I'll try to build the master and see whether the issue has potentially been resolved or whether i can fix it.

**Comment by falkTX** [comment]
I have used InnoSetup for another project, which seems very simple and easy to follow, it does pretty much all that is needed without complications.
So I think I will go with those.

Regarding JackRouter, help is appreciated for sure. I dont even know how to build it, but @sletz will have some ideas :)

**Comment by gnif** [comment]
NSIS is very simple, open-source, and builds on Linux. please use NSIS :+1: 

Here is an example we are using for the LookingGlass project which is used by a CI builder on a Linux system cross compiling for Windows.
https://github.com/gnif/LookingGlass/blob/master/host/platform/Windows/installer.nsi

**Comment by kmatheussen** [comment]
Maybe I've misunderstand what's happening, but I thought you had to register the JackRouter ASIO driver for it to work? Maybe mixx doesn't crash if you run the following command?

```
regsvr32 /U "C:\Program Files (x86)\Jack v1.9.8\64bits\JackRouter.dll"
```

**Comment by falkTX** [comment]
New builds now available. See https://github.com/jackaudio/jack2-releases/releases

Tested a bit with Carla in a VM, that works well.
![image](https://user-images.githubusercontent.com/1334853/93022099-f595c700-f5de-11ea-9c4e-3c44de2a22d6.png)

Bitwig also works, Ardour has a few issues. Zrythm developer will be doing testing today.

**Comment by falkTX** [comment]
@siana if you could please uninstall the previous jack version and install the one from https://github.com/jackaudio/jack2-releases/releases, that would be very appreciated.

qjackctl needs some tweaks so that it works better in windows, but at least we have things running now.

**Comment by kmatheussen** [comment]
I've just gone through a long debug session with a guy where portaudio crashed. It would probably be good to ensure this patch is attached (or at least somehow manage to compile portaudio with NDEBUG):

```diff -u a/src/hostapi/wdmks/pa_win_wdmks.c~ b/src/hostapi/wdmks/pa_win_wdmks.c
--- a/src/hostapi/wdmks/pa_win_wdmks.c~    2020-09-12 03:23:02.000000000 +0200
+++ b/src/hostapi/wdmks/pa_win_wdmks.c    2020-09-13 12:03:40.279668210 +0200
@@ -1058,6 +1058,5 @@
     }

     PA_DEBUG(("FindStartConnectionFrom: returning NULL\n"));
-    assert(FALSE);
     return 0;
 }
```

Also see my report to the portaudio list:
https://listserv.cuit.columbia.edu/scripts/wa.exe?A2=PORTAUDIO;7120129e.2009B&S=a

**Comment by kmatheussen** [comment]
Good work by the way. Finally.

**Comment by kmatheussen** [comment]
s/attached/applied/

**Comment by falkTX** [comment]
`-DNDEBUG` is set for these builds, so assertions like that are not triggered.
see https://github.com/DISTRHO/PawPaw/blob/master/setup/env.sh#L47

**Comment by kmatheussen** [comment]
Good. Have you tested it? Does it still work if you insert "assert(0)" into the top of that function?

**Comment by falkTX** [comment]
I did not test it, I do not know when that function is triggered. But the rule of `assert` being removed for builds with `NDEBUG` set tells me that it is not something to worry about.

**Comment by kmatheussen** [comment]
Because I tried to add -DNDEBUG to CFLAGS, and it didn't work. I had to remove the assert() line.

**Comment by kmatheussen** [comment]
That function should be triggered every time jack starts up if you compile portaudio with wdmks included in the "--with-winapi=" list. It is also triggered in qjackctl when you press the "Interface" combo box in Setup.

**Comment by falkTX** [comment]
Tried where and how? you need to have some compiler optimizations enabled too I think.
also depends if the project accepts C/XXFLAGS.

Anyway, I saw no crashes regarding that.
This qjackctl is not able to show the list of audio devices on windows, was that working at some point?

**Comment by kmatheussen** [comment]
Test it like this:
```
[kjetil@ttlush portaudio]$ diff -u src/hostapi/wdmks/pa_win_wdmks.c~ src/hostapi/wdmks/pa_win_wdmks.c
--- src/hostapi/wdmks/pa_win_wdmks.c~	2020-09-12 03:23:02.000000000 +0200
+++ src/hostapi/wdmks/pa_win_wdmks.c	2020-09-13 18:00:34.705336074 +0200
@@ -1047,6 +1047,9 @@
     unsigned i;
     const KSTOPOLOGY_CONNECTION* connections = (const KSTOPOLOGY_CONNECTION*)(filter->connections + 1);
     PA_DEBUG(("FindStartConnectionFrom: Startpin %u, Checking %u connections...\n", startPin, filter->connections->Count));
+
+    assert(0);
+    
     for (i = 0; i < filter->connections->Count; ++i)
     {
         const KSTOPOLOGY_CONNECTION* pConn = connections + i;

```

> Anyway, I saw no crashes regarding that.

I don't see any crashes either (when using an unpatched portaudio library), but for one Radium user it crashes every time. Removing that assert call fixed it. Adding NDEBUG didn't make a difference, don't know why, didn't really investigate either, but I reported it to the portaudio list.


> This qjackctl is not able to show the list of audio devices on windows, was that working at some point?

Yes, it's always been working as far as I know.

**Comment by falkTX** [comment]
> > This qjackctl is not able to show the list of audio devices on windows, was that working at some point?
> 
> Yes, it's always been working as far as I know.

well, it does not on the current qjackctl build. let me check if portaudio got disabled somehow.

**Comment by kmatheussen** [comment]
Also, this crash is not a single user problem. There are several hits when googling the crash. Both users of Python and Ardour have experienced crash because of that assertion in portaudio. It happens when probing soundcard interfaces.

**Comment by kmatheussen** [comment]
Here's my build of qjackctl: 
http://users.notam02.no/~kjetism/qjackctl.exe
It should display all interfaces.

**Comment by falkTX** [comment]
Found the issue, there is a typo in configure.ac, leading to portaudio being disabled in the build.

I tried adding some prints around the function that you want to test the assertion on, but it seems it is never triggered. I guess this build does not have the wdmks driver..?
ASIO, DirectSound, MME and WASAPI are there, should be enough of audio frameworks no? (and then people complain linux audio has too many of them lol)

Going to add -X winmme by default too, so we get the MIDI bridge.

**Comment by kmatheussen** [comment]
wdmks is supposed to be a very efficient driver type, but I don't really know. I just use ASIO and WASPI. Could be people who rely on it though, I don't know.

**Comment by kmatheussen** [comment]
Yes, I guess the portaudio build doesn't have wdmks driver. Again, don't know if it's needed.

**Comment by 3Rton** [comment]
> I did not notice this was so serious, thanks for bring that up (again).
> So JackRouter (the ASIO bridge) is a problem on Windows, I guess for the upcoming binary releases it will be better to not install/ship-with it.
> 
> I just removed the (old) macos and windows links from the jackaudio.org download page, so, thanks.
> 
> Updated binaries are coming later, I am on the final steps for setting up the CI/CD.

How is one supposed to install jack on win10 and use it now without the router? The installer from jack2 releases doesn't come with the router and I have no clue how to set up audio now. (Most guides including the one on Jacks website start with setting up the router via command line) 
Opening the GUI tool I can get the server to start with following Interface options: default and ASIO UMC 404 
However in neither I seem to be able to do anything. Is there anyone who has written a guide for installing on windows 10 post jackrouter removal and the 32-bit and 64-bit folders not being included in the installer anymore??

**Comment by falkTX** [comment]
You can use JACK by itself, with JACK-aware applications.

The list of that is not extensive for Windows, but we got at least:
- Ardour / Mixbus
- Bitwig Studio
- Carla (Plugin Host) [so basically any lv2, vst2, vst3 plugin as jack client is possible]
- PureData
- Radium
- Zrythm

**Comment by 3Rton** [comment]
Haa, I was going to use JACK to route audio for OBS recording but I guess with the jackrouter gone for now that isn't possible use case anymore. Is it still in the plans to include the router one day on windows side? 

As for the general setup Audacity is listed in the Jack aware apps page in the main website but it links to dead link for how to set it up. LMMS is also listed. But LMMS side native jack seems to only work on Linux (in their audio settings documentation Jack is listed as linux only while SDL and PortAudio are listed for Win) Though even then I think I'm doing something wrong. When I select my ASIO UMC 404 as my interface and start the server I get 4 system inputs and outputs but they don't seem to actually be anything but placeholders without being connected to any of my actual devices.
I don't suppose it will be on the priority list in near future either if the maintainer changed relatively recently but having some kind of updated windows set up guide would be nice. Trying to set this up has been pretty frustrating experience, even if it is mostly my own fault.

**Comment by falkTX** [comment]
noted. there are some resources out there already regarding setting up jack on windows, but a bit too spread out.
But the release is needed first, so everyone sees that jack is still being worked on and has plans for the future, this should help a few more applications giving support for it.
In the case of Audacity and LMMS, it should be pretty simple for them to enable jack support on windows. 

two good entry points for reading already:
https://libremusicproduction.com/articles/demystifying-jack-%E2%80%93-beginners-guide-getting-started-jack
https://ccrma.stanford.edu/docs/common/JACK.html

**Comment by kmatheussen** [comment]
On Thu, Oct 1, 2020 at 6:22 PM 3Rton <notifications@github.com> wrote:

> Haa, I was going to use JACK to route audio for OBS recording but I guess
> with the jackrouter gone for now that isn't possible use case anymore. Is
> it still in the plans to include the router one day on windows side?
>

In my opinion, the asio jack driver should be separated into a separate
project. It's a driver, so it might, and it already has, screwed up the
system for people, causing people to wrongfully blame jack, and people
wrongfully thinking that jack itself is some sort of asio driver.

**Comment by falkTX** [comment]
1.9.15 release no longer includes jack-router, so this issue can no longer happen (for new installs).

thanks a lot for the report, it was the kicker to get jack-router out of jack2 codebase, we needed that.

**Comment by marijncin** [comment]
> Let me know if i can help with anything at all! I'm thinking a NSIS installer can be built on Linux (though i never tried) so would NSIS script be a relevant task?
> 
> JackRouter is useful. I'll try to build the master and see whether the issue has potentially been resolved or whether i can fix it.

Hi, I am facing the exact same problem, but with MaxMSP. 
Did you manage to get a working version of jackRouter that does nog crash other applications? 

Greetings, Marijn

**Comment by dyfer** [comment]
@marijncin the 1.9.17 release includes JackRouter and AFAIU has this problem resolved.
