### ISSUE TITLE
Delay when sending MIDI to external hardware

### ISSUE THREAD

**Issue by TatriX** [jackaudio/jack2#631]
I have an Ardour project with a very simple MIDI track. It sends 4 notes in a loop to an external hardware drums and gets sound back. When head jumps to the begging of the loop, there is a noticeable (15ms) delay, probably related to panic send to the synth.

![2020-09-03-204823_1400x1544_scrot](https://user-images.githubusercontent.com/703150/92154893-d0f35f80-ee26-11ea-8f62-06a72b107559.png)

With help from the Ardour team we found out that this problem doesn't happen when using ALSA backend but happens with JACK1, JACK2 and pipewire-jack.

Ardour sends correct midi absolute timestamps: http://paste.org.ru/?rbwg9c

That's what `jack_midi_dump` shows, again looks ok: http://paste.org.ru/?cgci0i

And that's how recording of this looks: 
![2020-09-03-172316_2639x690_scrot](https://user-images.githubusercontent.com/703150/92155723-1c5a3d80-ee28-11ea-9bfd-31781c06b743.png)
notice a delay of 15ms at 01:00
![2020-09-03-202809_1251x969_scrot](https://user-images.githubusercontent.com/703150/92155773-2f6d0d80-ee28-11ea-8f1c-7b356ba15507.png)

Here's how it sounds: https://tatrix.org/public/delay-test-02.wav (it should be a steady bit instead)

Here's an example project, but this only happens with external hardware, not software synths.
[delay-test.zip](https://github.com/jackaudio/jack2/files/5170615/delay-test.zip)

And my JACK command line
```
jackd -ndefault -t 200 -p 2048 -R -X alsa_midi -d alsa -n 2 -r 48000 -p 128 -d hw:USB,0
```

Any help is appreciated!

UPD: it seems that when Ardour doesn't send panic messages, problem doesn't exist.

**Comment by falkTX** [comment]
Try using:
```
jackd -ndefault -t 200 -p 2048 -R -d alsa -n 2 -r 48000 -p 128 -d hw:USB,0 -X seq
```
The `alsa_midi` server option and `raw` alsa driver option are not ideal in terms of timing, the `seq` alsa driver option should have the same or equivalent timing results to a2jmidid (and I guess ardour as well)

**Comment by TatriX** [comment]
`a2jmidid` has the same problem, I forgot to mention

**Comment by TatriX** [comment]
> `jackd -ndefault -t 200 -p 2048 -R -d alsa -n 2 -r 48000 -p 128 -d hw:USB,0 -X seq`

Tried again (I also tried all combinations of alsa/midi/a2jmidid before that). Same issue ;(

**Comment by TatriX** [comment]
Sending twice as much midi messages in the end of the loop increase delay even more:
![2020-09-03-220402_893x709_scrot](https://user-images.githubusercontent.com/703150/92161942-a1962000-ee31-11ea-9c66-30bd5a02514c.png)

**Comment by TatriX** [comment]
Ok, so "ALSA raw-midi" in cadence has a delay, but this doesn't:
```
jackd -ndefault -t 200 -p 2048 -R -d alsa -n 2 -r 48000 -p 128 -d hw:USB,0 -X alsarawmidi
```
Though when bridging pulse, random delays still may happen.
It seems that this has the acceptable performance in my case:
``` $ pacmd
>>> load-module module-jack-sink channels=2
>>> set-default-sink jack_out
```
Thank you!
