### ISSUE TITLE
Failed to open server from jack_control even though jack and jackdbus are running from Jack1 forum

### ISSUE THREAD

**Issue by kiwi-ed** [jackaudio/jack2#632]
@ falkTX

"you are reporting this issue in jack1 repo. jack1 does not provide dbus support

in the case of jack2, jackd does not provide dbus support.
in order to use switch master and switch commands, you need to use jack_control to start jack, and completely ignore jackd as if it does not even exist.
(safest choice is to build without --classic)"

Thanks. Please clarify these points for me:
1) you mentioned ignore 'jackd' fine, and if jack_control starts 'jack' am I to assume 'jack' is another bin? Because jack_control is just a python CLI.
2) Inside jack_control it's totally DBus orientated so what is this talking too? Hence why I used jackdbus otherwise all I'm getting is DBus failures. 
3) Have I got the wrong jack_control somehow?

I do appreciate your help on this.    

EDIT:
Changing the build flag to just --dbus and running 'jackdbus auto' seems to work. Clearly jackdbus provides both the jack server and dbus comms together.

**Comment by falkTX** [comment]
>     1. you mentioned ignore 'jackd' fine, and if jack_control starts 'jack' am I to assume 'jack' is another bin? Because jack_control is just a python CLI.

the jack server can be in either jackd or jackdbus process.
but having jackdbus running does not mean that jack server is running.

jackdbus and jackd should never be running at the same time, as they manage the same thing - the jack server.
 
>     2. Inside jack_control it's totally DBus orientated so what is this talking too? Hence why I used jackdbus otherwise all I'm getting is DBus failures.

jack_control talks to jackdbus, and tells it to start and stop the server as needed.


>     3. Have I got the wrong jack_control somehow?

Really doubt it

**Comment by kiwi-ed** [comment]
Getting close now.  I can using the dummy driver play a track albeit silent, change rates, start stop the server etc. However when selecting alsa I get the following in the log. I know for a fact the alsa card is free. The asla card is a high-end USB DAC ( no mic/capture etc). The log states the handler is already registered and I assume this is what triggers the rest of the errors. There is defiantly no other jack type servers running, at the moment all is manually ran after boot. 

To start things:
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket
jackdbus auto &
python /usr/bin/jack_control start

log;
Fri Sep  4 13:11:06 2020: Starting jack server...
Fri Sep  4 13:11:06 2020: JACK server starting in realtime mode with priority 10
Fri Sep  4 13:11:06 2020: self-connect-mode is "Don't restrict self connect requests"
Fri Sep  4 13:11:06 2020: Acquired audio card Audio0
Fri Sep  4 13:11:06 2020: creating alsa driver ... hw:0|hw:0|1024|2|44100|0|0|nomon|swmeter|-|32bit
Fri Sep  4 13:11:06 2020: ERROR: ALSA: Cannot open PCM device alsa_pcm for capture. Falling back to playback-only mode
Fri Sep  4 13:11:06 2020: configuring for 44100Hz, period = 1024 frames (23.2 ms), buffer = 2 periods
Fri Sep  4 13:11:06 2020: ALSA: final selected sample format for playback: 32bit integer little-endian
Fri Sep  4 13:11:06 2020: ALSA: use 2 periods for playback
Fri Sep  4 13:11:06 2020: ERROR: cannot register object path "/org/freedesktop/ReserveDevice1/Audio0": A handler is already registered for /org/freedesktop/ReserveDevice1/Audio0
Fri Sep  4 13:11:06 2020: ERROR: Failed to acquire device name : Audio0 error : A handler is already registered for /org/freedesktop/ReserveDevice1/Audio0
Fri Sep  4 13:11:06 2020: ERROR: Audio device hw:0 cannot be acquired...
Fri Sep  4 13:11:06 2020: ERROR: Driver "alsa" cannot be loaded
Fri Sep  4 13:11:06 2020: ERROR: Segmentation Fault!
Fri Sep  4 13:11:06 2020: ERROR: info.si_signo = 11
Fri Sep  4 13:11:06 2020: ERROR: info.si_errno = 0
Fri Sep  4 13:11:06 2020: ERROR: info.si_code  = 1 (SEGV_MAPERR)
Fri Sep  4 13:11:06 2020: ERROR: info.si_addr  = 0x10
Fri Sep  4 13:11:06 2020: ERROR: Stack trace (non-dedicated):
Fri Sep  4 13:11:06 2020: ERROR: End of stack trace



As this is an embedded ARM system the DBus may not be correct due to no install scripts..
<busconfig>

  
  <policy user="root">
    <allow own="org.jackaudio.service"/>
    <allow own="org.freedesktop.ReserveDevice1.Audio0"/>
    <allow own="org.freedesktop.ReserveDevice1.Audio1"/>
  </policy>

  
  <policy context="default">
    <allow send_destination="org.jackaudio.service"/>
    <allow receive_sender="org.jackaudio.service"/>
  </policy>
</busconfig>


Thanks.

**Comment by falkTX** [comment]
You should not manually set DBUS_SESSION_BUS_ADDRESS or run jackdbus manually.
Let dbus session service take care of that.

In any case..

> Fri Sep 4 13:11:06 2020: ERROR: cannot register object path "/org/freedesktop/ReserveDevice1/Audio0": A handler is already registered for /org/freedesktop/ReserveDevice1/Audio0

This means the soundcard is already in use by something else.

**Comment by kiwi-ed** [comment]
OK, bear in mind this is a headless server with no x11 or GUI just a SSH terminal. If I run 'jack_control start' I get:
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead  

Hence why I added the export. What can be used to launch jackdbus then without x11?

Thanks.

**Comment by falkTX** [comment]
oh hmm that I dont know. is the dbus service running and working correctly? can you run some dbus introspection tool and actual get anything back?

**Comment by kiwi-ed** [comment]
Yea I use DBus for all sorts of things under the hood and they all work well. So I'm guessing the manual running of jackdbus has created a chicken-n-egg situation. With no x11 stuff I needed jacjdbus running to even get jack_control to talk to something ( it provided the org.jackaudio.service ) but then because as it was already started by doing a 'jack_control start' things blow-out due to the  /org/freedesktop/ReserveDevice1/Audio0 already being registered ( because I started jackdbus manually). Hmm..

I only ever use one connection at a time so maybe I should try jack1..

Cheers.

**Comment by falkTX** [comment]
You can also use jack2 without --dbus option.

**Comment by kiwi-ed** [comment]
Then does that mean I cannot use jack_control?

**Comment by kiwi-ed** [comment]
Cracked it!

xml:
 <engine>
  <option name="driver">alsa</option>
  <option name="slave-drivers">alsa</option>        <== removed // might be the cause for already registered..
 </engine>

The export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket    was need to tell the system that there's no x11

Added to /etc/dbus-1/system.conf:
<policy user="root">
     <allow own="org.freedesktop.ReserveDevice1.Audio0"/>
     <allow own="org.freedesktop.ReserveDevice1.Audio1"/>
</policy>


Added : /etc/dbus-1/system.d/jack-dbus.conf
<busconfig>
  
  <policy user="root">
    <allow own="org.jackaudio.service"/>
  </policy>

  
  <policy context="default">
    <allow send_destination="org.jackaudio.service"/>
    <allow receive_sender="org.jackaudio.service"/>
  </policy>
</busconfig>

Then doing:
jackdbus auto &
python /usr/bin/jack_control start

She's all good! Really appreciated your help - cheers.
