### ISSUE TITLE
Possibility of changing driver using client API

### ISSUE THREAD

**Issue by kiwi-ed** [jackaudio/jack2#633]
Hi,

I'm attempting to write an application similar to the jack_* (in example-clients) that includes change the driver from alsa to dummy. Is this possible using the client API? The only code I've come across that does this is within server_control.cpp which appears to be opening a server instance not a client as do the examples. The server_control.cpp also uses switch_master which I'd probably need as well.

My aim to switch various inputs (which is done) then at times change the driver to dummy or alsa.

Thanks!

**Comment by falkTX** [comment]
you cannot do this on the client side.

the current and only way to do this is over dbus.

**Comment by kiwi-ed** [comment]
OK, no problem. Can I then over DBus connect ports similar to jack_connect() in the client examples?  If so then everything can go via DBus.

Cheers.

**Comment by falkTX** [comment]
you can yes, a full patchbay can be implemented over dbus, with some limitations:
- no access to latency information
- no access to meta-data
- no transport control

and this is for managing connections only. you cannot do audio/midi processing over dbus.

**Comment by kiwi-ed** [comment]
Brilliant! I only want straight patching. Where would be the best place to get started - any example to lift/try code? There's no reference to patchbay in the jack_control,py 

Tar.

**Comment by falkTX** [comment]
I used to have some dbus related code before, but got rid of it because it was too limiting for my own case.
I can tell you, you are able to create a patchbay just using dbus, and also get some basic information about the running (or not) jack server, like buffer size, sample rate, RT on or off, etc.

Best recommendation I can give is to just use a dbus-instrospection tool, like qdbusviewer.
That way you can see which methods are available to call, and signals to listen to.
![Screenshot_20200907_195251](https://user-images.githubusercontent.com/1334853/92412436-cb0dbf00-f143-11ea-9c4a-0f3736243d20.png)

**Comment by kiwi-ed** [comment]
Yea was just doing that! Mine's CLI the hard way though being headless.. But your screen-shot has probably given me most of what I need to look for in the jackdbus dbus code now.  I'll hack up jack_control.py with some extras..

Thanks,

**Comment by kiwi-ed** [comment]
For anyone else who wants to connect stereo ports to jack via CLI DBus...

/* Get your ports */
dbus-send --system --dest=org.jackaudio.service --type=method_call --print-reply "/org/jackaudio/Controller" org.jackaudio.JackPatchbay.GetAllPorts
method return time=1599510177.029459 sender=:1.13 -> destination=:1.136 serial=158 reply_serial=2
   array [
      string "system:playback_1"
      string "system:playback_2"
      string "shairport-sync:out_L"
      string "shairport-sync:out_R"
   ]

/* Connect Left */
dbus-send --system --print-reply --dest=org.jackaudio.service /org/jackaudio/Controller org.jackaudio.JackPatchbay.ConnectPortsByName string:"shairport-sync" string:"out_R" string:"system" string:"playback_2"

/* Connect Right */
dbus-send --system --print-reply --dest=org.jackaudio.service /org/jackaudio/Controller org.jackaudio.JackPatchbay.ConnectPortsByName string:"shairport-sync" string:"out_L" string:"system" string:"playback_1"
