### ISSUE TITLE
Two second audio dropout after switchmaster and patching inputs

### ISSUE THREAD

**Issue by kiwi-ed** [jackaudio/jack2#634]
Hi,

I have a problem that after issuing a switchmaster ( after a device change etc ) reconnecting the inputs via DBus patchbay or a util such as jack_connect I get an annoying 2 second dropout in audio after initially starting. I have noticed in a few code examples a fixed 5 second delay after doing the switchmaster, surely this cannot be compulsory?

Thanks.

**Comment by falkTX** [comment]
might be the time needed to get the new device running and reconfigure all clients. this process can take a while

**Comment by kiwi-ed** [comment]
OK, just thought I'd ask. Cheers.

**Comment by kiwi-ed** [comment]
FYI - was the connecting application deciding to do a sound card flush before continuing the audio..
