### ISSUE TITLE
Guide for installing latest jack?

### ISSUE THREAD

**Issue by microfx** [jackaudio/jack2#636]
Hey!

The documentations are pretty hard to understand and incomplete for beginners (in terms of a real guide to install / configure). Are there good walkthroughs to install the latest jack? It's like I need to learn rocket science before using it. 

Cheers!

**Comment by falkTX** [comment]
Depends which platform/OS you use.

For windows/mac, there will be builds for them in the next release. For linux, it is impossible to write fully working steps because each distribution packages it differently.
Installing a system library like jack on top of distribution packages leads to issues, better to ask the official package maintainer to update it

**Comment by microfx** [comment]
Using latest Raspbian Lite with LXDE 

`JACK server starting in realtime mode with priority 75
self-connect-mode is "Don't restrict self connect requests"
Jack: JackPosixThread::StartImp : create non RT thread
Jack: JackPosixThread::ThreadHandler : start
Jack: playback device hw:pisound
Jack: capture device hw:pisound
Jack: apparent rate = 48000
Jack: frames per period = 128
Jack: JackDriver::Open capture_driver_name = hw:pisound
Jack: JackDriver::Open playback_driver_name = hw:pisound
Jack: Check protocol client = 8 server = 8
Jack: JackEngine::ClientInternalOpen: name = system
Jack: JackEngine::AllocateRefNum ref = 0
Jack: JackLinuxFutex::Allocate name = jack_sem.1000_default_system val = 0
Jack: JackEngine::NotifyAddClient: name = system
Jack: JackGraphManager::SetBufferSize size = 128
Jack: JackConnectionManager::DirectConnect first: ref1 = 0 ref2 = 0
Jack: JackGraphManager::ConnectRefNum cur_index = 0 ref1 = 0 ref2 = 0
Jack: JackDriver::SetupDriverSync driver sem in flush mode
audio_reservation_init
dbus_bus_request_name() failed. (1)
Failed to acquire device name : Audio2 error : Connection ":1.46" is not allowed to own the service "org.freedesktop.ReserveDevice1.Audio2" due to security policies in the configuration file
Audio device hw:pisound cannot be acquired...
Jack: ~JackDriver
Cannot initialize driver
Jack: no message buffer overruns
Jack: JackPosixThread::Stop
Jack: JackPosixThread::ThreadHandler : exit
JackServer::Open failed with -1
Jack: Succeeded in unlocking 82287136 byte memory area
Jack: JackShmMem::delete size = 0 index = 0
Jack: ~JackDriver
Jack: Succeeded in unlocking 1240 byte memory area
Jack: JackShmMem::delete size = 0 index = 1
Jack: Cleaning up shared memory
Jack: Cleaning up files
Jack: Unregistering server `default'
Failed to open server
`

Is this fixed in 1.9.14? This dbus is driving me nuts for ages...

**Comment by falkTX** [comment]
This is not something for jack to fix, something else is using the soundcard, and your user does not have permissions to request access to it.
So this is something to be fixed on the system level. Updating JACK will do nothing here

**Comment by microfx** [comment]
You were right... unplugged HDMI and now it starts. Thanks!

**Comment by microfx** [comment]
After removing HDMI and also the bcm device ... it's not working again.
