### ISSUE TITLE
ALSA cannot set period size on JACK startup 

### ISSUE THREAD

**Issue by DMario93** [jackaudio/jack2#639]
Little preface: I am a hundred percent new to audio routing, programming, etc so I apologize if what I am going to report as an "issue" is actually just the result of me being a noob.  

I'm trying to start a jack server on Linux (Fedora 32 for what it matters) using ALSA as the backend driver. It **always** fails, saying it cannot set the period size:

> JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
creating alsa driver ... hw:0|-|256|39|48000|0|0|nomon|swmeter|-|32bit
configuring for 48000Hz, period = 256 frames (5.3 ms), buffer = 39 periods
ALSA: final selected sample format for playback: 32bit integer little-endian
**ALSA: cannot set period size to 256 frames for playback**
ALSA: cannot configure playback channel
**Cannot initialize driver**
JackServer::Open failed with -1
Failed to open server

The user I am trying to start it with should have all the permissions required, since it was added to the group jackuser as specified [here](https://fedoraproject.org/wiki/JACK_Audio_Connection_Kit). I am also killing PulseAudio (or redirecting it - I tried two different ways with the same, negative result). 

On the [arch wiki](https://wiki.archlinux.org/index.php/JACK_Audio_Connection_Kit#Playing_nice_with_ALSA) I read that there are several bugs with alsa and alsa lib, so I might be asking for the wrong thing in the wrong place, but I guess it's worth trying. Also please note that on that wiki page there's a link to a forum [discussion](https://bbs.archlinux.org/viewtopic.php?id=250116) where people attempt to solve a _similar_ (might be the same) issue, however none of the proposed solutions work for me, including trying several combinations of frames, buffer and sample rate.

One last note, I git cloned, built and installed Jack2, but if I recall correctly the very same thing was happening with Jack1 which was installed through the official Fedora repositories. 

Thanks to anyone who'll help me

**Comment by miartad** [comment]
hi @DMario93, it could be an issue of your hw not being able to configure 256 frames per period.

Also, I have noticed you configured 39 periods, this might not be an issue, however 39 periods is quite a weird number of periods. Usually number of periods in audio buffer is 2 (minimal required number) or more (3,4), but 39 seems a bit high and uncommon at least to what I have seen in past.

output of:
```aplay -l```

could give more clarity on what hw you are running on

additionally you could experiment on your hw with command:
```cat /dev/urandom | aplay -D "hw:0,0" -c 2 -r 48000 -f S32_LE --period-size 96```

start with period size 96 and keep doubling the number, eventually you might get something that is supported by your hw and hear noise on the speaker output.

good luck

**Comment by DMario93** [comment]
hey @miartad, first of all thanks for your reply!

I tried experimenting directly with `aplay` as you suggested and.... wow it works! 

I am a bit confused however. I'd installed QJackCtl which would only let me set period size to multiples of 16. If I try to set it to 96 and then start Jack, QJackCtl will ignore it and try to start the server with a standard 256 which will fail on my hw. On the other hand, if I try to start the server through command line it works without any problem. 

But in general, how can I figure out which values will work for my hardware without bruteforcing all possible combinations? I'm trying to write a program for a friend who's a producer and might work on several machines with different hws, so I'd like my software to be smart enough to pick the right period size. How do you usually do that? Is there any standard way?

Anyway, I can definitely start a server now. I am going to check whether I can actually play or record some audio through it and then close this issue. 

Thank you very much again!

**Comment by miartad** [comment]
@DMario93 Im not familiar with qjackctl, but this seems like configuration issue, maybe you need to set a parameter or edit some config file when starting qjackctl to set the period size

to my knowledge, one does not simply query the supported period sizes for alsa device. when coding sw that interfaces with alsa-lib, you prepare a struct called snd_pcm_hw_params_t, where you would define your preferred parameters and their ranges (constraints), then you would call snd_pcm_hw_params for the opened audio device. this will try to apply parameters based on your constraints. once done you can query the actual chosen parameters for the device.

you can also use snd_pcm_hw_params_any to let the alsa negotiate whatever will work with the hw 

[1] https://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m___h_w___params.html#ga2fadb73803f58b900ac34846c14894ca
