### ISSUE TITLE
Jack_control won't accept a single char string as a byte (eps self-connect-mode won't work)

### ISSUE THREAD

**Issue by ovenwerks** [jackaudio/jack2#642]
Trying to set self-connect-mode will not work:

----------------------------8<-----------------------------
$ jack_control eps self-connect-mode e
--- engine param set "self-connect-mode" -> "e"
Traceback (most recent call last):
  File "/usr/bin/jack_control", line 400, in <module>
    main()
  File "/usr/bin/jack_control", line 283, in main
    configure_iface.SetParameterValue(['engine', param], python_type_to_jackdbus_type(value, type_char))
  File "/usr/bin/jack_control", line 46, in python_type_to_jackdbus_type
    return dbus.Byte(value);
TypeError: Expected a bytes or str of length 1, or an int in the range 0-255
-----------------------------------8<--------------------------------------

If I add line 279
                value = value.encode('utf-8')
Then it works as expected.

This seems to be a python 2 to python 3 error as python 2 had char strings and python 3 has unicode (int16) strings.

I do not know if this is the best solution though as there may be other settings that get passed as Byte, perhaps around line: 45?

**Comment by falkTX** [comment]
Try latest develop, this was fixed in https://github.com/jackaudio/jack2/commit/ba28ffa3db9af6e1a911d30135e95f3fdd50c1ba as far as I understand.

**Comment by ovenwerks** [comment]
Perfect. Thank you
