### ISSUE TITLE
SIGSEGV After last update (1.9.15)

### ISSUE THREAD

**Issue by Yrds** [jackaudio/jack2#646]
After the last jack2 update, some programs its giving segmentation fault when i launch it.

[patchmatrix.log](https://github.com/jackaudio/jack2/files/5393545/patchmatrix.log)
[qjackctl.log](https://github.com/jackaudio/jack2/files/5393546/qjackctl.log)

Edit 1:

System Info:

archlinux 5.8.14-zen1-1zen

Edit 2:

Patchage 1.0.2 seems to working fine.

Please let me know if you need more information.

**Comment by falkTX** [comment]
have you restarted the jack server since the update?
the default number of ports/clients being changed requires that.

**Comment by Yrds** [comment]
Yeah, i did a reboot after upgrade my packages.

This is the script which runs on every startup in my system(if this helps)

```
#!/bin/bash

jack_control ds alsa &
jack_control dps device 'hw:SB,0' &
jack_control dps rate 48000 &
jack_control dps nperiods 3 &
jack_control dps period 256 &
jack_control start &&
alsa_in -j mic -d "hw:Device" -r 48000 &&
exit 0
```

**Comment by falkTX** [comment]
I hope it is not related to the symbol-type change of the metadata properties...

2 checks to ask from you.

1. recompile of one the tools you are using, see if it fixes it right away (hopefully not)
2. build jack in debug mode, if that is possible, so we can get a nice backtrace of the crash

**Comment by falkTX** [comment]
note: if check 1 already passes (rebuilding gets a working application back), ignore the debug build

**Comment by Yrds** [comment]
Yeah, recompiling patchmatrix against jack2 make it work.

As mentioned in this [issue](https://github.com/OpenMusicKontrollers/patchmatrix/issues/13) only if recompiled against jack1 it giving the crash.

**Comment by falkTX** [comment]
thank you.

since old jack2 and also jack1 were using the style of headers before, we will have to keep them.
@wtay note this issue as pipewire changed the export metadata code too.

so this is pretty crucial... sigh, time to get a hotfix release going then.

**Comment by falkTX** [comment]
1.9.16 has been tagged, which fixes this.
