### ISSUE TITLE
jack_control doesn't run multiple commands

### ISSUE THREAD

**Issue by dj-foxxy** [jackaudio/jack2#652]
Our system that starts jack generates this;

```jack_control ds alsa dps device hw:K6 dpr capture dpr playback dps rate 44100 dps period 128 dps nperiods 2 dpr hwmon dpr hwmeter dpr duplex dpr softmode dpr monitor dpr dither dpr inchannels dpr outchannels dpr shorts dpr input-latency dpr output-latency dpr midi-driver epr name epr realtime epr realtime-priority epr temporary epr verbose epr client-timeout epr clock-source epr port-max epr replace-registry epr sync epr self-connect-mode epr slave-drivers```

`jack_control` used to run each subcommand, however, last night I noticed it would only run the first one then exit.

I'm I doing something wrong or is this a bug?

**Comment by falkTX** [comment]
Likely a regression.
