### ISSUE TITLE
JACK 1.9.16 win64 or win32 JackRouter.dll is missing

### ISSUE THREAD

**Issue by userdsp** [jackaudio/jack2#655]
There is no JackRouter.dll  inside C:\Program Files\JACK2 folder. How to register the JackRouter?

**Comment by falkTX** [comment]
jack router is unsupported at the moment, see https://jackaudio.org/news/2020/10/15/jack2-v1915-release-and-current-status.html

currently looking for new maintainers. do you volunteer?

**Comment by userdsp** [comment]
Yes I do

**Comment by falkTX** [comment]
Cool, see https://github.com/jackaudio/jack-router for the current code.

**Comment by userdsp** [comment]
After installing jack2-win64-v1.9.15.exe i'm still missing that file? What can cause this? Is not antivirus for sure. I need to use jackrouter at the moment :)

**Comment by userdsp** [comment]
Sorry i'm not a dev i can be a tester :D

**Comment by falkTX** [comment]
So, you misunderstood what a maintainer is then.
We need someone else to actually continue the work on jack-router, there is no one at the moment, so it was removed.
