### ISSUE TITLE
Jack library could not be loaded

### ISSUE THREAD

**Issue by andersvincent** [jackaudio/jack2#662]
I installed Jack 1.9.16 using the installer for macOS. After that I installed jacktrip 1.2.1 using the installer package for macOS.

I opened qjackctl and pressed start. After this I tried to execute jacktrip -s but I received the following error:

```
dyld: Library not loaded: /Library/Frameworks/Jackmp.framework/Versions/A/Jackmp
Referenced from: /usr/local/bin/jacktrip
Reason: image not found
```
I am running Mojave(10.14.6). I seem to not be the only one that has this problem, but the only other issue I found was related to homebrew, and I did not install Jack using homebrew. Is there any other build that potentially could fix this? Not much of a hacker myself. Help would be highly appreciated. Initially I thought this was a problem with jacktrip, but if I understand correctly the issue is that some library path has been changed in Jack maybe? Seems to be OS X specific.

**Comment by HaHeho** [comment]
Identical to https://github.com/jackaudio/jack2/issues/640.

**Comment by andersvincent** [comment]
Thanks HaHeho. I'll close this.
