### ISSUE TITLE
--help and --version return status code -1

### ISSUE THREAD

**Issue by C0nsultant** [jackaudio/jack2#663]
~I am currently preparing to add JACK2 to the official `homebrew-core` tap for OSX.~ https://github.com/Homebrew/homebrew-core/pull/63082
A simple test to check the reported version string using `jackd --version` fails since `print_version()` always returns [`-1`](https://github.com/jackaudio/jack2/blob/v1.9.16/common/Jackdmp.cpp#L256).
Same thing goes for `jackd --help` as it is treated as a [server failure](https://github.com/jackaudio/jack2/blob/v1.9.16/common/Jackdmp.cpp#L504) and returns the default return code [`-1`](https://github.com/jackaudio/jack2/blob/v1.9.16/common/Jackdmp.cpp#L325).

If you don't have any objections, I will change both cases to `0` since they are no failures.

**Comment by falkTX** [comment]
sounds good to me, specially the part the of "I will change". PR is welcome, thanks :)
