### ISSUE TITLE
Could not start JACK. Sorry.

### ISSUE THREAD

**Issue by jmar83** [jackaudio/jack2#674]
22:08:35.837 jackstart.exe -S -dportaudio -d"ASIO::ASIO4ALL v2" -c2 -r44100 -p1024
22:08:35.858 Could not start JACK. Sorry.

why?

**Comment by falkTX** [comment]
Where is this `jackstart.exe` coming from?
What version of jack are you using?

In any case, you can use `-v -dportaudio` to get more details, attention to the `-v` switch for verbose mode.

**Comment by jmar83** [comment]
I've got it from that obsolete users guide:
https://ccrma.stanford.edu/software/jacktrip/windows/index.html

(screen shot is from another version, number fo tabs is not the same)

and i already installed it a few weeks ago, then uninstalled it. after installing again (tody), that issue occured.

maybe there is a problem with dante VIA & dante controller. (i'm trying different solutions for audio tramsmission - commercial and open source ones)

**Comment by falkTX** [comment]
that version of jack is unsupported.
please uninstall and use the one from https://jackaudio.org/downloads/

**Comment by jmar83** [comment]
same problem. how to reset all settings to dafault? does it leave some user-defined settings (e.g. in user profile dir or registry) they will not be deleted on uninstallation?

**Comment by jmar83** [comment]
same message when i use fender asio instead of asio4all... same message an all other devices too...

**Comment by lucianoiam** [comment]
I got that error trying to start latest jackd with an old version of JackRouter installed. Old JACK uninstaller should remove JackRouter but cannot recall if that is the case, try with these manual cleanup steps:

- Locate the path to JackRouter.dll on disk, if found open an Administrator command prompt and run:

```
cd c:\path\to\jackrouter.dll   (change to path found in previous step)
regsvr32 /u jackrouter.dll
```

- Delete this key from registry: `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\ASIO\JackRouter`

- Start JACK

**Comment by jmar83** [comment]
thx.

there is not file like that after uninstall current version. and also no registry entry "JackRouter". So that things will be uninstalled fine.

still the same issue after install it again...

**Comment by jmar83** [comment]
reboot does also not help

**Comment by lucianoiam** [comment]
it does not seem to be the installation itself, but honestly no idea, without verbose messages it is difficult to know

**Comment by jmar83** [comment]
ok thx. however. will try the next open source solution..

**Comment by jmar83** [comment]
problem is still pendent, so thanks in advance for any feedbacks.

with kind regards,
jan
