### ISSUE TITLE
jack audio on Mac 10.12.6 Sierra

### ISSUE THREAD

**Issue by goliath49** [jackaudio/jack2#681]
Hello,
I have the same problem as kakyoism in https://github.com/jackaudio/jack2/issues/509, except that I am using Sierra (10.12.6):
After launching jackd, I open Reaper and Jamulus (according to what I see in forums, both are supposed to be compatible with jack, right?), but "When I open my Patchbay and try to add sockets, all I get is system", and in the list of soundcards of both Reaper and Jamulus, I don't see anything related to jack...
I tried first with "homebrew install jack", then uninstalling it, and then compiled from sources found here -> same problem.

**Comment by falkTX** [comment]
That is expected, jack-router no longer works on new macOS and is currently unmaintained anyway, so it was removed from the project
