### ISSUE TITLE
Possible broken compatibility of JACK 2 (64 bits) against Jack Router (32 bits) on Windows

### ISSUE THREAD

**Issue by platform-717** [jackaudio/jack2#682]
Hello,

I installed the latest 64 bits version of JACK 2 from [jack2-releases](https://github.com/jackaudio/jack2-releases/releases/download/untagged-e843b85e6b6f359a745a/jack2-win64-ac62faa9c0268b89e3ea23c0318227612acd8079.exe). I also copied the latest Jack Router files from [jack-router](https://github.com/jackaudio/jack-router/tree/main/binaries) and then I registered the DLLs using:

```
regsvr32 "C:\SomeLocalPath\jack-router-binaries\win32\JackRouter.dll"
regsvr32 "C:\SomeLocalPath\jack-router-binaries\win64\JackRouter.dll"
```

All my audio apps can then see the JackRouter ASIO interface, but **only the native 64 bits ones can actually use it**, so connect to JACK 2.

Example of 64 bits apps which are able to connect: Ardour, VB-Audio's VoiceMeeter Potato x64.

Example of 32 bits apps which are no longer able to connect: VB-Audio's ASIO Bridge, VoiceMeeter etc., but also others. All these apps work fine, for instance, with JACK 1.9.11 and Jack Router that comes bundled with it.

I tried to use the latest JACK 2 but to register the 32 bits version of _JackRouter.dll_ grabbed from 1.9.11. Again, it didn't work.

The last thing to mention is that for the above tests I only had a single version of JACK 2 installed at any given moment.

Any suggestion about which the problem can be?

Many thanks!

**Comment by falkTX** [comment]
Those binaries need to be rebuilt
someone was nice enough to do the 64bit version, 32bit one still untouched
see https://github.com/jackaudio/jack-router/pull/4

basically jack-router is unmaintained now, so got removed from jack2 and put in separate repo.
still waiting/asking for someone to step up for that, thanks

**Comment by platform-717** [comment]
Thanks, I was able to build myself in VS 2019 and it works!

I don't have access to push my branch unfortunately. The changes are simple, just add the x86 configuration lines in _.sln_:

```
GlobalSection(SolutionConfigurationPlatforms) = preSolution
	[...]
	Release|Win32 = Release|Win32
EndGlobalSection
GlobalSection(ProjectConfigurationPlatforms) = postSolution
	[...]
	{08E8BE85-76F9-4070-B85E-0CA6A38BCBB4}.Release|Win32.ActiveCfg = Release|Win32
	{08E8BE85-76F9-4070-B85E-0CA6A38BCBB4}.Release|Win32.Build.0 = Release|Win32
```

Then in _.vxproj_ add "PSAPI_VERSION=2;" at line #184 (perhaps this doesn't matter, but just to be like in the case of x64):

`<PreprocessorDefinitions>WIN32;NDEBUG;_WINDOWS;PSAPI_VERSION=2;%(PreprocessorDefinitions)</PreprocessorDefinitions>`

Last thing and the most important add a new line after or before #271:

`<Library Include="C:\Program Files\JACK2\lib32\libjack.dll.a" />`

That's all! 👍

**Comment by lucianoiam** [comment]
Maybe you can create a PR?

**Comment by falkTX** [comment]
Yes, a pull-request will be very welcome. Please update the 32bit binary while at it.

**Comment by platform-717** [comment]
OK, I will try to fork and create a PR then.

**Comment by falkTX** [comment]
This is already handled in 1.9.17, and we have 1.9.18 as of today.
