### ISSUE TITLE
Using MAD (merging audio driver) with jack. 

### ISSUE THREAD

**Issue by StudioOnno** [jackaudio/jack2#698]
Hi, 

Has anyone attempted to use the MAD driver? 
If I could send / receive audio streams from and to MAD that would be absolutely perfect. 

Greetings, Marijn 

mad driver
[https://www.merging.com/products/merging_audio_device](url)

**Comment by falkTX** [comment]
Is it just me, or this feels like trying to promote something?

JACK-Router is coming back in v1.9.17 release, so there is no need for this (from my quick glance at it)

Discussions are preferred on the mailing list.
Thanks for understanding.

**Comment by StudioOnno** [comment]
@falkTX 

Hi, I can ensure you I am not trying to promote anything, nor do I work for merging. I am just trying to figure out if it is possible to send audio from jack to mad.. that's all. The link was just there for information.

cheers.

**Comment by falkTX** [comment]
Alright, it just seemed too suspicious as your github account had no other activity.

In any case, it is the first time ever to hear of such thing. On Windows JACK can talk to ASIO drvers, so maybe that works?

**Comment by StudioOnno** [comment]
Hi, I removed the link from my post. 
I don't use GitHub a lot. as I am not really a developer but a sound engineer.  I just use jack, and absolutely love it so far. I 

My goal is to stream jack to aes67 to be send to IP loudspeakers. 
yes, ASIO drivers! I tried Dante virtual VS but it didn't work. I thought I might have better luck with MAD.

**Comment by falkTX** [comment]
I see, my apologies.

I saw your attempt to post on the mailing list, but you need to register there first before you can post.
It would be otherwise useless to post there, as you would not get any replies back to your mailbox.
