### ISSUE TITLE
[bug] jack_cpu_load produces inconsistent values with Reaper under Wine

### ISSUE THREAD

**Issue by wtangerine** [jackaudio/jack2#70]
Steps to reproduce:
1. Load Reaper under Wine, create an empty project
2. Create 1 audio track
3. Add JS:Tonegenerator (built-in Reaper FX) to the track FX, make it produce some signal
4. Add ReaFir (built-in Reaper FX) to the Master Track, select 32768 for FFT Size
5. Open Reaper's Performance Meter (Ctrl+Alt+P), jack_cpu_load in a console window
(Options->Preferences->Audio->uncheck "Close audio device when stopped and application is inactive", in order to make Reaper process audio when switching to a different window)
6. Compare values in Reaper's Performance Meter vs jack_cpu_load. In my case, Reaper shows 1.80% CPU, jack_cpu_load shows 3.4% load. That's about in the same ballpark.
7. Move ReaFir from the Master track to track no. 1, after tonegenerator (ctrl+alt+mouse drag-n-drop)
8. Compare the values. They should be the same as before, as essentially the processing chain did not change. In my case, Reaper still shows the same 1.80% CPU. jack_cpu_load shows only about 0.63% load.
9. Duplicate ReaFir 4 times, to have 5 sequential ReaFir plugins in the FX chain on track no. 1 (ctrl+drag)
10. (on my machine) Reaper shows about 7.6% CPU, jack_cpu_load shows only about 0.68% load.

Conclusion: with wine/Reaper,  jack_cpu_load calculates load correctly when FX are on the Master track, fails to calculate correctly when FX are on the Audio Tracks.

Measured with Reaper x64, "Net" driver for Jack2, Buffer Size of 2048. Wine compiled from the latest git, with "wine-rt" patches.

Verified similar behavior with Reaper x86, "Alsa" driver for Jack, Buffer Size of 512, with wine-rt from KXstudio-repositories, with and without wine-rt initialized.

**Comment by 7890** [comment]
Hi, I will close this issue for the following reasons:

-Inactive for some time
-Involves units such as Wine and Reaper, making it harder to reproduce
-The issue could not be presented as a compact, JACK-only case

However if you think this is still an issue, please feel free to open a NEW issue. Thanks for caring about JACK!
