### ISSUE TITLE
Clarify supported Windows versions and close old issues about Windows XP

### ISSUE THREAD

**Issue by szszoke** [jackaudio/jack2#701]
Hello!

In order to keep the list of issues smaller and more straightforward I propose to define a list of supported Windows versions, then we can close some of the issues that were opened 4+ years ago with no updates.

We could have Windows 10 as a supported Windows version for now and then collect reports about other versions.

Based on the currently open issues, it seems that Jack2 is not running on Windows XP anymore.

**Comment by falkTX** [comment]
There is nothing special in jack2 that prevents old windows version support.
The main question is... do we care?

**Comment by szszoke** [comment]
Whether we care or not is in limbo right now.

We should have a list of Windows versions where the official binary installed through the official installer is expected to work.

Then we could establish the list of Windows versions that we care about.

If there is a need for official support for an EOL Windows version, somebody could step up and be responsible for the extra workload.

If there is nobody to step up then maybe supporting an EOL Windows version is not that pressing after all.

**Comment by falkTX** [comment]
The current 32bit version should work on windows XP, but needs testing.
A CPU with SSE2 instructions is needed, but I think that is it.

Does microsoft still give VM images to try? I can do that with a win xp one just to see if it works or not.

**Comment by szszoke** [comment]
I think there is Windows XP Mode for Windows 7 but I don't know about free VM images.

Last time I dealt with Windows XP images, I could download them for work, but my employer was a Microsoft partner at the time.

**Comment by szszoke** [comment]
Another option would be to find someone who daily drives a Windows XP machine.

**Comment by falkTX** [comment]
hmm Windows 10 only go as far as "Windows 7" in the compatibility mode.
I think that is good enough in terms of supported version then.

I will add this info to the downloads. XP will in theory work there, but it is untested, so better mention Windows 7 minimum.

**Comment by szszoke** [comment]
Sounds good to me. Then we can clean out some of the issues that mention Windows XP and are several years old.

**Comment by falkTX** [comment]
Fixed in https://github.com/jackaudio/jackaudio.github.com/commit/df068c72f82258e5417c6e485d31bfc4c035452a
