### ISSUE TITLE
Not a bug but question. Jack_control stopped working and I had to install jack2-dbus

### ISSUE THREAD

**Issue by rhysday** [jackaudio/jack2#716]
Just curious what happened here. I've been running a pulse to jack to alsa audio setup for awhile now. I had jack2 installed but never jack2-dbus. Now for my setup to work I need it. Did something change? I'm running latest Arch build.

**Comment by rhysday** [comment]
For my audio setup I would always install realtime-privileges, jack2, lib32-jack2, python-dbus, pulseaudio-jack, alsa-plugins...and now jack2-dbus.

**Comment by falkTX** [comment]
There was a regression in v1.9.16 that made jack_control only run the first command.
This was fixed in v1.9.17. Is arch up to date yet?

**Comment by rhysday** [comment]
Yea I have 1.9.17-2 installed

**Comment by rhysday** [comment]
I uninstalled jack2-dbus to see if it would work without but no dice.

**Comment by dvzrv** [comment]
@falkTX I believe @rhysday is referring to packaging actually.

As discussed on IRC I have split jack2 into jack2 and jack2-dbus (the latter providing the dbus related activation such as jackdbus, jack_control and the dbus service itself). This has been announced on Arch Linux' pro-audio mailing list, too: https://lists.archlinux.org/pipermail/arch-proaudio/2021-January/000341.html

@falkTX Seeing that questions do pop up from time to time, would it be useful to also provide a question template for the github issues?

**Comment by falkTX** [comment]
tbh questions should go into the community part of jack, https://jackaudio.org/community
asking questions here sorta pollutes the issue tracker.

**Comment by dvzrv** [comment]
@rhysday if you are using dbus activation and rely on e.g. cadence or jack_control, then it is correct to install jack2-dbus (cadence actually pulls jack2-dbus in as a fixed dependency).

**Comment by dvzrv** [comment]
@falkTX fair point and I anticipated that answer ;-)

I can try to add this info to the README in a pull request so that it becomes clear also from browsing this repository. The information about where to ask questions can also be added to the inline comments in the existing issue templates. I forgot to do that.

As is, this ticket can be closed.

**Comment by rhysday** [comment]
Ah I use Carla and Non-mixer for my interface so don't think they would pull the package. 

Sorry about posting it here. But thank you for the answers... I will follow the arch pro audio mailing list :-)
