### ISSUE TITLE
Unable to register the DLL/OCX: RegSvr32 failed with exit code 0x3

### ISSUE THREAD

**Issue by marijncin** [jackaudio/jack2#718]
I am just trying to install the latest version of jack, including jackRouter. 

I get this message: 
![error jack](https://user-images.githubusercontent.com/43089382/106271940-16a13200-61e5-11eb-9875-0f748e0b2d06.PNG)

## Describe the bug

Error on installation: installing as admin, or not does not make a difference
I even tried it with a fresh copy of windows 10, same bug. 

Registry failed

## Environment

* **JACK Version:** Which version of jack2 are you using? (e.g. the output of `jackd --version` or a git commit checksum)
* **Operating System:** What operating system or distribution in which version are you using? (e.g. Linux, macOS, Windows)
* **Installation:** How did you install jack2? (e.g. package manager, from source)

## Steps To Reproduce

```bash
# Paste a minimal code example here (e.g. about how you started JACK)
```

### Expected vs. actual behavior

A clear and concise description of what you expected to happen vs. what happened.
I would expect jackRouter to register.

**Comment by falkTX** [comment]
Why did you close this? Did you solve it?

**Comment by marijncin** [comment]
Hi FalkTX, 

I resolved the problem by manually registering jack using the command prompt. But, the installer still gives this error.

**Comment by ReeseWang** [comment]
Hi @marijncin ,
Could you provide the command line to register the DLLs?

**Comment by SynthiaPayne** [comment]
Follow these steps to register jackrouter.dll

Open a command window:
Type: regsvr32 "C:\Program Files (x86)\Jack\64bits\JackRouter.dll"

- be sure to substitute the name of your directories if they are different
- should return “registration successful” message

- if registration is unsuccessful, run unregister command below, then 
run #1 above

regsvr32 -u "C:\Program Files (x86)\Jack\64bits\JackRouter.dll"

synthia

**Comment by ale-rinaldi** [comment]
Hello, I had the same issue and the above suggestions did not work for me: even the manual registration gave me a generic error.

Turned out I just needed to install the Visual C++ Runtime, that can be found on https://docs.microsoft.com/it-IT/cpp/windows/latest-supported-vc-redist?view=msvc-170 (the first section, named "Visual Studio 2015, 2017, 2019 and 2022"). I downloaded and installed both the 32bit and the 64bit versions, just to be sure, and then the setup correctly registered the DLLs.

Maybe this dependency should be specified in the download instructions for Windows, I can't seem to find anything about it on the web.

**Comment by lucianoiam** [comment]
Newer installers like 1.9.21 place Jack2 and JackRouter files in a different folder.
This fixed the issue for me on a Windows 7 box:

`regsvr32 "C:\Program Files\JACK2\jack-router\win64\JackRouter.dll"`

**Comment by zbynekdrlik** [comment]
Some issue today. Windows 11 Pro.

**Comment by zbynekdrlik** [comment]
After installinf https://aka.ms/vs/17/release/vc_redist.x64.exe, manual registration has been sucessfull.

**Comment by sanikovich** [comment]
Fix steps:

Install both Visual C++ 2010 Redistributables:
[vcredist_x86.exe](https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe)
[vcredist_x64.exe](https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x64.exe)
