### ISSUE TITLE
Need to request mic permission on macOS

### ISSUE THREAD

**Issue by falkTX** [jackaudio/jack2#724]
Reported on IRC, on macOS Catalina, jackd started via qjackctl cannot access microphone.

The fix involves adding microphone permission request in the Info.plist file, as done in https://github.com/Ardour/ardour/commit/acbccc1febb78cc0badf0b4c1f4d16f763f18bab for example.

This is just a reminder so I don't forget to add this in for next release.
Carla will need something similar.

**Comment by dyfer** [comment]
I wanted to help fixing this, but I realized that I don't know where you build QJackCtl... could you point me to the right direction? I thought that maybe I just need to add it to [c_osx.py](https://github.com/jackaudio/jack2/commit/9e645b9d6916a374ea8388fc4d6acf26cc0cf337), would that be so? Or does that need to be added upstream to QJackCtl?

**Comment by falkTX** [comment]
That part is done in https://github.com/jackaudio/jack2-releases, with https://github.com/DISTRHO/PawPaw being the project behind it.
Likely needs some tweaking around https://github.com/DISTRHO/PawPaw/blob/master/pack-jack2.sh#L108

**Comment by dyfer** [comment]
I was just looking at that. At which step is that plist file created? Is this in [macdeplyqt](https://github.com/DISTRHO/PawPaw/blob/master/setup/functions.sh#L645), called from https://github.com/DISTRHO/PawPaw/blob/master/pack-jack2.sh#L105 ? Not sure if I can recreate this setup locally, so trying to figure out when the actual application bundle is being created. Is it part of QJackCtl build itself or does it happen later?

**Comment by falkTX** [comment]
I do not recall, but I think macdeplyqt is the one that takes care of this.

**Comment by falkTX** [comment]
Now handled, will be part of 1.9.19 release
