### ISSUE TITLE
Jack2 Upgrade from 1.9.11 to 1.9.17 failed

### ISSUE THREAD

**Issue by keithfinnie** [jackaudio/jack2#729]
## Describe the bug

jack2 not removed after attempt to remove using .

## Environment

JACK Version:**  1.9.11
Operating System:** MacOS Big Sur
* **Installation:**  package manager

## Steps To Reproduce
standard MacOS 'drag to trash'

### Expected vs. actual behavior

Expected jackd 1.9.11 plus qjackctl to be fully removed. Qjackctl remained in Apps folder. /usr/local/bin/jack* files remained.

No error messages

### Subsequent attempts
* Contacted Tim Renner to obtain Beta removal tool
* Attempted "sudo locate" to list locations of jack files. Itwould not run due to permissions. (owner has no passwords set for admin or personal account). 
* From the command line, jackd --version showed  1.9.11
* Qjackctl V 0.3.6 in the apps folder started and ran. 'Messages' window showed jackd started. 'Connections' showed system in/out present.
* ps -ax | grep jack showed jackd process running.
* Ran qjacktrip 1.3.0. Upon 'Connect' button press, gave error pop-up saying jackd not started. 
* Ran freeware AppCleaner and emptied trash. jackd 1.9.11 still installed. 
* Downloaded jack2-clean-slate-osx. MacOS refused to run the install without required MacOS permission changes. Done.
* Subsequently  /usr/local/bin/jackd --version showed 1.9.17 
* qjackctl not showing installed in Apps folder.
* Ran jackd from command line and it worked successfully with qjacktrip.

### Issue remaining
find qjackctl and place in Apps folder.

**Comment by falkTX** [comment]
This is unsupported.

The new installer specifically states in its intro page:
```
Please note that this package will not delete previously installed jackosx contents.
If you used that before, please run its own uninstaller before installing this package!
```

qjackctl is not installed by default, its app bundle is directly inside the tarball you download for macOS.
Not everyone likes qjackctl, and it is not necessary to use JACK, so its app bundle is there just as convenience. (worth noting that qjackctl is not part of the jack project as well)

**Comment by keithfinnie** [comment]
OK, Thank you.
