### ISSUE TITLE
Jack Package for OS X refuses to install on Yosemite (10.10); Claims my OS X is too old

### ISSUE THREAD

**Issue by Someguy123** [jackaudio/jack2#73]
When installing Jack2 on the latest Yosemite 10.10 GM3, I get the following error which is clearly wrong:

    This 64/32 bits package can only be installed on Snow Leopard and later systems

Screenshot:
![OSX too old](http://i.imgur.com/SqwOl8z.png)

**Comment by rafmagana** [comment]
I've having the same problem :(

**Comment by rafmagana** [comment]
Confirmed "Mixed 64/32 bit, 0.90 of JackOSX for Snow Leopard" is working in Yosemite. Thanks.

**Comment by OrangeK** [comment]
I tried it just now in El Capitan, and it warned me about the software being out of date, and that it might harm my computer. Is there an easy way for me to install the newest version instead of maybe an old one?

**Comment by sletz** [comment]
You can use the latest JackOSX 0.92 package from here 

https://dl.dropboxusercontent.com/u/28869550/JackOSX.0.92_b1.zip

St�phane

Le 14 nov. 2015 � 05:03, Orange Karpusi <notifications@github.com> a �crit :

**Comment by klauskobald** [comment]
Is there a way to get a 64bit compatible Jack-insert.vst Plugin?
The above Package only contains an old 32 bit version from 2009.
Thanks!

**Comment by cerw** [comment]
https://dl.dropboxusercontent.com/u/28869550/JackOSX.0.92_b1.zip dead :(

**Comment by sletz** [comment]
https://dl.dropboxusercontent.com/u/28869550/JackOSX.0.92_b3.zip

Le 22 mars 2016 � 03:30, Petr Cervenka <notifications@github.com> a �crit :

**Comment by patrickhartono** [comment]
Hi guys any link to Jack for el capitan?

**Comment by F1LT3R** [comment]
Same problem on Siera. Does anyone have a build that works for Siera?

**Comment by sletz** [comment]
https://dl.dropboxusercontent.com/u/28869550/JackOSX.0.92_b3.zip

**Comment by velenoise** [comment]
This last link seems to be dead already. Does anybody has it updated?

**Comment by falkTX** [comment]
can we stop using dropbox for software releases please?

**Comment by sletz** [comment]
Where can we put the OS X binary?

**Comment by velenoise** [comment]
My 2 cents would be to have it on the Releases page, along with the source code zips

**Comment by falkTX** [comment]
yes, github releases are perfect for this.

**Comment by adridp** [comment]
is there already any working link for this?

**Comment by mseeber** [comment]
Yes, here you go:
https://github.com/jackaudio/jackaudio.github.com/releases

I'd rather have it on the releases of the jack2 repo but better than nothing.

**Comment by adridp** [comment]
Thanks a lot! I was starting to think it was not any longer available.
