### ISSUE TITLE
Autoconnect to custom port (self connect)

### ISSUE THREAD

**Issue by BlueMax** [jackaudio/jack2#731]
## Summary

There are 4 autoconnect modes in Jack2. The 'default' mode ("don't restrict") always connects to 'system' port.
Allow customization of 'autoconnect' (self connect) to a custom port instead of 'system' port only. 
This helps to control erratic port behavior (register/unregister) of some apps that are otherwise not controllable by external autoconnect tools.
```
   [ --autoconnect OR -a <modechar>]
     where <modechar> is one of:
       ' ' - Don't restrict self connect requests (default)
       'E' - Fail self connect requests to external ports only
       'e' - Ignore self connect requests to external ports only
       'A' - Fail all self connect requests
       'a' - Ignore all self connect requests
```
### Basic example

`$ jackd --autoconnect 'x42-dpl - Digital Peak Limiter Stereo'`
Target taken from `jack_lsp -c`.

### Motivation

There are jack apps that register/unregister their ports dynamically like `ALSA Jack plugin, Firefox/IPC, WineASIO/Winamp`. They appear/disappear a lot depending on if audio is played or similar. It can happen that the ports are visible but not connectable or only connectable when audio is actually streamed. This makes it mostly impossible to autoconnect (e.g. with `qjackctl/patchbay`).
The best way is to let the apps autoconnect all by themselves. The problem is they always connect to the 'system' port that is not always the best choice. If you have a fancy audio graph set up in `Carla` you obviously want the audio to be fed at the beginning of the graph not at the end (system port).

**Comment by satchnut** [comment]
Surprised this hasn't gotten more love. Customizable port self-connect is sensible and would make JACK tremendously more convenient to use. 

In a basic scenario, the health of your speakers and ears demands the presence of an active clipper/limiter at the end of your signal chain _at all times_, and _definitely_ by default. JACK's default method doesn't allow for this, leaving applicable users to either mess around in the patch bay every time he opens an audio app, or risk damaging his ears/speakers.

I know Linux allows this when used simultaneously with PipeWire, but that isn't a practical workaround for those not wishing to use PipeWire (or Linux).

**Comment by nedko** [comment]
@satchnut  As author of the jackaudio server autoconnect feature I have to say that I always run in 'e' mode and with ladish [1]. ladish aims to support jack client/port subgraphs, via studio connected to rooms via jmcore (jack multicore aka snake) room paradigm. It also handles connections by itself, including restoring connections of jack client apps that have no notion of explicit session support, be it lash, ladish L1, nsm-proto, or jack-plugin. Support for the latter two is yet to be implemented. ladish also can handle jack apps running the deprecated now by jackaudio project jack session protocol.

[1] http://ladish.org https://ladish.org

**Comment by BlueMax** [comment]
All 'auto-connector' apps failed for me in the end in some way or another and/or involved too much hassle for new apps.
The final solution i'm still using today: Using a 'default sink' that gets connected with the same reliability as a soundcard. In other words a 'virtual soundcard'. Or in technical terms 'Nullsink' (Pipewire) or 'snd-aloop' (Alsa).
https://github.com/falkTX/Carla/issues/1574#issuecomment-1019344257

**Comment by satchnut** [comment]
Good to know about ladish. Unfortunately for me I'm on Win10, so reliable JACK sink options are already extremely limited. My current workaround is similar to that of BlueMax's: JACK sinking into a VoiceMeeter Banana insert (the only virtual ASIO / exclusive-audio sink I've been able to get to play with JACK so far on Win). This does add about triple the CPU utilization at-rest (as well as some latency, I would imagine) compared to JACK sinking straight into hardware output / ASIO4ALL.
