### ISSUE TITLE
Jack2 library version in homebrew: libjack.0.dylib vs libjack.0.1.0.dylib

### ISSUE THREAD

**Issue by dyfer** [jackaudio/jack2#733]
## Describe the bug

My apologies if this should be rather reported to homebrew.

It seems that software compiled against **homebrew** jack2 links against `libjack.0.1.0.dylib`, while software compiled against jack2 from the official installer links against `libjack.0.dylib`. The latter is more compatible and allows that software to also run with older jack (namely JackOSX distribution). 

Is there a way to make `libjack.0.dylib` take precedence in the homebrew version?

Homebrew provides a slightly patched version of Jack 1.9.17, see https://github.com/jackaudio/jack2/issues/640#issuecomment-723022578 and https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/jack.rb#L31

This results in software built agains homebrew jack2 not running with the old JackOSX. #640 is about the issue "the other way around" (software built against JackOSX not running on Jack2).

@fanninpm do you have any ideas about this?

## Environment

* **JACK Version:** 1.9.17 (bulid), 1.9.11 (run)
* **Operating System:** macOS
* **Installation:** installer; homebrew
## Steps To Reproduce

1. Install Jack2 with homebrew or using the installer 
- `brew install jack`
2. compile 3rd party software that uses jack 
3. move that software to another machine with JackOSX (1.9.11) installed
4. run 3rd party software

If the 3rd party app is built agains Jack2 from the official installer - the application runs. If it's built against Jack2 from homebrew - it doesn't run with the older Jack.

Here's an output from otool on JackTrip compiled against Jack2 from homebrew and from the official installer:
Jack2 from homebrew:
```
$ otool -L jacktrip
jacktrip:
	/usr/local/opt/jack/lib/libjack.0.1.0.dylib (compatibility version 0.1.0, current version 1.9.17)
```
Jack2 from the installer:
```
$ otool -L jacktrip
jacktrip:
	/usr/local/opt/jack/lib/libjack.0.dylib (compatibility version 0.0.0, current version 0.1.0)
```

### Expected vs. actual behavior

Expected: software built against homebrew Jack2 runs on older Jack (JackOSX).
Actual: software built against homebrew Jack2 doesn't run on older Jack (JackOSX)

**Comment by fanninpm** [comment]
Which version of macOS are you compiling with?

**Comment by dyfer** [comment]
> Which version of macOS are you compiling with?

10.15

**Comment by fanninpm** [comment]
Try forking the Homebrew core repository, editing the `jack` formula (removing the OS version constraints in the `install` block), and building `jack2` from source.

**Comment by dyfer** [comment]
Sorry, I must've had an older version of Jack2 installed (1.9.16?). The behavior is the same for homebrew Jack2, altered homebrew Jack2 (removed OS contraints) and current Jack 1.9.17 - all result in creating binaries linked with `...0.1.0.dylib`. I'll open another issue to clarify. Sorry for the noise @fanninpm
