### ISSUE TITLE
qjackctl update?

### ISSUE THREAD

**Issue by 0lm** [jackaudio/jack2#735]
just a side question. is it possible to integrate the newest qjackctl into jack2? for me it is still using the version from year 2015 while the most recent qjackctl version is from 2021. am i doing something wrong?
Im usually opening the interface via Jack Control.

**Comment by falkTX** [comment]
huh, what makes you say so?
the automated releases use 0.9.0 as set in https://github.com/jackaudio/jack2-releases/blob/master/pack-jack2-version.sh#L4

I will update that to 0.9.2

**Comment by falkTX** [comment]
Updated at https://github.com/jackaudio/jack2-releases/releases/tag/untagged-1c7aa69258f0a23d217f

though the qjackctl 0.9.0 of last jack2 releases had a few patches from it, so difference is small.
