### ISSUE TITLE
Seeking advice: Must I recompile jackd if i compile FFADO with custom configuration?

### ISSUE THREAD

**Issue by DanielDewberry** [jackaudio/jack2#742]
I am using KUbuntu 20.04 with Ardour 6.6.0.  I would like to make my Focusrite Liquid Saffire 56 firewire soundcard work properly with FFADO.  My research has informed me that I must reconfigure FFADO as Focusrite reused device identifiers. 

If I make the necessary changes to FFADO and compile it, will I need to build Jackd from source and cease using the packaged version?

Version data for reference:
```
ffado-dbus-server/focal 2.4.2-1build1 amd64 
ffado-mixer-qt4/focal   2.4.2-1build1 all 
ffado-tools/focal       2.4.2-1build1 amd64 
jack-capture/focal      0.9.73-3 amd64 
jackd2-firewire/focal   1.9.12~dfsg-2ubuntu2 amd64 
jackd2/focal            1.9.12~dfsg-2ubuntu2 amd64 
jackd/focal             5+nmu1 all 
jack-keyboard/focal     2.7.2-1 amd64 
jack-rack/focal         1.4.8~rc1-2ubuntu4 amd64 
libffado2/focal         2.4.2-1build1 amd64 
libffado-dev/focal      2.4.2-1build1 amd64 
```

The [change](https://web.archive.org/web/20160714132759/http://ffado.org/?q=node/2062) I intend to make is

> comment out the PRO 10 section in the file "configuration" in the FFADO source directory, add the following, and reinstall:
> ,
> {
> vendorid = 0x00130e;
> modelid = 0x00000006;
> vendorname = "Focusrite";
> modelname = "Liquid Saffire 56";
> driver = 20;
> mixer = "Generic_Dice_EAP";
> }
> 
> Put this snippet before the closing ");".

Thank you 

Daniel

**Comment by falkTX** [comment]
you only need to rebuild ffado, not jack.

**Comment by DanielDewberry** [comment]
Thank you
