### ISSUE TITLE
jackd using a lot of CPU with small buffer sizes

### ISSUE THREAD

**Issue by mikeoliphant** [jackaudio/jack2#744]
The CPU usage of jackd seems to be impacted more by the audio buffer size than I would expect. On my system, it uses almost twice as much CPU with a buffer size of 32 as it does with a 64 sample buffer.

With a 32-sample buffer, the jackd process ends up using almost 10% of a Raspberry Pi 4 CPU core - twice as much CPU as my actual audio processing client (which is doing non-trival guitar amplifier/effect/cabinet simulation).

I am using the alsa backend and a USB audio interface.

## Environment

jackdmp version 1.9.12 tmpdir /dev/shm protocol 8
OS: Linux on Raspberry Pi 4.
Installed via apt-get

**Comment by falkTX** [comment]
nothing wrong here, this is quite expected.
32 frames at 48000Hz means processing audio every 0.6ms. from fetching buffers, to copy, to signaling events etc etc
a lot of systems cannot even run with a buffer size of 32.

**Comment by mikeoliphant** [comment]
I'm aware that a 32-sample buffer is aggressively small. I would expect to be more susceptible to dropouts, and I would expect an increase in overhead as the buffer size decreases, but the actual amount of overhead from jackd (or, perhaps the underlying alsa system) surprised me - particularly that it was using more CPU than my actual DSP code. Maybe I'll try a pure alsa approach to compare.

**Comment by falkTX** [comment]
when you reach that low of a buffer size, assuming the sound card can handle it, that is expected.
this is why a lot of cards cannot even go that low, because the time required to poll buffers, sync audio threads, write to output buffers etc is too long and the application ends up not even able to process 1 audio cycle.

**Comment by mikeoliphant** [comment]
I get that - but why the high CPU usage in the jackd process as compared to the actual DSP client code?

On Raspberry Pi 4 with a USB audio interface, I can run solid at 32 samples without dropouts as long as the CPU usage on the core being used stays under around 15-20% . Once I start exceeding that, I get dropouts. At 32 samples, though, the jackd process is using 10% of the CPU, so I only have 5-10% for my actual DSP. If I increase the buffer size to 64 samples (which, to be fair, is still very good), then the jackd usage goes down to around 5% and I get more headroom for my stuff. I would still like to get some of that 5% back though - I have to go up to 1024 samples before the jackd CPU drops below 1%.

I understand that this may well just be the cost of doing business through the alsa driver (which is why I plan to test straight alsa) - I just wanted to make sure that there isn't some potentially fixable per-buffer overhead happening in jack that people wouldn't notice unless they try to run a very small buffer sizes on (relatively) slow systems.

**Comment by falkTX** [comment]
you need to look into the jack dsp load, not the real cpu load. the jack dsp load is the measurement regarding time you have left on the audio thread side.
a "sleep(1)" on the dsp side will take more than 100% of jack dsp load, while remaining at 0% in the cpu load.
jack consuming so much actual cpu load is just all the thread-sync and buffer handling happening many many times a second.

you will definitely get buffer results with using raw alsa. if you only intend to run a single application, that is the best to do anyway.

**Comment by mikeoliphant** [comment]
For dsp load, do you mean the output of jack_cpu_load()?

It still seems strange to me that with a 32-sample buffer, the jack activity is taking twice as much CPU as my DSP operations, which involve passing through amp sim, cabinet IR convolution, algorithmic reverb, etc. -- all at the same many, many times per second.

I will definitely try using raw alsa, as I'm running a single client - although using jack is more convenient and flexible.

Thanks for your responses - and thanks for all of your open source audio contributions. I've got my own framework now, but the mod-host/mod-ui stuff got me interested in doing guitar fx processing in Linux.

**Comment by falkTX** [comment]
> For dsp load, do you mean the output of jack_cpu_load()?

yes.

the thing that takes time for jack is the thread synchronization of clients. context-switching due to IPC is an expensive operation under the ARM platform.
there are ways to reduce the jackd load, but a bit too complex to explain in simple words.
I did quite a few steps for this for MOD, most of the changed ended up upstream, but still a few important things remain as custom patch:
1. use internal jack client instead of external (ie, standalone), so that we can avoid the heavy IPC
2. patch sources so that audio thread sync (linux futex) is always set in private mode, thus completely avoiding context switches
3. remove a bunch of time calculations that are only used if jack is run in verbose mode
4. for the SOCs that support proper cpu cycle counter, use it as timing source instead of system clock
5. as bonus, removed a lot of stuff regarding xruns, so that it recovers faster

you can try using https://github.com/moddevices/jack2 which provides all that, except the cycle counter stuff (which is really unsafe to use in most devices)
you will need to use internal clients though, as the repo is setup to assume that to be the default

**Comment by mikeoliphant** [comment]
That is really helpful information - thanks! In particular, I suspect running as an internal client may make a significant difference.

**Comment by schnitzeltony** [comment]
> On Raspberry Pi 4 with a USB audio interface, I can run solid at 32 samples without dropouts as long as the CPU usage on the core being used stays under around 15-20% . Once I start exceeding that, I get dropouts. At 32 samples, though, the jackd process is using 10% of the CPU, so I only have 5-10% for my actual DSP. If I increase the buffer size to 64 samples (which, to be fair, is still very good), then the jackd usage goes down to around 5% and I get more headroom for my stuff. I would still like to get some of that 5% back though - I have to go up to 1024 samples before the jackd CPU drops below 1%.

Have a Raspi 4
* image build with Yocto
* Linux raspberrypi4-64 5.4.74-rt40 #1 SMP PREEMPT Wed Nov 11 23:33:01 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
* Audioinjector as soundcard
* At 32 samples qjackctl reports CPU load of 0.9 - 1% 
* Made some tests with Logitech USB headset: It cannot go down to 32 samples but on 64 samples qjackctl reports 0.66% CPU load

=> Raspi 4 can do better

**Comment by mikeoliphant** [comment]
Interesting, @schnitzeltony - what jack version are you running? I am on 1.9.12.

On my Pi 4 with a 32 sample buffer, qjackctl reports between 5-10% usage with no clients running. With a 1024 sample buffer, it goes down to 0.25%.

You are running a newer kernel (I'm on 4.19). Does "PREEMPT" mean your running a realtime kernel? Wonder if that might be the difference.

**Comment by schnitzeltony** [comment]
* Jack version on machine reported is 1.19.14
* Yes I have the RT-patches in kernel build and CONFIG_PREEMPT set

**Comment by mikeoliphant** [comment]
I just tried the MOD version of jack2 and it does not use noticeably less CPU on my system. I also grabbed and compiled the mainline version, and it was a bit worse...
