### ISSUE TITLE
Sources and Sinks not spawning in correct order.

### ISSUE THREAD

**Issue by Krauus** [jackaudio/jack2#754]
## Describe the bug

Sources and Sinks not spawning in correct order when using JACK D-Bus Detect PA module.

I opened a ticket with full description of the bug on [PulseAudio's Gitlab Issue Tracker](https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/1197).

But! I am not sure if this is a PA issue or a JACK issue.

## Environment

Manjaro
pulseaudio 14.0-282-gd21d0
jackdmp version 1.9.18 tmpdir /dev/shm protocol 8
QjackCtl 0.9.2

(Full environment in pa-info.txt file in GitLab thread)

## Steps To Reproduce

Set number of sink channels to 10 in `/etc/pulse/default.pa` with `sink_channel_map=[args]`

Start JACK through QjackCtl when "Enable JACK D-Bus interface" is checkmarked.

### Expected vs. actual behavior

Sources and Sinks are being spawned alphabetically instead of the order passed through from PulseAudio.

![image](https://user-images.githubusercontent.com/69413775/116488263-c454c900-a846-11eb-92cc-7efc2fd024d7.png)

Is this a PulseAudio issue? A JACK issue? Or is this normal behavior?

I'm using QjackCtl, but I don't suspect it's an app-specific issue. I am unsure, though.

Is there a way I can reproduce this test using purely CLI commands?

**Comment by falkTX** [comment]
JACK does not order the ports automatically.
They are given to all clients as they were originally registered.

If a specific ordering is required, there is a metadata property for that.
https://jackaudio.org/metadata/order/

**Comment by Krauus** [comment]
Is the original registration passed down from PulseAudio?

**Comment by falkTX** [comment]
It is not really relevant. jack2 shows the ports in the order they are registered, jack1 does the exact opposite/reverse.
If an application wants to force a specific order, it should use meta-data to enforce this.
jack meta-data is detailed at https://jackaudio.org/api/group__Metadata.html

**Comment by Krauus** [comment]
Found out it's a QjackCtl thing. I opened it in Carla (at your suggestion) and it's working fine.

![image](https://user-images.githubusercontent.com/69413775/116489485-f0257e00-a849-11eb-9e46-08a325b74ae1.png)
