### ISSUE TITLE
Install Problem with Mojave

### ISSUE THREAD

**Issue by denoveri** [jackaudio/jack2#759]
## Environment

* **JACK Version:** Which version of jack2 are you using? (e.g. the output of `jackd --version` or a git commit checksum)
* **Operating System:** What operating system or distribution in which version are you using? (e.g. Linux, macOS, Windows)
* **Installation:** How did you install jack2? (e.g. package manager, from source)

## Steps To Reproduce

```bash
# Paste a minimal code example here (e.g. about how you started JACK)
```

### Expected vs. actual behavior

A clear and concise description of what you expected to happen vs. what happened.

**Comment by denoveri** [comment]
I recently upgraded to MacOS Mojave.  Following that, I installed Jack 1.9.18.  I got the message 'succesfully installed'.  But there is no JACK APP in the Applications folder.  Am I doing anything wrong?  Is this the right place to ask such a question?

**Comment by falkTX** [comment]
Use the discussions for stuff you dont understand.
JACK is working fine, there is no tool in applications folder added, as JACK is a sound server and not an application.
Use the provided QjackCtl if you want a GUI.
