### ISSUE TITLE
DBus exception: org.freedesktop.DBus.Error.NoReply

### ISSUE THREAD

**Issue by waqas-subhani** [jackaudio/jack2#764]
[waqas@Arch ~]$ jack_control ds alsa
--- driver select "alsa"
[waqas@Arch ~]$ jack_control dps device hw:0
--- driver param set "device" -> "hw:0"
[waqas@Arch ~]$ jack_control dps rate 48000
--- driver param set "rate" -> "48000"
[waqas@Arch ~]$ jack_control dps period 512
--- driver param set "period" -> "512"
[waqas@Arch ~]$ jack_control start
--- start
DBus exception: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
[w

I am running jack2 on virtualbox,when I am selecting dummy jack_control work fine, and When using alsa , above issue occur, kindly help. my system info is below:

 [waqas@Arch ~]$ cat /proc/asound/cards
 0  [I82801AAICH    ]: ICH - Intel 82801AA-ICH
                      Intel 82801AA-ICH with AD1980 at irq 21

[waqas@Arch ~]$ hostnamectl
 Static hostname: Arch
       Icon name: computer-vm
  Virtualization: oracle
Operating System: Arch Linux                      
          Kernel: Linux 5.12.10-arch1-1
    Architecture: x86-64
 Hardware Vendor: innotek GmbH
  Hardware Model: VirtualBox

**Comment by dvzrv** [comment]
Hi! I believe this might be an issue due to virtualization. Are you able to playback audio through plain ALSA?

Also, please start JACK using [jackd](https://man.archlinux.org/man/jackd.1) instead of through `jack_control` (jackdbus) to rule out issues in relation to dbus.

**Comment by waqas-subhani** [comment]
Hi, Thanks for your email.
Using jackd start Jack on (Ubuntu 20.04.02) , It gets no issue. output of
the jackd is attached.
But how do we set up connections between applications using jackd ? There
is no command to check available applications Interfaces for audio routing
, as we can set up  connections using jack_connect or using connection
manager in Qjackctl.

**Comment by waqas-subhani** [comment]
waqas@waqas-VirtualBox:~$ sudo jackd -R -d alsa -d hw:0 -r48000 -p512 -n2
[sudo] password for waqas: 
jackdmp 1.9.18
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2021 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
no message buffer overruns
no message buffer overruns
no message buffer overruns
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
creating alsa driver ... hw:0|hw:0|512|2|48000|0|0|nomon|swmeter|-|32bit
configuring for 48000Hz, period = 512 frames (10.7 ms), buffer = 2 periods
ALSA: final selected sample format for capture: 16bit little-endian
ALSA: use 2 periods for capture
ALSA: final selected sample format for playback: 16bit little-endian
ALSA: use 2 periods for playback

**Comment by dvzrv** [comment]
> Using jackd start Jack on (Ubuntu 20.04.02) , It gets no issue. output of
the jackd is attached.

You *have to* be more specific about to which system you are referring to now if you expect someone to help you :)
In your initial comment you state, that you were attempting to start JACK using jack_control on an Arch Linux box running on virtualbox. Now you state that you are running on Ubuntu 20.04.02.

> waqas@waqas-VirtualBox:~$ sudo jackd -R -d alsa -d hw:0 -r48000 -p512 -n2

Why do you run jackd as root? This is not necessary and also not recommended.

> But how do we set up connections between applications using jackd ? There
is no command to check available applications Interfaces for audio routing
, as we can set up  connections using jack_connect or using connection
manager in Qjackctl.

As this seems to be rather a general "how do I work with JACK" request and not a specific bug report (you did not use any of the provided issue templates when opening this ticket), I suggest you check with the [community channels](https://jackaudio.org/community.html) for support and/or with [the wiki](https://github.com/jackaudio/jackaudio.github.com/wiki) for further information and close this ticket, as the issue tracker is for the development of jack2, not for support on how to learn how to use it.

**Comment by waqas-subhani** [comment]
Actually I am working at Arch using VirtualBox now. I follow the wiki [](https://wiki.archlinux.org/title/JACK_Audio_Connection_Kit)  configuration to setup the jack2, Its not work for me at all.  I also  try to launch using Qjackctl. When I am starting  , show error prompt as ( D-bus: Jack server could not be started. sorry)  
I did not understand why these errors comes.
