### ISSUE TITLE
After resume jack needs to be restarted so clients can reconnect

### ISSUE THREAD

**Issue by mfs12** [jackaudio/jack2#771]
Hey,

after a recent upgrade I experience the following problem. I am wondering if i am the only person.

## Describe the bug

Since upgrading to Linux kernel 5.12.12-arch1-1 jack2 1.9.18-1 clients fail to reconnect to jack server.

## Environment

* **JACK Version:** 1.9.18-1
* **Operating System:** Arch Linux running kernel 5.12.12-arch1-1
* **Installation:** pacman

## Steps To Reproduce

- connect any client, i.e. pulseaudio jack sink, ardour.
- suspend to RAM
- resume
- resume playing music

### Expected vs. actual behavior

I would expect the clients continue to work as it was before.

**Comment by dvzrv** [comment]
It is expected that after suspend to RAM jackd needs to be restarted. It has exclusively power over the audio hardware after all.

**Comment by falkTX** [comment]
I have jack running 100% of the time on my main desktop, and put it on suspend many many times through out the month.
Only powering off for the occasional reboot.

So I would not say this is expected.
Might be a quirk of the system that cuts power to USB devices and other peripherals.
Might be fixed adjusting some BIOS settings.

**Comment by mfs12** [comment]
It was working smoothly until recently. Means i could suspend and resume my computer without restarting jackd. I think the behavior changed with a recent kernel update.

Anyway. But it looks like i am the only one so it's specific to my system not something happening in general.

**Comment by falkTX** [comment]
would be useful to get some logs.
turn on verbose mode in jack (depending on what you use to start it) and make this buggy behaviour happen.

that would help to shine some light on this.

**Comment by mfs12** [comment]
I think it was related to a device i had connected. So far i couldn't reproduce it. I will reopen it if it's going to happen again. Closing it for now. Thanks for the support.
