### ISSUE TITLE
jack2 no longer honours devices and is grouping everything under "system"

### ISSUE THREAD

**Issue by markjfisher** [jackaudio/jack2#780]
## Describe the bug

When I used jack 1.19.11, it would correctly find the hardware and SAR (Synchronous Audio Router) devices and display them for me to use in audio routing (via Catia for example).

Latest versions no longer show the devices, and simply list everything under "system".

Here is a view from 1.9.11:

<img width="802" alt="jack2-1 9 11-catia-view-all-devices" src="https://user-images.githubusercontent.com/1616940/127323162-8012567d-df0c-46c8-9bac-6b99badde006.png">

Here is the view from 1.9.19:

<img width="460" alt="jack2-1 9 19-catia-view-all-devices" src="https://user-images.githubusercontent.com/1616940/127323199-348d97b0-2e32-48aa-a85c-d9565905fda8.png">

I've included in the middle of each image the Port Information for the same "capture_19" port which in 1.9.11 had a second alias of "desktop 1", but in the current version no longer has this alias name.

Also of note is that all the hardware devices (ADAT1, 2, ... etc) are grouped into System and no longer showing separately, so I don't believe this is a SAR issue.

## Environment

* **JACK Version:** 1.9.19
* **Operating System:** Windows 10
* **Installation:** Using the msi download from releases site

## Steps To Reproduce

* Download and install 1.9.11.
* Install and configure some SAR devices
* Run qjackctl configured to use Interface "ASIO::Synchronous Audio Router"
* Open Catia to view the available devices
* Note they are all separate as in diagram above for 1.9.11

Repeat the above with 1.9.19 and note they are no longer separate, but all pulled together under "system"

### Expected vs. actual behavior

I've explained what I expect in the steps to reproduce and images; the device list for each separate SAR configured device (and hardware device too, e.g. ADAT1, ADAT2 etc for my soundcard)

**Comment by falkTX** [comment]
v1.9.11 is so old that getting any real info on this will be near impossible.

if you know of a potential culprit, do say.
pull requests welcome.

**Comment by markjfisher** [comment]
the first culprit appears to be the second alias name missing from latest version, which I was wondering if the old code was using to separate out the devices by

**Comment by markjfisher** [comment]
if you could roughly point me to where the capture/playback devices are created, I don't mind having a hunt through the code to see if I can see anything obvious.

**Comment by falkTX** [comment]
[https://github.com/jackaudio/jack2/tree/develop/windows/portaudio](windows/portaudio] is the place to look, either the *Devices.cpp or *Driver.cpp, ignore the adapter stuff.

**Comment by markjfisher** [comment]
An update, which I work through this.

Going through the codebase, I did find that I can manually add an alias to make it appear correctly in Catia with:

    tools\jack_alias.exe system:capture_19 "desktop 1"

which gives me the correct change:

<img width="437" alt="jack2-1 9 19-manually-add-alias" src="https://user-images.githubusercontent.com/1616940/127374454-fab9fdad-c824-4b09-ac50-a6b299cb2f2f.png">

Now trawling through a huge diff to see if any alias code was removed, or some other change subtly removed the aliasing.
I'm still not sure how it got the "desktop 1" and other names yet though.
I'm continuing to hunt

**Comment by falkTX** [comment]
you can try to set catia option to show alias 1 instead of alias 2.

**Comment by markjfisher** [comment]
thanks, but unfortunately, that doesn't help.

I need the aliases (e.g. "desktop 1", "discord 1" etc) because the alias 1 names (e.g. "portaudio:ASIO::Synchronous Audio Router:out19") don't tell me that's my "desktop channel 1".

it's just "out19" and I would have to work out what that maps to as a device anyway, which is no better than "capture_19"

e.g. it now looks like:

<img width="416" alt="jack2-1 9 19-alias1" src="https://user-images.githubusercontent.com/1616940/127379534-b5c7d27c-90a2-439d-ad25-8f2abc9b2550.png">

**Comment by falkTX** [comment]
hmm yeah, that looks ugly.

**Comment by markjfisher** [comment]
Is there any archive of installable versions of Jack2 between 1.9.11 and 1.9.19? I can only find the src downloads, and I don't have the toolchains to compile them. I could at least then find out which version it changed in.

**Comment by falkTX** [comment]
There are some on https://github.com/jackaudio/jackaudio.github.com/releases

but v1.9.11 is the most updated one from the old windows builds.
a lot has changed in jack since then, in a period where we did not make any windows builds.

but since this is only about 1 specific folder, perhaps easy to check for changes.

I just run a local diff of develop branch against v1.9.10 release, these are the only relevant changes
```
diff --git a/windows/portaudio/JackPortAudioAdapter.cpp b/windows/portaudio/JackPortAudioAdapter.cpp
index 7c380193..09013588 100644
--- a/windows/portaudio/JackPortAudioAdapter.cpp
+++ b/windows/portaudio/JackPortAudioAdapter.cpp
@@ -211,8 +211,8 @@ extern "C"
         desc = jack_driver_descriptor_construct("audioadapter", JackDriverNone, "netjack audio <==> net backend adapter", &filler);
 
         value.ui = 0;
-        jack_driver_descriptor_add_parameter(desc, &filler, "in-channels", 'i', JackDriverParamInt, &value, NULL, "Maximum number of input channels", NULL);
-        jack_driver_descriptor_add_parameter(desc, &filler, "out-channels", 'o', JackDriverParamInt, &value, NULL, "Maximum number of output channels", NULL);
+        jack_driver_descriptor_add_parameter(desc, &filler, "in-channels", 'i', JackDriverParamUInt, &value, NULL, "Maximum number of input channels", NULL);
+        jack_driver_descriptor_add_parameter(desc, &filler, "out-channels", 'o', JackDriverParamUInt, &value, NULL, "Maximum number of output channels", NULL);
 
         jack_driver_descriptor_add_parameter(desc, &filler, "capture", 'C', JackDriverParamString, &value, NULL, "Provide capture ports. Optionally set PortAudio device name", NULL);
 
@@ -230,10 +230,10 @@ extern "C"
         jack_driver_descriptor_add_parameter(desc, &filler, "list-devices", 'l', JackDriverParamBool, &value, NULL, "Display available PortAudio devices", NULL);
 
         value.ui = 0;
-        jack_driver_descriptor_add_parameter(desc, &filler, "quality", 'q', JackDriverParamInt, &value, NULL, "Resample algorithm quality (0 - 4)", NULL);
+        jack_driver_descriptor_add_parameter(desc, &filler, "quality", 'q', JackDriverParamUInt, &value, NULL, "Resample algorithm quality (0 - 4)", NULL);
 
         value.ui = 32768;
-        jack_driver_descriptor_add_parameter(desc, &filler, "ring-buffer", 'g', JackDriverParamInt, &value, NULL, "Fixed ringbuffer size", "Fixed ringbuffer size (if not set => automatic adaptative)");
+        jack_driver_descriptor_add_parameter(desc, &filler, "ring-buffer", 'g', JackDriverParamUInt, &value, NULL, "Fixed ringbuffer size", "Fixed ringbuffer size (if not set => automatic adaptative)");
 
         return desc;
     }
diff --git a/windows/portaudio/JackPortAudioDevices.cpp b/windows/portaudio/JackPortAudioDevices.cpp
index 686202ef..362461bd 100644
--- a/windows/portaudio/JackPortAudioDevices.cpp
+++ b/windows/portaudio/JackPortAudioDevices.cpp
diff --git a/windows/portaudio/JackPortAudioDevices.h b/windows/portaudio/JackPortAudioDevices.h
index 0acb104b..93af2541 100644
--- a/windows/portaudio/JackPortAudioDevices.h
+++ b/windows/portaudio/JackPortAudioDevices.h
@@ -23,8 +23,8 @@ Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 #include <cstdio>
 #include <string>
 
-#include "portaudio.h"
-#include "pa_asio.h"
+#include <portaudio.h>
+#include <pa_asio.h>
 
 /*!
 \brief A PortAudio Devices manager.
diff --git a/windows/portaudio/JackPortAudioDriver.cpp b/windows/portaudio/JackPortAudioDriver.cpp
index 994c3f17..97ceecd2 100644
--- a/windows/portaudio/JackPortAudioDriver.cpp
+++ b/windows/portaudio/JackPortAudioDriver.cpp
@@ -196,8 +196,12 @@ int JackPortAudioDriver::Open(jack_nframes_t buffer_size,
     }
 
     // Generic JackAudioDriver Open
+    char capture_driver_name[JACK_CLIENT_NAME_SIZE];
+    char playback_driver_name[JACK_CLIENT_NAME_SIZE];
+    snprintf(capture_driver_name, sizeof(capture_driver_name), "%s", capture_driver_uid);
+    snprintf(playback_driver_name, sizeof(playback_driver_name), "%s", playback_driver_uid);
     if (JackAudioDriver::Open(buffer_size, samplerate, capturing, playing, inchannels, outchannels, monitor,
-        capture_driver_uid, playback_driver_uid, capture_latency, playback_latency) != 0) {
+        capture_driver_name, playback_driver_name, capture_latency, playback_latency) != 0) {
         return -1;
     }
 
@@ -239,12 +243,6 @@ int JackPortAudioDriver::Open(jack_nframes_t buffer_size,
     fEngineControl->fConstraint = fEngineControl->fPeriodUsecs * 1000;
 #endif
 
-    assert(strlen(capture_driver_uid) < JACK_CLIENT_NAME_SIZE);
-    assert(strlen(playback_driver_uid) < JACK_CLIENT_NAME_SIZE);
-
-    strcpy(fCaptureDriverName, capture_driver_uid);
-    strcpy(fPlaybackDriverName, playback_driver_uid);
-
     return 0;
 
 error:
@@ -336,10 +334,6 @@ int JackPortAudioDriver::SetBufferSize(jack_nframes_t buffer_size)
         goto error;
     }
 
-    // It seems that some ASIO drivers (like ASIO4All) needs this to restart correctly;
-    delete fPaDevices;
-    fPaDevices = new PortAudioDevices();
-
     err = OpenStream(buffer_size);
     if (err != paNoError) {
         jack_error("Pa_OpenStream error = %s", Pa_GetErrorText(err));
```

**Comment by falkTX** [comment]
Those 2 lines
```
-    strcpy(fCaptureDriverName, capture_driver_uid);
-    strcpy(fPlaybackDriverName, playback_driver_uid);
```
are very suspicious...

Sadly travis went to shit, so we dont have automated builds anymore.

**Comment by markjfisher** [comment]
I'll try and setup a toolchain and compile with those lines re-add and see if it fixes it, unless you can do a mini-release I can test?

**Comment by falkTX** [comment]
I can do a quick win64 build from here with those lines added back.
win64 works for you right, or do you need win32?

**Comment by markjfisher** [comment]
win64 fine

**Comment by falkTX** [comment]
oh actually I see an issue.
there is a macro `HAVE_ASIO` which is not defined anymore.

and https://github.com/jackaudio/jack2/commit/e3bbd5cdbaee8a0a13fece93327662e344fb21bf is the commit that removed those lines.
rightfully so, as JackDriver.cpp has that same code, so it is useless there.

I will fix the `HAVE_ASIO` macro instead, really seems that it is the issue, as it includes this code:
```

#if defined(HAVE_ASIO)
        if (fInputDevice != paNoDevice && fPaDevices->GetHostFromDevice(fInputDevice) == "ASIO") {
            for (int i = 0; i < fCaptureChannels; i++) {
                if (PaAsio_GetInputChannelName(fInputDevice, i, &alias) == paNoError) {
                    JackPort* port = fGraphManager->GetPort(fCapturePortList[i]);
                    port->SetAlias(alias);
                }
            }
        }

        if (fOutputDevice != paNoDevice && fPaDevices->GetHostFromDevice(fOutputDevice) == "ASIO") {
            for (int i = 0; i < fPlaybackChannels; i++) {
                if (PaAsio_GetOutputChannelName(fOutputDevice, i, &alias) == paNoError) {
                    JackPort* port = fGraphManager->GetPort(fPlaybackPortList[i]);
                    port->SetAlias(alias);
                }
            }
        }
#endif
```

**Comment by markjfisher** [comment]
that looks much more promising

**Comment by falkTX** [comment]
There you go, see if this one works.

[jack2-win64-v1.9.19.zip](https://github.com/jackaudio/jack2/files/6895946/jack2-win64-v1.9.19.zip)

**Comment by markjfisher** [comment]
brb, rebooting to install, didn't work directly installing from this, so I've removed old version and going to check my system is clear

**Comment by falkTX** [comment]
Since I am pretty positive this should do something, I pushed the fix already to caf336a6bc68ad0a8414ce1b6e40d40707cbc873

**Comment by falkTX** [comment]
spoke too soon, I think an extra little something still needed.

**Comment by markjfisher** [comment]
hmm, no change here. just single "system" with 34 capture_xx entries still.
anyway i can prove i installed this new version?

**Comment by falkTX** [comment]
2nd attempt. I verified that the code in question is being compiled/enabled.

[jack2-win64-v1.9.19-try2.zip](https://github.com/jackaudio/jack2/files/6896015/jack2-win64-v1.9.19-try2.zip)

**Comment by markjfisher** [comment]
It's alive!

<img width="481" alt="jack2-1 9 19-catia-view-all-devices-fixed" src="https://user-images.githubusercontent.com/1616940/127385078-004f2d53-17a4-41b3-86fd-4c6221d7bf96.png">

**Comment by falkTX** [comment]
Great! Thanks for the report, I was not aware a bunch of ASIO code was not active, good stuff.
This will be part of next release then.

**Comment by markjfisher** [comment]
many thanks. that's made my night.

**Comment by markjfisher** [comment]
A final comment on this, but qjackctl also does not use alias 2 names to split the devices. I don't really care, just thought I'd mention it, as it looks similar to my initial report.

<img width="889" alt="qjackctl-port-assignment-no-devices" src="https://user-images.githubusercontent.com/1616940/127389523-79cb6b6f-c82a-41db-840e-1c5ce4b66cbd.png">

**Comment by falkTX** [comment]
you can change something in qjackctl settings to show aliases or metadata.
but I dont think it will split the main client.

catia by default shows 2nd alias, when present.

just a matter of different default configs.
