### ISSUE TITLE
Build failure on tools directory in Raspberry Pi 4 64-bit (aarch64)

### ISSUE THREAD

**Issue by arthurc2000** [jackaudio/jack2#781]
## Describe the bug
type ./waf -v and it cannot build the tools directory, e.g. midi_dump.c..

226966
## Environment
[Raspberry Pi 4, gcc 8.3.0] (log attached)
[IMX8 Nano, gcc 7.3.0] (no log)
There is a similar issue on simdtests.cpp.

JACK Version: latest

Rpi 4 OS: Raspian OS 64 bit 5.10.17-v8+
imx8mm : 4.14.98

## Steps To Reproduce
pi@raspberrypi:~/jack2 $ ./waf -v
Waf: Entering directory `/home/pi/jack2/build'
15:43:31 runner 'cd man ; sh fill_template 1.9.19'
[167/219] Linking build/example-clients/jack_simdtests
15:43:32 runner ['/usr/bin/gcc', 'example-clients/simdtests.cpp.9.o', '-o/home/pi/jack2/build/example-clients/jack_simdtests', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-Lcommon', '-ljack', '-lpthread', '-lrt', '-ldl', '-lm', '-Wl,--no-undefined']
[189/219] Linking build/tools/jack_load
15:43:32 runner ['/usr/bin/gcc', 'tools/ipload.c.6.o', '-o/home/pi/jack2/build/tools/jack_load', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-Lcommon', '-ljack', '-lpthread', '-lrt', '-ldl', '-lm', '-Wl,--no-undefined']
[192/219] Linking build/tools/jack_lsp
15:43:32 runner ['/usr/bin/gcc', 'tools/lsp.c.7.o', '-o/home/pi/jack2/build/tools/jack_lsp', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-Lcommon', '-ljack', '-lpthread', '-lrt', '-ldl', '-lm', '-Wl,--no-undefined']
[193/219] Linking build/tools/jack_midi_dump
15:43:32 runner ['/usr/bin/gcc', 'tools/midi_dump.c.8.o', '-o/home/pi/jack2/build/tools/jack_midi_dump', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-Lcommon', '-ljack', '-lpthread', '-lrt', '-ldl', '-lm', '-Wl,--no-undefined']
/usr/bin/ld: example-clients/simdtests.cpp.9.o: undefined reference to symbol '__gxx_personality_v0@@CXXABI_1.3'
/usr/bin/ld: //lib/aarch64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

Waf: Leaving directory `/home/pi/jack2/build'
Broken revdeps detected on {
        {task 548309762232: cxxprogram test.cpp.1.o -> jack_test},
        {task 548309762456: cxxprogram cpu.c.2.o -> jack_cpu},
        {task 548309762680: cxxprogram iodelay.cpp.3.o -> jack_iodelay},
        {task 548309762904: cxxprogram external_metro.cpp.4.o -> jack_multiple_metro},
        {task 548310712216: cprogram netsource.c.15.o,netjack_packet.c.15.o -> jack_netsource},
        {task 548309668024: vnum libjack.so -> libjack.so.0.1.0,libjack.so.0},
        {task 548310560952: vnum libjackserver.so -> libjackserver.so.0.1.0,libjackserver.so.0},
        {task 548310710760: cprogram monitor_client.c.9.o -> jack_monitor_client},
        {task 548310710984: cprogram property.c.10.o -> jack_property},
        {task 548310711208: cprogram samplerate.c.11.o -> jack_samplerate},
        {task 548310711432: cprogram session_notify.c.12.o -> jack_session_notify},
        {task 548310711656: cprogram ipunload.c.13.o -> jack_unload},
        {task 548310711880: cprogram wait.c.14.o -> jack_wait}}

**Comment by falkTX** [comment]
the `simdtests.cpp` tool should be built using g++ and not gcc.
fixed in #536 which I forgot to merge

**Comment by falkTX** [comment]
Thanks for the reminder, should be fixed in latest git.
