### ISSUE TITLE
jack_netsource.exe not in release anymore?

### ISSUE THREAD

**Issue by madskjeldgaard** [jackaudio/jack2#789]
## Describe the bug

On previous versions of jack on Windows there used to be a jack_netsource.exe program for using jack net but since updating one of our windows computers' jack installation here it seems to not be a part of the release anymore?

## Environment

* **JACK Version:** Which version of jack2 are you using? (e.g. the output of `jackd --version` or a git commit checksum)
* **Operating System:** Windows 10
* **Installation:** Installed using the latest installer on jackaudio.org

**Comment by falkTX** [comment]
You are correct, I see in the build config it is only enabled for linux or macOS.
Enabled the build just now, let's see if it succeeds https://github.com/jackaudio/jack2/actions/runs/1115814350

**Comment by falkTX** [comment]
It does, jack_netsource.exe is be there now.
Next release will include this tool, you can use the build artifacts from the link above in the mean time.

**Comment by madskjeldgaard** [comment]
Thank you !


Get Outlook for Android

**Comment by hockinsk** [comment]
Was jack_netsource.exe removed from Windows build again? I can't find it in latest release?
