### ISSUE TITLE
jackd start with control.c error

### ISSUE THREAD

**Issue by kionic666** [jackaudio/jack2#791]
Recently I installed the cadence for use. but always can not use normally, when i use ` jackd start ` in terminal, i got the error like this:

> [W][00171.528351][       control.c:   87 jackctl_server_create2()] not implemented 0x55e3253be4a0 0x55e3253be610 0x55e3253be6d0
[W][00171.528419][       control.c:  174 jackctl_server_get_parameters()] 0x55e326f002c0: not implemented
unknown option character 
[W][00171.528437][       control.c:  174 jackctl_server_get_parameters()] 0x55e326f002c0: not implemented
[W][00171.528448][       control.c:  395 jackctl_parameter_get_enum_constraints_ (nil): not implemented
[W][00171.528458][       control.c:  162 jackctl_server_get_drivers_list()] 0x55e326f002c0: not implemented
[W][00171.528467][       control.c:  253 jackctl_driver_get_type()] 0x55e326f069e0: not implemented
[W][00171.528476][       control.c:  245 jackctl_driver_get_name()] 0x55e326f069e0: not implemented
[W][00171.528485][       control.c:  185 jackctl_server_get_internals_list()] 0x55e326f002c0: not implemented
[W][00171.528493][       control.c:  114 jackctl_server_destroy()] 0x55e326f002c0: not implemented

my os is manjaro-linux

can anyone pls help me with this issue.

**Comment by falkTX** [comment]
are you using pipewire?

**Comment by kionic666** [comment]
yes, i was using pipewire

**Comment by falkTX** [comment]
yeah that is your problem, pipewire does not implement those dbus methods.

**Comment by dvzrv** [comment]
@kionic666: FWIW, you are likely using [pipewire-jack-dropin](https://aur.archlinux.org/packages/pipewire-jack-dropin/) as well, which means that when you attempt to start jackd the libraries required for jack2 are pointing at the pipewire provided `libjackserver.so` etc.

This is not supported. Either use pipewire *or* jack2, not both at the same time. If you have pipewire-jack-dropin installed you can *not* use the jackd executable or jack_control.

If you uninstall pipewire-jack-dropin you may use e.g. `pw-jack` to start applications using the pipewire provided jack implementation *and* you are able to use jackd in the way you describe above.

**Comment by kionic666** [comment]
@dvzrv As u say, i unistalled pipewire-jack-dropin, then it works! and my cadence also works. so excited, thanks!
