### ISSUE TITLE
using wrapper function

### ISSUE THREAD

**Issue by ihsinme** [jackaudio/jack2#795]
I think this is a wrapper function created for just such places.
https://github.com/jackaudio/jack2/blob/1ab3445e65ec2bfc1ba8562984822616e03fb9fe/posix/JackNetUnixSocket.cpp#L32

I think this is quite simple and safer than calling `gethostname` directly
https://github.com/jackaudio/jack2/blob/1ab3445e65ec2bfc1ba8562984822616e03fb9fe/posix/JackNetUnixSocket.cpp#L146

**Comment by ihsinme** [comment]
friendly ping

**Comment by falkTX** [comment]
Do I see a pull request coming? :)

**Comment by ihsinme** [comment]
https://github.com/jackaudio/jack2/pull/796

**Comment by falkTX** [comment]
Thanks for the PR!
