### ISSUE TITLE
Distorted sound on Raspberry Pi 4b

### ISSUE THREAD

**Issue by peter-vanpoucke** [jackaudio/jack2#809]
## Describe the bug

Playing a song through *jack* with *mpv* on a Raspberry Pi 4B results in a distorted sound on the headphones output. Playing the same file with *aplay* is fine. Playing the song through *jack* on *Windows* also is.

## Environment

* **JACK Version:** `jackdmp version 1.9.17 tmpdir /dev/shm protocol 8`
* **Operating System:** `Linux <hostname> 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux`
* **Installation:** package manager

## Steps To Reproduce

```bash
jackd -R -d alsa -r 44100 -P hw:0 -C hw:0 -i 2 -S
mpv -ao=jack song.wav
```

### Expected vs. actual behavior

Sound comes out distorted. No error is shown.

**Comment by falkTX** [comment]
the `-S` there means it is using 16bit, what if you remove that?

did you confirm that raw alsa with the same exact format (stereo 16bit 44.1kHz) has no distorted sound?

**Comment by peter-vanpoucke** [comment]
The file is a WAV in 44.1kHz, 16 bit and 2 channels.

aplay shows:
```
$ aplay -v song.wav
Playing WAVE 'song.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
ALSA <-> PulseAudio PCM I/O Plugin
Its setup is:
  stream       : PLAYBACK
  access       : RW_INTERLEAVED
  format       : S16_LE
  subformat    : STD
  channels     : 2
  rate         : 44100
  exact rate   : 44100 (44100/1)
  msbits       : 16
  buffer_size  : 22050
  period_size  : 5512
  period_time  : 125000
  tstamp_mode  : NONE
  tstamp_type  : GETTIMEOFDAY
  period_step  : 1
  avail_min    : 5512
  period_event : 0
  start_threshold  : 22050
  stop_threshold   : 22050
  silence_threshold: 0
  silence_size : 0
  boundary     : 1445068800
```
mpv to jack:
```
$ mpv -ao=jack song.wav
[ffmpeg/demuxer] wav: Discarding ID3 tags because more suitable tags were found.
 (+) Audio --aid=1 (pcm_s16le 2ch 44100Hz)
File tags:
Curator: _
Copyright: Creative Commons Attribution-NonCommercial-NoDerivatives 4.0: http://creativecommons.org/licenses/by-nc-nd/4.0/
 Date: 2018-06-13T14:24:50
 Title: Face the Sun
 Track: 8
AO: [jack] 44100Hz stereo 2ch floatp
```

Not sure if the floatp is fine?

**Comment by falkTX** [comment]
hmm this is going through pulseaudio, so not really raw alsa and not possible to compare as-is.
you will have to disable pulseaudio to get a real comparison.
and also bump the buffer size of jack quite considerably, to 4096 or 8192 frames.

**Comment by peter-vanpoucke** [comment]
It looks like it's really related to the Headphone output of the Raspberry Pi. Could simulate it an on another device that was still on Buster. On that one it works to play the audio through HDMI. Something's blocking it on Bullseye, but that's also the case in MPV.

But it does work with mpv through Alsa: [mpv to HP @ 202111131538.log](https://github.com/jackaudio/jack2/files/7532246/mpv.to.HP.%40.202111131538.log)

It does work when playing through a USB device, so I have a workaround for now.

The thing about the distorted sound is that I can here something that sounds like it, but lower/shifted and with some ringing.

**Comment by peter-vanpoucke** [comment]
Dug a little deeper and with `jackd -R -d alsa -r 41000 -P hw:0 -i 2 -S`, Alsa's `/proc/asound/card0/pcm0p/sub0/hw_params` had:
```text
access: MMAP_INTERLEAVED
format: S16_LE
subformat: STD
channels: 8
rate: 41000 (41000/1)
period_size: 1024
buffer_size: 2048
```
Since it's a stereo output, the 8 channels isn't ideal.

So `jackd -R -d alsa -r 41000 -P hw:0 -o 2 -S` on the other hand only has two and the sound is ... OK! :man_facepalming:

Should have checked all params first, sorry for bothering.

**Comment by yeeking** [comment]
I just encountered this on raspberry pi 2 and 3 models. The -o option solved it. This is a real pain for anyone running jackd on a pi as the default (no -o)  behaviour is to generate distorted sound. 

Will drop this -o info onto the supercollider readme page for raspberry pi.
