### ISSUE TITLE
Ableton Connection Not Working M1 Mac

### ISSUE THREAD

**Issue by jaymothra** [jackaudio/jack2#812]
Can not for the life of me figure out how to get this to work.

I am on Mac OS Monterey, installed Jack2 from the binary releases, picked universal for M1. Using the QJackCtl, I follow the instructions below, set up my Scarlett 2i2, and when I hit run QJackCtl asks me if I want to use the microphone. I say yes, but I still am unable to get Ableton to recognize Jack. I've linked the instructions I've used below. It really seems rather difficult to get relevant and concise info about how to actually use Jack so I'd appreciate the help.

https://linuxaudio.github.io/libremusicproduction/html/articles/demystifying-jack-%E2%80%93-beginners-guide-getting-started-jack

**Comment by falkTX** [comment]
Ableton does not support JACK. But Bitwig does
