### ISSUE TITLE
Unable to run connect to jack using runuser

### ISSUE THREAD

**Issue by worikgh** [jackaudio/jack2#817]
I am connecting to `jack` through `mod-host` (a LV2 host)

If I run `mod-host` as an unprivileged user (`patch` in this case) all is fine.
If I run `mod-host` from a script being run by root  using `runuser` I get the error:
```
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
```

Helpfully strace tells me what cannot be found:

`connect(3, {sa_family=AF_UNIX, sun_path="/dev/shm/jack_default_1000_0"}, 110) = -1 ENOENT (No such file or directory)`

The directory `/dev/shm` does not contain the socket `jack_default_1000_0`

/dev/shm contains....  

```
  -rw-rw----  1 jack jack 82287136 Dec  3 14:20 jack-110-0
  -rw-rw----  1 jack jack     1240 Dec  3 14:20 jack-110-1
  srw-rw----  1 jack jack        0 Dec  3 14:20 jack_default_0
  -rw-rw----  1 jack jack       12 Dec  3 14:20 jack_sem.default_freewheel
  -rw-rw----  1 jack jack       12 Dec  3 14:20 jack_sem.default_system
  -rw-rw-rw-  1 jack jack    70744 Dec  3 08:49 jack-shm-registry
```

I am in a position where I must run `mod-host` from a script that is running as `root`
I am inexperienced with the issues of switching user and have reached my limit - can anybody here help?

**Comment by falkTX** [comment]
jack and clients must run as the same user.

**Comment by worikgh** [comment]
No.  The problem (I solved with a kind person from  blokas.io was the environment getting cleared by `runuser`

Particularly: `JACK_PROMISCUOUS_SERVER=jack`

```
#!/bin/bash                                                                                                                                                              
export JACK_PROMISCUOUS_SERVER=jack
export LV2_PATH=/usr/modep/lv2
runuser  --preserve-environment -u patch  /usr/bin/mod-host
```
