### ISSUE TITLE
Build breaks on powerpc64le

### ISSUE THREAD

**Issue by pkubaj** [jackaudio/jack2#839]
## Describe the bug

Build breaks on powerpc64le due to https://github.com/jackaudio/jack2/commit/dff7fa4fa8d25a8d3f21f4445a6496fd263e4a52

## Environment

* **JACK Version:** 1.9.20
* **Operating System:** FreeBSD 13.0-RELEASE
* **Installation:** ports tree

## Steps To Reproduce

Try to build on powerpc64le.

### Expected vs. actual behavior
```
[  3/181] Compiling common/JackDebugClient.cpp
09:13:58 runner ['c++', '-O2', '-pipe', '-fPIC', '-fstack-protector-strong', '-fno-strict-aliasing', '-Wall', '-Wno-invalid-offsetof', '-std=gnu++11', '-fPIC', '-Ifreebsd', '-I../freebsd', '-Iposix', '-I../posix', '-Icommon', '-I../common', '-Icommon/jack', '-I../common/jack', '-I.', '-I..', '-I../compat/alloca', '-I/usr/local/include/opus', '-I/usr/local/include', '-I/usr/local/include/dbus-1.0', '-I/usr/local/lib/dbus-1.0/include', '-DEXECINFO=1', '-DHAVE_LIBSYSINFO=1', '-DHAVE_DOXYGEN=0', '-DHAVE_ALSA=0', '-DHAVE_FIREWIRE=0', '-DHAVE_IIO=0', '-DHAVE_PORTAUDIO=0', '-DHAVE_WINMME=0', '-DHAVE_CELT=0', '-DHAVE_EXAMPLE_TOOLS=0', '-DHAVE_OPUS_OPUS_CUSTOM_H=1', '-DHAVE_OPUS_PKG=1', '-DHAVE_OPUS=1', '-DHAVE_SAMPLERATE=1', '-DHAVE_SNDFILE=0', '-DHAVE_READLINE=0', '-DHAVE_SYSTEMD=0', '-DHAVE_DB_H=1', '-DHAVE_DB=0', '-DHAVE_ZALSA=0', '-DHAVE_PPOLL=1', '-DHAVE_EXECINFO_H=1', '-DJACK_VERSION="[]"', '-DHAVE_DBUS_1=1', '-DHAVE_EXPAT=1', '-DUSE_LIBDBUS_AUTOLAUNCH=1', '-DCLIENT_NUM=256', '-DPORT_NUM_FOR_CLIENT=2048', '-DADDON_DIR="/usr/local/lib/jack"', '-DJACK_LOCATION="/usr/local/bin"', '-DUSE_POSIX_SHM=1', '-DJACKMP=1', '-DJACK_DBUS=1', '-DHAVE_CONFIG_H', '-DSERVER_SIDE', '../common/JackDebugClient.cpp', '-c', '-o/wrkdirs/usr/ports/audio/jack/work/jack2-1.9.20/build/common/JackDebugClient.cpp.2.o', '-I/usr/local/include']
In file included from ../common/JackDebugClient.cpp:21:
../common/JackEngineControl.h:67:5: error: requested alignment is less than minimum alignment of 8 for type 'Jack::JackTransportEngine'
    alignas(UInt32) JackTransportEngine fTransport;
    ^
../common/JackEngineControl.h:89:5: error: requested alignment is less than minimum alignment of 8 for type 'Jack::JackFrameTimer'
    alignas(UInt32) JackFrameTimer fFrameTimer;
    ^
2 errors generated.
```

**Comment by 0EVSG** [comment]
Additional info: It does build with GCC. And there's also a [report](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=261508) of it failing on Arm64, but only with the base compiler in FreeBSD 14.0-CURRENT which corresponds to llvm 13.0.0. Arm64 on FreeBSD 13.0-RELEASE builds fine though, the base compiler there is llvm 11.0.1.

I tried to reproduce this with cross-compilation, both on 13.0-RELEASE and FreeBSD 14.0-CURRENT, and for both Arm64 and PowerPC. No luck.

IMHO there's no inherent or architectural reason for the compiler to require 8 byte alignment here, neither for Arm64 nor PowerPC64. I suspect this to be a platform specific compiler issue.

@pkubaj: Did you try with any of the llvm* from ports? I'm the maintainer of the audio/jack port, BTW.
