### ISSUE TITLE
graph is blurry on high DPI macOS

### ISSUE THREAD

**Issue by Be-ing** [jackaudio/jack2#847]
## Describe the bug

The connection graph in the QJackCtl build shipped with the macOS version of JACK does not scale well for high DPI screens.

## Environment

* **JACK Version:** 1.9.20
* **Operating System:** macOS 11.5.2
* **Installation:** https://jackaudio.org/downloads

## Steps To Reproduce

Open QJackCtl distributed with JACK on macOS and click the Graph button

### Expected vs. actual behavior

Everything within the graph is blurry but the text at the top of the window scales okay:
<img width="1134" alt="Screen Shot 2022-02-06 at 7 36 47 PM" src="https://user-images.githubusercontent.com/9455094/152711746-08d686d7-5819-43a7-b69a-1d109ada8727.png">

**Comment by falkTX** [comment]
you need to report that to qjackctl, not here.
jack releases package qjackctl as-is for convenience of users, but the projects are quite unrelated, different people etc

**Comment by Be-ing** [comment]
Ah, I was under the impression it was a modified build of QJackCtl because the graph looks totally different on macOS versus Linux.

**Comment by Be-ing** [comment]
Reported to QJackCtl here: https://github.com/rncbc/qjackctl/issues/170

**Comment by Be-ing** [comment]
This issue [does not occur with QJackCtl from Homebrew](https://github.com/rncbc/qjackctl/issues/170#issuecomment-1031526735) which is built with Qt 6.2.2.

**Comment by falkTX** [comment]
Carla uses the same exact Qt version as the jack2 qjackctl packaged one and works fine for high-dpi setups.
so dont know then..

**Comment by Be-ing** [comment]
Qt5 high DPI scaling is opt-in and requires setting [Qt::AA_EnableHighDpiScaling](https://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt) before the Qt application starts. In Qt6 that was removed and scaling is always enabled.
