### ISSUE TITLE
Working with libjackserver on Windows

### ISSUE THREAD

**Issue by vrslev** [jackaudio/jack2#856]
`jackserver` library is shipped with official JACK package on Windows. But it is not installed in C:\Windows, so users can't use it in directory different from C:\Program Files [x86]\JACK2. What is official way to use this lib?

**Comment by falkTX** [comment]
There are very little uses for linking to jackserver. But the library is not put in %windir% simply because it was not necessary, so I assume you have a usecase here?
Are you developing a new opensource jack control type of gui?

**Comment by vrslev** [comment]
I’m making a wrapper around JACK and JackTrip for audio networking using Python. For purpose of controlling JACK server I created Python package [`jack_server`](https://github.com/vrslev/jack_server) — it uses jackserver lib.

**Comment by falkTX** [comment]
ah then on python you can just use registry entires to find the location of jack2.
see https://github.com/jackaudio/jack2/blob/develop/windows/inno/win64.iss#L70

**Comment by vrslev** [comment]
Thanks! I ended up using Linux anyway 😃
