### ISSUE TITLE
MIDI on Windows is broken 

### ISSUE THREAD

**Issue by dunkfordyce** [jackaudio/jack2#892]
I am using `jackd -S -X winmme` on windows. I have no external MIDI devices. In messages I get the following error 

`JackWinMMEDriver::Open - while creating output port: Undefined external error. | winmme, system_midi, out`

Googling this error suggests the port is in use. I have checked all my services and nothing should be using MIDI. This maybe correct as I think jack does not actually do its own virtual midi routing?

I have tried virtual midi devices such as loopbe and loopMIDI. loopbe does not work at all. loopMidi shows some virtual devices but does then not work for my use case: using SuperCollider when I create a midi output it does not show up in jackctrl graph editor or in Carla's external devices display. If I do not use jack the midi output from SuperCollider is shown in Carla. 

If its relevant I am also using ASIO4ALL driver.

**Comment by dunkfordyce** [comment]
Looking at issue #558 and the code in https://github.com/jackaudio/jack2/blob/852ba2b8ebc944865e75d8eb5d4550d408772f3b/windows/winmme/JackWinMMEDriver.cpp it seems like jack does not monitor port changes and only creates them on startup which could explain the problems..?

**Comment by dunkfordyce** [comment]
I got this working - I think I was confused.

**Comment by pcmkr929** [comment]
@dunkfordyce Would you also have the goodwill to tell us how you solved it?
