### ISSUE TITLE
Updating from 1.9.17 to 1.9.21 introduces Ardour segfault

### ISSUE THREAD

**Issue by martinsolberg** [jackaudio/jack2#893]
## Describe the bug

Ardour 6.9 was running stably until recently, when it started randomly crashing with segfault. Seems to be related to a recent Jack update. Reverting to the previous Jack package seems to solve the issue.

## Environment

* **JACK Version:** 1.9.21
* **Operating System:** MX Linux 21 (Debian stable)
* **Installation:** MX Linux 21 apt repos 

## Steps To Reproduce

Run an empty Ardour project connected to Jack. The segfault occurs after a short period of time (<15 minutes). Throws the following error message in the kernel log:
`kernel: audioengine[3370]: segfault at 229789b2c0 ip 00007f185d7b7e1b sp 00007f1822318a30 error 4 in libardour.so.3[7f185cfd3000+c58000]`

### Expected vs. actual behavior

Ardour was running stably on `1.9.17~dfsg-1`
Crashing on `1.9.21~dfsg-1~mx21+1`
Reverting to `1.9.17~dfsg-1` remedies the issue

**Comment by falkTX** [comment]
I dont think those 2 are comparable, since they come from different sources.
Issue could be jack2 changes, or something within the new packages.

Would be great if you could have the option for older jack built in the same way as the new mx stuff.
So it reduces the amount of variables at play here.

**Comment by martinsolberg** [comment]
Never mind, it still segfaulted, only it took a lot longer on the older Jack version (half a day vs 5-15 minutes). Guess I will need to debug Ardour.
