### ISSUE TITLE
RFC: is it valid to use a port after jack_port_unregister() has been called?

### ISSUE THREAD

**Issue by pobrn** [jackaudio/jack2#897]
This is a request for clarification due to an issue reported to the pipewire bug tracker: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2638

[`tests/test.cpp` has the following lines](https://github.com/jackaudio/jack2/blob/99e5d115ea47f6673ef741ce5633e57661f63510/tests/test.cpp#L1767):
```cpp
    jack_port_unregister(client1, output_port1b);

    if (jack_port_name(output_port1b) != NULL ) {
```

Could someone confirm if this is allowed?

**Comment by falkTX** [comment]
It is clear from the rest of the code.

```
    if (jack_port_name(output_port1b) != NULL ) {
        printf("!!! WARNING !!! port_name return something while the port have been unregistered !\n");
        printf("!!! Name of unregistered port : %s !\n", jack_port_name(output_port1b));
    } else {
        Log("Checking jack_port_name() with a non valid port... ok\n");
    }
```

so `jack_port_name` with a unregistered port must return null

**Comment by pobrn** [comment]
Thanks for the quick reply.
