### ISSUE TITLE
jack crashes client if v mem exhausted - mmap() failure

### ISSUE THREAD

**Issue by AlexandruCostache** [jackaudio/jack2#90]
If the client uses up almost all of its virtual memory jack may crash it in common/JackShmMem.h:

The destructor for JackShmReadWritePtr is called although Init() failed and it will call GetShmAddress()->UnlockMemory(); 

The fastest sollution that solved my issue was to add another flag member, initDone and set it to TRUE in Init() right after locking memory so that GetShmAddress()->UnlockMemory() doesn't do an illegal access.

I'm not familiar with jackd so I'm asking: is this approach acceptable/safe or is there a better way to handle this mmap() failure?

**Comment by AlexandruCostache** [comment]
Sure, here it is: https://www.dropbox.com/s/5qv5dr938c54d8q/0001-Avoid-crashing-client-when-mmap-fails.patch?dl=0

**Comment by sletz** [comment]
Le 7 janv. 2015 à 14:43, AlexandruCostache <notifications@github.com> a écrit :

> If the client uses up almost all of its virtual memory jack may crash it in common/JackShmMem.h:


1) Does "Init" really crash or does it call " throw std::bad_alloc();" ?

2) or does it crash in GetShmAddress()->LockMemory()  ?

> 
> The destructor for JackShmReadWritePtr is called although Init() failed and it will call GetShmAddress()->UnlockMemory();
> 
> The fastest sollution that solved my issue was to add another flag member, initDone and set it to TRUE in Init() right after locking memory so that GetShmAddress()->UnlockMemory() doesn't do an illegal access.
> 
> I'm not familiar with jackd so I'm asking: is this approach acceptable/safe or is there a better way to handle this mmap() failure?


Stéphane=

**Comment by AlexandruCostache** [comment]
Crashes in destructor, ~JackShmReadWritePtr(), to be more specific in GetShmAddress()->UnlockMemory()

**Comment by AlexandruCostache** [comment]
GetShmAddress() does not have a valid address because Init() failed previously. If this class in not used for iterators then that patch should do just fine.

**Comment by sletz** [comment]
No the question is : how the call to Init fails in the first place? where in the code of Init does it fails ? (calling throw std::bad_alloc(), or chasing in   GetShmAddress()->LockMemory();)

Thanks

Stéphane

**Comment by AlexandruCostache** [comment]
It failed trough bad_alloc

**Comment by sletz** [comment]
Could you possibly try the bit more general patch here :



Stéphane

**Comment by AlexandruCostache** [comment]
I'm not seeing the patch, looks like the link doesn't appear

**Comment by sletz** [comment]
Give me your direct mail address.

Stéphane

**Comment by AlexandruCostache** [comment]
It's the one in the patch I've provided. Not posting it here due to spamming considerations. Thanks

**Comment by AlexandruCostache** [comment]
Took it for a spin and it behaves ok

**Comment by sletz** [comment]
Thanks commited and pushed on go.

Stéphane

**Comment by AlexandruCostache** [comment]
Thank you!
