### ISSUE TITLE
I need to build without MIDI

### ISSUE THREAD

**Issue by worikgh** [jackaudio/jack2#906]
## Summary

I need to build Jack without any support for MIDI

### Motivation

I use Jack exclusively for audio

I am building Jack locally because it is filling up my error logs then failing in mysterious ways, and I wish to diagnose the issues (and if possible I will report any I find)

Jack MIDI connections are a distraction, I do not know why Jack is involved with MIDI

**Comment by falkTX** [comment]
You can just ignore them.

JACK has transport, latency information, DB for client and port properties, network transmission utilities and other things.
You dont have to make use of it all, just ignore the things you dont need.
