### ISSUE TITLE
jackdrc and device names with whitespace

### ISSUE THREAD

**Issue by x42** [jackaudio/jack2#91]
on OSX devices can include whitespace.
e.g. "AppleUSBAudioEngine:Focusrite:Scarlett 18i6 USB:000039BF:2,1"
"AppleUSBAudioEngine:PreSonus:AudioBox 1818 VSL:2209:2,1" etc

The parser in posix/JackPosixServerLaunch.cpp does not handle quotes nor escapes. jack cannot be started by a jackdrc if the device-name contains spaces. NB. The jackdrc parser in JackWinServerLaunch.cpp does handle things correctly.

**Comment by sletz** [comment]
Patch?

Stéphane

**Comment by x42** [comment]
There's no patch, yet. Just filing the issue so that it does not get lost.

I suppose it could be as easy as copy/edit from `JackWinServerLaunch` to `JackPosixServerLaunch`. But that may break compatibility with jack1 .jackdrc.

**Comment by x42** [comment]
https://github.com/x42/jack2/commit/886a64e02a0f7ce192c318f74cff1f16d5e15bfb

I'll file a pull request
