### ISSUE TITLE
SIG32 Real-time event while using functions 'jack_deactivate'  & 'jack_client_close'

### ISSUE THREAD

**Issue by ArtemRotov** [jackaudio/jack2#914]
Good day! While upgrading my Debian 9 based OS to a Debian 10 based OS, I had problems with my jackd2 based program. 
I'm getting very strange behavior for which I can't find the cause. When working without a debugger, the behavior of the program does not raise any questions and it is fully functional.
However, when working with the debugger, it constantly catches exceptions like  "**SIG32   Real-time event 32**" when calling two functions (maybe more than 2, but I have not observed any more), namely "**jack_deactivate**" and "**jack_client_close**". But I ask you to note that this does not stop the program, and if you continue debugging, then the program remains fully functional.

Jackd2 version changed from 1.9.10 to 1.9.12 after operating system change
OS based on Debain 10.
Jackd2 was installed via apt from debian repositories.

The call stack is very limited and is the following list:
```
1. syscall  (syscall.S   line 38)            <<< EXCEPTION HERE
2. ??
3. ??
4. ??
5. ??
6. ??
7. start_thread   (pthread_create.c   line 486)
8. clone   (clone.S    line 95)
```
And Disassembler code (syscall)
```
30 [1]	in ../sysdeps/unix/sysv/linux/x86_64/syscall.S
0x7ffff62f19d0                  48 89 f8              mov    %rdi,%rax
        31 [1]	in ../sysdeps/unix/sysv/linux/x86_64/syscall.S
0x7ffff62f19d3  <+    3>        48 89 f7              mov    %rsi,%rdi
        32 [1]	in ../sysdeps/unix/sysv/linux/x86_64/syscall.S
0x7ffff62f19d6  <+    6>        48 89 d6              mov    %rdx,%rsi
        33 [1]	in ../sysdeps/unix/sysv/linux/x86_64/syscall.S
0x7ffff62f19d9  <+    9>        48 89 ca              mov    %rcx,%rdx
        34 [1]	in ../sysdeps/unix/sysv/linux/x86_64/syscall.S
0x7ffff62f19dc  <+   12>        4d 89 c2              mov    %r8,%r10
        35 [1]	in ../sysdeps/unix/sysv/linux/x86_64/syscall.S
0x7ffff62f19df  <+   15>        4d 89 c8              mov    %r9,%r8
        36 [1]	in ../sysdeps/unix/sysv/linux/x86_64/syscall.S
0x7ffff62f19e2  <+   18>        4c 8b 4c 24 08        mov    0x8(%rsp),%r9
        37 [1]	in ../sysdeps/unix/sysv/linux/x86_64/syscall.S
0x7ffff62f19e7  <+   23>        0f 05                 syscall
        38 [1]	in ../sysdeps/unix/sysv/linux/x86_64/syscall.S
0x7ffff62f19e9  <+   25>        48 3d 01 f0 ff ff     cmp    $0xfffffffffffff001,%rax               
        39 [1]	in ../sysdeps/unix/sysv/linux/x86_64/syscall.S
0x7ffff62f19ef  <+   31>        73 01                 jae    0x7ffff62f19f2 <syscall+34>
        40 [1]	in ../sysdeps/unix/sysv/linux/x86_64/syscall.S
0x7ffff62f19f1  <+   33>        c3                    retq
        42 [1]	in ../sysdeps/unix/sysv/linux/x86_64/syscall.S
0x7ffff62f19f2  <+   34>        48 8b 0d 77 64 0c 00  mov    0xc6477(%rip),%rcx        # 0x7ffff63b7e70
0x7ffff62f19f9  <+   41>        f7 d8                 neg    %eax
0x7ffff62f19fb  <+   43>        64 89 01              mov    %eax,%fs:(%rcx)
0x7ffff62f19fe  <+   46>        48 83 c8 ff           or     $0xffffffffffffffff,%rax
0x7ffff62f1a02  <+   50>        c3                    retq
```
Exception on :
  ```
        38 [1]	in ../sysdeps/unix/sysv/linux/x86_64/syscall.S
0x7ffff62f19e9  <+   25>        48 3d 01 f0 ff ff     cmp    $0xfffffffffffff001,%rax       
```  

This is all the information that I can provide at the moment. I will be grateful for any help and advice. 
Thank you!

**Comment by falkTX** [comment]
this is not an issue, realtime events are expected.
tell the debugger to ignore them and proceed as usual

**Comment by ArtemRotov** [comment]
> this is not an issue, realtime events are expected. tell the debugger to ignore them and proceed as usual

Very thanks! I didn't get this event in the past and didn't know how to proceed. Thank you
I added a `~/.gdbinit ` file with the following content:
`handle SIG32 nostop noprint pass`
