### ISSUE TITLE
Windows installer intercepted by McAfee LiveSafe

### ISSUE THREAD

**Issue by escuta** [jackaudio/jack2#917]
## Describe the bug

Not a bug but an issue. I'm unable to install Jack on a Windows 11 Home Single Language machine with McAfee LiveSafe installed. When trying to launch the installer McAfee detects a virus (true or not) and deletes the installer.

## Environment

* **JACK Version:** Which version of jack2 are you using? (e.g. the output of `jackd --version` or a git commit checksum)
* **Operating System:** What operating system or distribution in which version are you using? (e.g. Linux, macOS, Windows)
* **Installation:** How did you install jack2? (e.g. package manager, from source)

64bit installer: [JACK 1.9.22 win64](https://github.com/jackaudio/jack2-releases/releases/download/v1.9.22/jack2-win64-v1.9.22.exe).
Windows 11 

## Steps To Reproduce
As above
### Expected vs. actual behavior

A clear and concise description of what you expected to happen vs. what happened.

See above

**Comment by falkTX** [comment]
those antiviruses are more of a scam than anything else.
pretty much any binary generated by mingw is being falsely flagged with a virus.
nothing to do here from jack2 side

**Comment by escuta** [comment]
ah, ok, thanks, thought that was probably the case
