### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [jackaudio/jack2#928]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by falkTX** [comment]
this spam is getting out of hand. if you want to report a bug just report it, dont open tickets on a bunch of repos at once saying exactly the same thing.

FYI the copy&paste makes me think you are just a spam account, will report it to github.
