### ISSUE TITLE
alsa_in crashes when connected to bluetooth SCO alsa PCM device

### ISSUE THREAD

**Issue by mike7c2** [jackaudio/jack2#93]
We are working to integrate a bluetooth headset with a system which uses jackd2 for the audio transport.

We found that alsa_in would regularly crash and provide choppy audio whatever settings we used. Unfortunately I don't have access to equipment to provide a detailed bug report just now, this can provided on request.

Attached is a source file bt_alsa_in.c which worked for us. The settings are hardcoded so it would require minor modification to make it generally useable, the main difference is that alsa work is carried out in the programs main thread instead of on the jack callback. It also doesn't contain the algorithm to deal with subtle rate differences, this implementation will lose a frame every once in a while if the input and output streams are not synchronised.

We could not find a copyright notice for the alsa_in file so we aren't sure where/whether to submit it. We would be happy to make it a more general solution and submit it back to the project. The GIST links to the source, I just added the LGPL copyright notice because I wasn't sure what else to do!

https://gist.github.com/mike7c2/3c4825278c0217d7f8a0

Cheers,
Mike

**Comment by mseeber** [comment]
Instead of alsa_in, you could just use zita-ajbridge which is superior to alsa_in/alsa_out in many aspects.
(see http://kokkinizita.linuxaudio.org/linuxaudio/zita-ajbridge-doc/quickguide.html )

**Comment by 7890** [comment]
@mike7c2 the jack_process_callback in the GIST is indeed very lean, thanks for the contribution.

"this implementation will lose a frame every once in a while" -> does this introduce clicks in the stream?

Have you tried the headset with zita-ajbridge as suggested by @mseeber? Chances are good that it will work fine.  It will (hopefully) replace the alsa_in/out anytime in the future.

I will close this issue for now - Please feel free to open a pull request if you'd like to add the code as another example client (with no guarantee that it will be merged).
