### ISSUE TITLE
Human readable Jack MIDI device names

### ISSUE THREAD

**Issue by agraef** [jackaudio/jack2#944]
## Summary

Please make the Jack2 MIDI device names reflect their ALSA names, so that it's easier to figure out what ALSA MIDI device you're working with.

### Basic example

I have a bunch of MIDI devices connected to my desktop Linux PC, the ALSA MIDI devices look like this in qjackctl:

![image](https://github.com/jackaudio/jack2/assets/2853977/909140f9-e14f-4e2d-b689-1f34618696c2)

Here's how the Jack MIDI devices look like in qjackctl with the raw or seq MIDI drivers:

![image](https://github.com/jackaudio/jack2/assets/2853977/d1464434-147a-4c47-8fb9-86d61875c573)

Here's how they look like with `a2jmidid -e`:

![image](https://github.com/jackaudio/jack2/assets/2853977/4c91a1d9-285d-4567-8eb5-3aee454952d7)

Much better. :) IIRC, with Jack1 the Jack MIDI device names also reflected the ALSI MIDI names, and pipewire also displays the proper ALSA names in its Jack MIDI Bridge.

### Motivation

I'm not sure whether that's a jack2 issue, or qjackctl is to blame. It's probably a bit of both, since qjackctl seems to be capable to display the real device names in its new graph window, but I'd really like to have this in qjackctl's connection window which I prefer. That's why I still use a2jmidid. I'd prefer to use jack2's built-in Jack MIDI driver, but those generic names are driving me bonkers. They just aren't of much use if you have more than 1-2 MIDI devices connected.

Maybe there's a reason for those generic device names, but I don't see it. I really consider this a serious usability issue. I've remained silent about it all those years, since I know that Stephane is busy with other things, but I think it's about time that this gets fixed, now that Jack2 is pretty much the default Jack implementation everywhere. :)

I haven't looked at the source yet, but if someone can point me at the code where those generic Jack MIDI port names are created, then I'll try to come up with something that generates proper names from the ALSA MIDI device names. But hopefully one of the Jack2 experts around here can help me out? Or explain to me why those generic device names are there?

**Comment by agraef** [comment]
Never mind, I just discovered that on qjackctl's Display tab in the Setup dialog, I can set the "JACK client/port aliases" to First or Second to get the proper device names shown in the connection window:

![image](https://github.com/jackaudio/jack2/assets/2853977/5340615c-6612-4616-9f9f-340e84b44e7e)

E.g., here is how the "Second" option looks like:

![image](https://github.com/jackaudio/jack2/assets/2853977/7f9ed43e-e8e4-483c-a3a6-9a0f13aee27a)

Anyway, it's not a bug, the information was there all along, I simply was too dumb to figure out how to have it shown in qjackctl. After all those years! :) Rui, you couldn't have hidden that setting much better. Maybe this should be in a FAQ somewhere...

**Comment by agraef** [comment]
Well, this didn't actually fix the issue. :( The prettier port names are shown in the connection window alright, but you can't make any connections there (well, you can, but they don't show up), and the qjackctl patchbay still stubbornly uses the generic names. So changing the display mode doesn't really work.

This now looks more like a qjackctl issue to me, so maybe I should report it to Rui instead. But I'm curious how everybody else deals with this, so I'm reopening the issue. After all, I never had to jump through these hoops with Jack1, so maybe Jack2 could adopt a MIDI device naming scheme that's more in line with Jack1 for better compatibility? Or is there a good reason that Jack2 uses these generic MIDI device names after all?

**Comment by agraef** [comment]
> Or is there a good reason that Jack2 uses these generic MIDI device names after all?

Maybe for consistency with the port naming of the system audio device? @sletz You wrote the thing, do you remember? :)

**Comment by agraef** [comment]
FWIW, here's how the Jack MIDI ports are shown in qjackctl's connection window with Jack1:

![image](https://github.com/jackaudio/jack2/assets/2853977/07aba8f5-2652-440d-a217-226de0561dfa)

This is with the built-in bridge (-Xseq), default display settings. Setting the connections works and they are displayed properly, and the same readable port names are also shown in qjackctl's patchbay and the graph display. That's how I'd like it to be in Jack2 as well. It should be just a matter of reworking the port naming in alsa{raw,seq}midi.c so that it uses the aliases being generated there as the actual device names, no?

**Comment by agraef** [comment]
Ok, this is how far I got with https://github.com/agraef/jack2/commit/71c9e64019a45c363cfedfec5f3ff9d5f2d9a1cc:

![image](https://github.com/jackaudio/jack2/assets/2853977/bc1f3a99-ff77-4dd9-964d-be24ccac4095)

This is already a lot better, but not quite there yet. I'd really like to have the proper ALSA port names in there as well, so I tried using the same naming scheme as in Jack1, but that would produce garbled port names, and I'm not sure why.

So it seems feasible at least. What now? If I'm going to embark on turning this into a PR, I'd like to have at least a word from the developers that this is going to be considered. I see lots of open PRs already in the backlogs, and I don't want to waste any time on something that's never going to be accepted anyway.

**Comment by falkTX** [comment]
Debian has a tentative patch at this, which as far as I know has not been sent upstream as PR.
It is not enabled but they still ship with it in the debian source, do not know the details for it.

Attaching it here for easy reference:

```diff
--- /dev/null
+++ b/linux/alsa/port_names.c
@@ -0,0 +1,179 @@
+/* -*- mode: c; c-file-style: "linux"; -*- */
+/*
+    Copyright (C) 2010 Florian Faber, faber@faberman.de
+
+    This program is free software; you can redistribute it and/or modify
+    it under the terms of the GNU General Public License as published by
+    the Free Software Foundation; either version 2 of the License, or
+    (at your option) any later version.
+
+    This program is distributed in the hope that it will be useful,
+    but WITHOUT ANY WARRANTY; without even the implied warranty of
+    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+    GNU General Public License for more details.
+
+    You should have received a copy of the GNU General Public License
+    along with this program; if not, write to the Free Software
+    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
+
+*/
+
+
+#include <math.h>
+#include <stdio.h>
+#include <memory.h>
+#include <unistd.h>
+#include <stdlib.h>
+#include <errno.h>
+#include <stdarg.h>
+#include <signal.h>
+#include <sys/types.h>
+#include <regex.h>
+#include <string.h>
+
+#include "alsa_driver.h"
+
+
+static int port_names_load_portfile(alsa_driver_t *driver, const char *filename, char **buf, const unsigned int offset, const unsigned int num) {
+	int fh, i, ret, lineno, id, res=0;
+	char line[256];
+
+	printf("Trying to load portnames from %s\n", filename);
+	fh = open(filename, O_RDONLY);
+	if (-1!=fh) {
+		res = 1;
+		i = 0;
+		lineno = 1;
+		for (;;) {
+			ret = read(fh, &line[i], 1);
+			if (0==ret) {
+				break;
+			} else if (-1==ret) {
+				sprintf(stderr, "Error while reading \"%s\": %s", filename, strerror(errno));
+				break;
+			}
+			if (0x0A==line[i]) {
+				/* new line, parse input */
+				line[i] = 0;
+
+				if ('#' != line[0]) {
+					i=0;
+					while ((i<255) && (line[i]!='=')) i++;
+					if (255==i) {
+						sprintf(stderr, "Error while reading \"%s\": Line %d has no key=value syntax!", filename, lineno);
+					} else {
+						line[i] = 0;
+						id = atoi(line);
+						if ((id>=1) && (id<=num)) {
+							if (NULL==buf[id-1+offset]) {
+								/* don't overwrite existing names */
+								buf[id-1+offset] = strdup(&line[i+1]);
+							}
+						} else {
+							sprintf(stderr, "Error while reading \"%s\": Key %d out of range in line %d (1..%d)", filename, id, lineno, num);
+						}
+					}
+				}
+
+				i = 0;
+				lineno++;
+			} else {
+				i++;
+				if (i==255) {
+					sprintf(stderr, "Error while reading \"%s\": Line %d is too long", filename, lineno);
+					break;
+				}
+			}
+		}
+
+		(void) close(fh);
+	}
+
+	return res;
+}
+
+
+static void port_names_default_portnames(char **buf, const unsigned int offset, const unsigned int num, const char *defaultname) {
+	unsigned int i;
+	char line[256];
+
+	/* Fill in default names */
+	for (i=0; i<num; i++) {
+		if (NULL==buf[i+offset]) {
+			snprintf(line, 255, defaultname, i+1);
+			buf[i+offset] = strdup(line);
+		}
+	}
+}
+
+
+char** port_names_get_portnames(alsa_driver_t *driver) {
+	snd_ctl_card_info_t *card_info;
+	int err;
+	const char *card_name = NULL;
+	char filename[256], *speed;
+	char **buf;
+
+	printf("Using port names patch v0.1 (07.04.2010)\n");
+
+	if (driver->frame_rate > 96000) {
+		speed="qs";
+	} else if (driver->frame_rate > 48000) {
+		speed="ds";
+	} else {
+		speed="ss";
+	}
+
+	snd_ctl_card_info_alloca(&card_info);
+	err = snd_ctl_card_info(driver->ctl_handle, card_info);
+	if (err >= 0) {
+		card_name = snd_ctl_card_info_get_name(card_info);
+	} else {
+		card_name = "noname";
+	}
+
+	buf = malloc(sizeof(char *)*(driver->capture_nchannels + driver->playback_nchannels));
+	if (NULL==buf) {
+		sprintf(stderr, "ALSA: Not enough memory for %d port names", driver->capture_nchannels + driver->playback_nchannels);
+		return NULL;
+	}
+	bzero(buf, sizeof(char *)*(driver->capture_nchannels + driver->playback_nchannels));
+
+	/* Read port names from special to general:
+	 * Begin with user and speed specific port names */
+	snprintf(filename, 255, "%s/.config/jack/cards/%s.%s.ports.in", getenv("HOME"), card_name, speed);
+	(void) port_names_load_portfile(driver, filename, buf, 0, driver->capture_nchannels);
+
+	/* Now user general */
+	snprintf(filename, 255, "%s/.config/jack/cards/%s.ports.in", getenv("HOME"), card_name);
+	(void) port_names_load_portfile(driver, filename, buf, 0, driver->capture_nchannels);
+
+	/* System speed specific */
+	snprintf(filename, 255, "/etc/jack/cards/%s.%s.ports.in", card_name, speed);
+	(void) port_names_load_portfile(driver, filename, buf, 0, driver->capture_nchannels);
+
+	/* System general */
+	snprintf(filename, 255, "/etc/jack/cards/%s.ports.in", card_name);
+	(void) port_names_load_portfile(driver, filename, buf, 0, driver->capture_nchannels);
+
+	/* Fill all still unnamed ports with default names */
+	port_names_default_portnames(buf, 0, driver->capture_nchannels, "capture_%lu");
+
+
+	/* Same procedure for the playback channels */
+	snprintf(filename, 255, "%s/.config/jack/cards/%s.%s.ports.out", getenv("HOME"), card_name, speed);
+	(void) port_names_load_portfile(driver, filename, buf, driver->capture_nchannels, driver->playback_nchannels);
+
+	snprintf(filename, 255, "%s/.config/jack/cards/%s.ports.out", getenv("HOME"), card_name);
+	(void) port_names_load_portfile(driver, filename, buf, driver->capture_nchannels, driver->playback_nchannels);
+
+	snprintf(filename, 255, "/etc/jack/cards/%s.%s.ports.out", card_name, speed);
+	(void) port_names_load_portfile(driver, filename, buf, driver->capture_nchannels, driver->playback_nchannels);
+
+	snprintf(filename, 255, "/etc/jack/cards/%s.ports.out", card_name);
+	(void) port_names_load_portfile(driver, filename, buf, driver->capture_nchannels, driver->playback_nchannels);
+
+	port_names_default_portnames(buf, driver->capture_nchannels, driver->playback_nchannels, "playback_%lu");
+
+	return buf;
+}
--- /dev/null
+++ b/linux/alsa/port_names.h
@@ -0,0 +1,34 @@
+/*
+    Copyright (C) 2010 Florian Faber, faber@faberman.de
+
+    This program is free software; you can redistribute it and/or modify
+    it under the terms of the GNU General Public License as published by
+    the Free Software Foundation; either version 2 of the License, or
+    (at your option) any later version.
+
+    This program is distributed in the hope that it will be useful,
+    but WITHOUT ANY WARRANTY; without even the implied warranty of
+    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+    GNU General Public License for more details.
+
+    You should have received a copy of the GNU General Public License
+    along with this program; if not, write to the Free Software
+    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
+
+*/
+
+#ifndef __jack_port_names_h__
+#define __jack_port_names_h__
+
+#ifdef __cplusplus
+extern "C"
+{
+#endif
+
+char** port_names_get_portnames(alsa_driver_t *driver);
+
+#ifdef __cplusplus
+}
+#endif
+
+#endif /* __jack_port_names_h__ */
--- a/linux/alsa/JackAlsaDriver.cpp
+++ b/linux/alsa/JackAlsaDriver.cpp
@@ -43,6 +43,7 @@
 #include "JackPosixThread.h"
 #include "JackCompilerDeps.h"
 #include "JackServerGlobals.h"
+#include "port_names.h"
 
 namespace Jack
 {
@@ -72,6 +73,8 @@
     unsigned long port_flags = (unsigned long)CaptureDriverFlags;
     char name[JACK_CLIENT_NAME_SIZE + JACK_PORT_NAME_SIZE];
     char alias[JACK_CLIENT_NAME_SIZE + JACK_PORT_NAME_SIZE];
+    char old_name[JACK_CLIENT_NAME_SIZE + JACK_PORT_NAME_SIZE];
+    char **portnames;
     jack_latency_range_t range;
 
     assert(fCaptureChannels < DRIVER_PORT_NUM);
@@ -88,15 +91,20 @@
 
     jack_log("JackAlsaDriver::Attach fBufferSize %ld fSampleRate %ld", fEngineControl->fBufferSize, fEngineControl->fSampleRate);
 
+    portnames = port_names_get_portnames(alsa_driver);
+
     for (int i = 0; i < fCaptureChannels; i++) {
         snprintf(alias, sizeof(alias) - 1, "%s:%s:out%d", fAliasName, fCaptureDriverName, i + 1);
-        snprintf(name, sizeof(name) - 1, "%s:capture_%d", fClientControl.fName, i + 1);
+        snprintf(old_name, sizeof(old_name) - 1, "%s:capture_%d", fClientControl.fName, i + 1);
+        snprintf(name, sizeof(name) - 1, "%s:%s", fClientControl.fName, portnames[i]);
         if ((port_index = fGraphManager->AllocatePort(fClientControl.fRefNum, name, JACK_DEFAULT_AUDIO_TYPE, (JackPortFlags)port_flags, fEngineControl->fBufferSize)) == NO_PORT) {
             jack_error("driver: cannot register port for %s", name);
             return -1;
         }
+        free(portnames[i]);
         port = fGraphManager->GetPort(port_index);
         port->SetAlias(alias);
+        port->SetAlias(old_name);
         range.min = range.max = alsa_driver->frames_per_cycle + alsa_driver->capture_frame_latency;
         port->SetLatencyRange(JackCaptureLatency, &range);
         fCapturePortList[i] = port_index;
@@ -107,13 +115,16 @@
 
     for (int i = 0; i < fPlaybackChannels; i++) {
         snprintf(alias, sizeof(alias) - 1, "%s:%s:in%d", fAliasName, fPlaybackDriverName, i + 1);
-        snprintf(name, sizeof(name) - 1, "%s:playback_%d", fClientControl.fName, i + 1);
+        snprintf(old_name, sizeof(old_name) - 1, "%s:playback_%d", fClientControl.fName, i + 1);
+        snprintf(name, sizeof(name) - 1, "%s:%s", fClientControl.fName, portnames[i+fCaptureChannels]);
         if ((port_index = fGraphManager->AllocatePort(fClientControl.fRefNum, name, JACK_DEFAULT_AUDIO_TYPE, (JackPortFlags)port_flags, fEngineControl->fBufferSize)) == NO_PORT) {
             jack_error("driver: cannot register port for %s", name);
             return -1;
         }
+        free(portnames[i+fCaptureChannels]);
         port = fGraphManager->GetPort(port_index);
         port->SetAlias(alias);
+        port->SetAlias(old_name);
         // Add one buffer more latency if "async" mode is used...
         range.min = range.max = (alsa_driver->frames_per_cycle * (alsa_driver->user_nperiods - 1)) +
                          ((fEngineControl->fSyncMode) ? 0 : fEngineControl->fBufferSize) + alsa_driver->playback_frame_latency;
@@ -137,6 +148,8 @@
         }
     }
 
+    free(portnames);
+
     if (alsa_driver->midi) {
         int err = (alsa_driver->midi->attach)(alsa_driver->midi);
         if (err)
--- a/linux/wscript
+++ b/linux/wscript
@@ -54,6 +54,7 @@
                        'alsa/hdsp.c',
 		       'alsa/alsa_driver.c',
                        'alsa/hammerfall.c',
+                       'alsa/port_names.c',
                        'alsa/ice1712.c'
                        ]
 
```

I see no reason why such PR/patch would be blocked, assuming it works properly and gets some testing.

**Comment by agraef** [comment]
Thanks @falkTX, that looks like the right way to do it. I already suspected that there might be another place where the port names are mangled, now I know where (JackAlsaDriver.cpp). :) I'll give this a go and report back.

**Comment by agraef** [comment]
Nope, this just loads port names for the *audio* device from config files in some location in ~/.config/jack (which doesn't  even exist on my system). In any case, the MIDI port names are unchanged. So this is unrelated and doesn't fix the issue.

But it seems that I'm on the right track with https://github.com/agraef/jack2/tree/jack-midi-portnames. I just need to figure out how I can get the real ALSA port names instead of the generic capture/playback names. This should be easy.

**Comment by agraef** [comment]
Ok, I have this working now. It uses the same port naming as Jack1 (while keeping the old generic port names around as aliases so that Jack2 applications which expect to find these will hopefully continue to work):

![image](https://github.com/jackaudio/jack2/assets/2853977/b814f4e4-31af-47a1-bded-e444549b7dc3)

I still need to give alsa_ramidi.c the same treatment, then I'll submit a PR. Stay tuned.

**Comment by agraef** [comment]
All right, here's how -Xraw looks now:

![image](https://github.com/jackaudio/jack2/assets/2853977/fea65d56-8757-48a1-b27a-10864c2ff1aa)

Yeah, the raw MIDI port names aren't all that pretty, but at least they tell you what you need to know. :) We can always beautify them later.

PR is now up at #945. Filipe, over to you!

**Comment by agraef** [comment]
Gave the raw MIDI port names another facelift, so that they look like the seq ones. I think that I'm finished with this, it now looks exactly like I wanted.
