### ISSUE TITLE
JACK protocol mismatch (8 vs 9) when using a 32bit client and a 64bit server

### ISSUE THREAD

**Issue by RaphaelNeubert** [jackaudio/jack2#954]
I think this problem https://github.com/wineasio/wineasio/issues/71 might be caused by jack. 

Besides the stuff already discussed in the issue, i've tried to install everything on a new drive running a fresh opensuse install since that 
uses the most recent jack release.  After installing everything i ran into the exact same problem. The client is using protocol version 8 and the server is using protocol version 9. Everything jack related comes from the most recent jack release which uses protocol version 9. 

I don't see why the bitness should change the jack protocol version.

**Comment by falkTX** [comment]
> I don't see why the bitness should change the jack protocol version.

it doesnt, it is literally impossible for that to happen.

so the 32bit jack libs you have around were built with a different jack2 version.

you can create a small C tool that fetches the jack version and prints it out, then buid 32bit and 64bit. I am positive they will print different values.

how to solve this is entirely on your side.

**Comment by RaphaelNeubert** [comment]
> you can create a small C tool that fetches the jack version and prints it out, then buid 32bit and 64bit. I am positive they will print different values. 

Alright so i have the following programm:
```
#include <stdio.h>
#include <jack/jack.h>

int main()
{
        printf("JACK version: %s\n", jack_get_version_string());
        return 0;
}
```
When i compile it with `gcc main.c -ljack` and run it it prints:
JACK version: 1.9.22
When i run ldd on it to see which libs are linked it gives me:
```
        linux-vdso.so.1 (0x00007ffcc5551000)
        libjack.so.0 => /usr/lib64/libjack.so.0 (0x00007f4529177000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f4528fa5000)
        libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/13/libstdc++.so.6 (0x00007f4528c00000)
        libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/13/libgcc_s.so.1 (0x00007f4528f81000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f45291f9000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f4528ea9000)

```
When i compile it with `gcc main.c -m32 -ljack` and run it it prints:
JACK version: 1.9.22
and ldd on the executable gives me:
```
linux-gate.so.1 (0xf7f8f000)
        libjack.so.0 => /usr/lib/libjack.so.0 (0xf7f03000)
        libc.so.6 => /lib/libc.so.6 (0xf7c00000)
        libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/13/32/libstdc++.so.6 (0xf7800000)
        libm.so.6 => /lib/libm.so.6 (0xf7e35000)
        libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/13/32/libgcc_s.so.1 (0xf7bd7000)
        /lib/ld-linux.so.2 (0xf7f91000)
```
As you can see, both the 32bit and the 64bit libraries are jack version 1.9.22. 
Is there any way to print the protocol version of a jack client? 

I guess my next step could be creating a jack client and trying to connect to the server and see if i have the same issues as in wineasio.

Any other ideas on how i can troubleshoot this?

**Comment by falkTX** [comment]
ok something very weird is happening then. I suspect that 32bit client would be able to access the jack server too.

specially since the protocol bump was done in 13d5eccba44d615767892c6c93cb73c9b15587f0.
and as we can see through https://github.com/jackaudio/jack2/commits/develop/common that change was done for the 1.9.20 release.

maybe your wine installation is bringing some other custom libjack?
`locate libjack.so.0`might help in that case, to see where those libs are (or `dpkg -S libjack.so.0` variant for your distro)

**Comment by falkTX** [comment]
also if you run jackd/jackdbus with verbose option enabled, you should be able to see a print of client and server protocol version, as per https://github.com/jackaudio/jack2/blob/250420381b1a6974798939ad7104ab1a4b9a9994/common/JackEngine.cpp#L488

**Comment by RaphaelNeubert** [comment]
locate libjack.so.0 gave it away.
Apparently the steam runtime is using its own libjack.so, they have like 10 libjack.so's in different locations.
I will have to find out how to replace them (savely).

Thank you very much for your patience, i was starting to become crazy.

**Comment by RaphaelNeubert** [comment]
related: https://github.com/ValveSoftware/steam-runtime/issues/438
