### ISSUE TITLE
Ardour session export does not work anymore with "-d alsa"

### ISSUE THREAD

**Issue by rcspam** [jackaudio/jack2#96]
Hi,
It's impossible to export ardour session to audio file with "-d alsa" parameter.
Qjackctl start it with "/usr/bin/jackd -u -dalsa -dhw:0 -r48000 -p256 -n2 -H -M -D -Chw:Intel,0"
I use the jack2 version from kxstudio (stable 1.9.10 release) from 23-Aug-2014
To export my session i must run "jack -d dummy"...

**Comment by x42** [comment]
Works just fine here.
Can you run jack in verbose mode? that may provide some clues.

**Comment by x42** [comment]
can you try just `jackd -dalsa -dhw:0 -r48000 -p256` ?

**Comment by rcspam** [comment]
It works.... Can you explain what is wrong in qjackctl config?

**Comment by rcspam** [comment]
I dont understand if run "jackd -u -dalsa -dhw:0 -r48000 -p256 -n2 -H -M -D -Chw:Intel,0" directly from command line , it works.
If i run it from cadence idem no problem.
Sorry for post issue here.
But is someone can explain to me what's the problem with qjackctl.
![reglages - kit de connexion audio jack_001](https://cloud.githubusercontent.com/assets/10021906/5968004/3179479e-a813-11e4-9b32-8a6be0dfe78d.png)

**Comment by rcspam** [comment]
I ve found the problem...
There was an activated patchbay in qjackctl !!
Incredible.... I am Very Sorry.... The good side of my  that It can help if someone have the same problem.
Regards and thousands of sorry

**Comment by lilrc** [comment]
You seem to have solved it yourself. Closing.
