### ISSUE TITLE
CMake FTW

### ISSUE THREAD

**Issue by robiwano** [jackaudio/jack2#994]
I note that for some inexplicable reason, JACK does not use CMake as build system, but **waf** and then moving to **meson** (another build system no one has heard of). I've worked with CMake since 2007 and despite it having its flaws (albeit very few today at v3.31), today it is widely accepted as THE standard build system for C/C++ projects, on ALL platforms.

I rely on CMake for ALL my projects and using libraries with CMake support makes it a breeze to setup new projects.

But I have no idea on how to add JACK as a library dependency for my new CMake project. The problem is that I cannot rely on the usual  "make install" procedures as I am cross compiling, so I need to build JACK as part of the build process. CMake has ExternalProjects support which might be possible to use for setting this up (I've done it for ALSA before), but it is a nuisance.

I can probably create a basic CMakeLists.txt file for JACK, if you'd be interested.

**Comment by falkTX** [comment]
I have no interest on adding cmake to jack, meson is the approach selected to many opensource developers and projects and quite mature by now. Take it more of a coincidence that you never heard of it, I see it quite a lot.

for finding jack libs, you should just use pkg-config which is the standard way to find libraries for opensource tools.

**Comment by robiwano** [comment]
> for finding jack libs, you should just use pkg-config which is the standard way to find libraries for opensource tools.

You obviously missed the part about **cross compling**, where there is no package/library to be found.
